import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `wrangler types` — regenerated on every deploy.
    "worker-configuration.d.ts",
    // Wrangler build output (dev/deploy temp bundles).
    ".wrangler/**",
    // The Android wrapper embeds a copy of the built app (out/) as WebView
    // assets; those minified chunks are not lint targets.
    "android/**",
  ]),
]);

export default eslintConfig;
