import type { Dict } from "../i18n";

export const haDict: Dict = {
    n_home: "Gida", n_explore: "Binciko", n_find: "Nemi Kula", n_services: "Ayyuka",
    n_health: "Lafiya", n_profile: "Bayanan", n_provider: "Mai bayarwa", n_admin: "Gudanarwa", n_account: "Asusu",
    h_title: "Ta yaya zamu taimaka muku a yau?",
    h_sub: "Koyi game da lafiyar ku, duba lambobin ku, nemi kulawa mai kyau, ku saka ido ga masu bayar da kulawa.",
    h_learn: "Koyi game da lafiya", h_learn_d: "Labarai masu sauki kan cututtuka da rigakafi.",
    h_check: "Duba lafiyar ku", h_check_d: "Gwaji, asibitoci, da shafi na lafiyar ku.",
    h_find: "Nemi kula a kusa", h_find_d: "Asibitoci, PHC, dakunan gwaji, kantin magani da kwararru a jihar ku.",
    h_connect: "Saka ido ga mai kula", h_connect_d: "Tuntuɓi masu bayar da kulawa kai tsaye don yin booking.",
    h_search: "Bincika batutuwan lafiya, cututtuka, ko ayyuka…",
    h_emergency: "Nemi taimako yanzu", h_emergency_d: "Lambobin gaggawa da matakan agaji.",
    h_browse: "Duba duk batutuwan lafiya", h_readmore: "Kara karatu",
    e_title: "Bincika ilimin lafiya", e_sub: "Zaɓi rukuni ko karanta wani batu a ƙasa.",
    e_allcat: "Duk rukunoni", e_topics: "Batutuwa", e_draft: "Daftari", e_publish: "Buga", e_report: "Rahoto",
    f_title: "Nemi Kula", f_sub: "Nemi asibitoci, PHC, dakunan gwaji, kantin magani da kwararru — ku tuntuɓi su kai tsaye.",
    f_search: "Nemi da suna, aiki, ko LGA…", f_all: "Duk rukuni", f_verified: "An tabbatar", f_call: "Kira",
    f_whatsapp: "WhatsApp", f_dir: "Hanyar", f_request: "Nemi ziyara", f_reportP: "Rahoton mai bayarwa",
    f_open_24: "Yana buɗe 24 awa", f_no_results: "Babu mai bayarwa da ya dace da bincikenku.", f_services: "Ayyuka",
    f_hours: "Lokaci", f_desc: "Game da wannan wurin",
    s_title: "Ayyuka", s_sub: "Duba lafiyar ku kuma ku yi booking na ayyukan rigakafi.",
    s_book: "Yi booking na aiki ko ziyara", s_received: "An karɓi buƙatar",
    em_title: "Nemi Taimako Yanzu", em_sub: "Jagorancin gaggawa da inda za a kira.",
    hh_title: "Lafiya Ta", hh_sub: "Gurin ku — motsa jiki, rikodi, ci gaba.",
    hh_exercise: "Motsa jiki & nauyi", hh_exercise_d: "Yi motsa jiki kullum, sa masu tunani, bin diddigin nauyi.",
    hh_journal: "Littafin lafiya", hh_journal_d: "Halin, alamomi da lafiya ta yau da kullum.",
    hh_records: "Bayanan lafiya", hh_records_d: "Ziyara, sakamakon dakin gwaji da takardu.",
    hh_reminders: "Abubuwan tunatarwa", hh_reminders_d: "Magani, motsa jiki, alƙawura.",
    a_title: "Asusu", a_sub: "Ƙirƙiri asusu na son rai ko ci gaba kamar baƙo.",
    a_name: "Cikakken suna", a_email: "Imel", a_phone: "Waya", a_role: "Ni ne",
    a_consumer: "Mara lafiya / al'umma", a_provider: "Mai bayar da lafiya", a_admin: "Ƙungiyar CareNBuddi",
    a_signup: "Ƙirƙiri asusu", a_signin: "Shiga", a_signout: "Fita",
    a_send_code: "Aiko mini lambar sirri", a_verify: "Tabbatar", a_code: "Lambar 6",
    a_language: "Harshe", a_language_d: "Canza harshen dashboard da abun cikin lafiya.",
    a_demo: "Shiga demo", a_demo_admin: "Buɗe demo gudanarwa", a_demo_provider: "Buɗe demo mai bayarwa", a_demo_consumer: "Buɗe demo mara lafiya",
    a_welcome: "An shigar da kai", c_back: "Baya", c_save: "Ajiye", c_cancel: "Soke",
    a_password: "Kalmar sirri",
    a_cloud: "Asusun cloud",
    a_cloud_d: "Yi shiga don adana bayanai kuma yi amfani da CareNBuddi a kowane na'ura.",
    a_signed_in_as: "An shiga da",
    a_sync_now: "Sanya yanzu",
    a_syncing: "Ana aiki…",
    a_synced: "An adana duk bayanan",
    a_sync_idle: "Shanye don aiki",
a_sync_off: "Buga kyauta — bayanai suna kan wannan na'ura kawai",
  a_offline_note: "Aiki a offlain — bayananka kan nan gida. Shiga don sanya tare tsakanin na'urori.",
  auth_or: "ko",
  auth_google: "Google",
  auth_apple: "Apple",
  a_confirm_email: "An ƙirƙiri asusun. Duba imel ɗinka don tabbatar, sannan yi shiga.",
    a_bad_login: "Imel ko kalmar sirri ba daidai ba ne.",
    a_missing_fields: "Shigar da imel ɗinka da kalmar sirri.",
    c_remove: "Cire", c_send: "Aika", c_new: "Sabo", c_status: "Matsayi", c_pending: "Jiran",
    c_approved: "An amince", c_rejected: "An ƙi", c_resolved: "An warware", c_none: "Babu",
    c_manage: "Sarrafa", c_reason: "Dalili",
    pv_title: "Mashaya mai bayarwa", pv_sub: "Sarrafa bayanan wurin ku da buƙatun kulawa.",
    pv_register: "Yi rajistar wurin ku", pv_requests: "Buƙatun tuntuɓa / booking", pv_profile: "Bayanan wuri na",
    pv_services: "Ayyuka", pv_save: "Ajiye bayanan", pv_pending: "Ana duba rajistar ku.",
    pv_none: "Babu wuri da aka tabbatar a wannan asusu.",
    pv_new_req: "Sabbin buƙatun", pv_confirm: "Alama aka tuntuɓa",
    ad_title: "Mashaya gudanarwa", ad_sub: "Abubuwa, tabbatarwa, masu amfani, kididdiga da tsaro.",
    ad_overview: "Kallo", ad_content: "Abun ciki", ad_verification: "Tabbatarwa",
    ad_users: "Masu amfani", ad_analytics: "Kididdiga", ad_reports: "Rahotanni",
    ft_nav: "CareNBuddi — Tsarin Kewayon Lafiyar Ku na Kai Tsaye.",
    ft_desc: "Muna haɗa ilimin lafiya da mataki mai kyau — duba lambobin ku, nemi kulawa da aka tabbatar, yi booking na ayyuka, ku bi diddigin — ga daidaikun mutane, iyalai da al'ummomi a Najeriya.",
    ft_notdx: "CareNBuddi yana ba da bayanin lafiya na gabaɗaya da kewayawa. Ba binciken likita ba ne kuma baya maye gurbin ƙwararren lafiya.",
    ft_emergency: "A gaggawa, koyaushe kira lambar gaggawa ta gida da farko — kafin amfani da wannan dandali.",
    ft_lang: "Akwai cikin Turanci, Yarbanci, Hausa da Igbo.",
    ft_report: "Nemi bayani da ba daidai ba ko ya tsufa",
  n_chronic: "Kulawar cututtukan da suka daɗe", n_chronic_d: "Jagorori don cututtuka kamar hawan jini.",
  n_journey: "Tafiyar lafiya", n_journey_d: "Bayanan ku da ziyarta cikin layin lokaci guda.",
  n_carecircle: "Da'irar Kulawa", n_carecircle_d: "Lafiyar iyali a gani daya.",
  n_healthdays: "Kwanakin Lafiya", n_healthdays_d: "Gwaje-gwajen al'umma da bibiyarwa.",
  n_worker: "Yanayin ma'aikaci", n_worker_d: "Kayan aiki na masu aikin lafiya na al'umma.",
  n_ask_d: "Jagor neman yanayi, kulawa da dandali.",
  cc_title: "Abokin Kulawar Cututtuka", cc_sub: "Tsarin yau da kullum da nazarin wata don cututtuka da suka daɗe.",
  cc_today: "Yau", cc_month: "Wannan wata", cc_latest: "Na baya-bayan nan", cc_care: "Kulawa", cc_find: "Nemo wurin kulawa kusa →",
  cc_hypertension: "Tafiya Hauwan Jini", cc_diabetes: "Tafiya na Ciwon Sugar",
  cc_sicklecell: "Tafiya na Ciwon Kwayar Jini", cc_asthma: "Tafiya na Shaqa",
  cc2_title: "Da'irar Kulawa", cc2_sub: "Bibiyar lafiyar wadanda kuke kula da su.",
  cc2_remove: "Cire", cc2_bp: "BP", cc2_med: "Magani", cc2_appt: "Alƙawari", cc2_screen: "Bincike na gaba",
  cc2_add: "Ƙara memba na iyali", cc2_name: "Suna / lakabi", cc2_rel: "Dangantaka", cc2_save: "Ajiye", cc2_cancel: "Soke", cc2_addb: "Ƙara memba",
  hd2_title: "Kwanakin Lafiyar Al'umma", hd2_sub: "Gwaje-gwaje da ilimi inda mutane ke taruwa.",
  hd2_create: "Ƙirƙiri rana lafiya", hd2_f_title: "Suna", hd2_f_org: "Mai shiryawa (coci, makaranta…)",
  hd2_f_date: "Kwanan wata", hd2_f_loc: "Wuri", hd2_f_srv: "Ayyuka", hd2_save: "Ƙirƙirar", hd2_cancel: "Soke", hd2_createb: "Ƙirƙiri rana lafiya",
  jt_title: "Tafiyar Lafiyar Ku", jt_sub: "Duk abin da ya faru, cikin layi guda.",
  pp_title: "Fasfo na Lafiya", pp_sub: "Bayani ɗaya. Tarihin lafiya ɗaya. A kowane wuri.",
  pp_details: "Cikakkun bayanai", pp_edit: "Gyara", pp_save: "Ajiye", pp_cancel: "Soke",
  pp_name: "Cikakken suna", pp_blood: "Jinin", pp_allergies: "Allergies", pp_meds: "Magungunan da ake bawa",
  pp_conditions: "Cututtuka da suka daɗe", pp_history: "Tarihin magani", pp_imm: "Alurar riga kafi", pp_hmo: "Inshora / HMO",
  pp_ec: "Mai tuntuɓar gaggawa", pp_ecp: "Wayar gaggawa",
  pp_card: "Katin gaggawa", pp_card_d: "Nuna wannan ga ma'aikacin lafiya a gaggawa.", pp_scan: "Duba da manhajar ma'aikatan CareNBuddi",
  w_title: "Yanayin Ma'aikacin Lafiya", w_sub: "Gwaje-gwaje, turawa da bibiyarwa daga filin aiki.",
  w_events: "Abubuwan", w_participants: "An gwada", w_referred: "An tura", w_pending: "Bibiyarwa ake buƙata",
  w_log: "Rubuta gwaji", w_add: "Ƙara", w_recent: "Rubutun baya-bayan nan", w_sync: "Ana adanawa a na'ura kuma za a aika idan an dawo da intanet.", w_days: "Duba kwanakin lafiya →",
  ask_title: "Tambayi CareNBuddi", ask_ph: "Tambaya kan yanayi, samun kulawa, farashi…", ask_send: "Aika",
  f_cost: "Farashi", f_any_cost: "Duk farashi", f_low_cost: "₦ Ƙasa", f_mid_cost: "₦₦ Matsakaici", f_high_cost: "₦₦₦ Mai tsada",
  h_tagline: "Kyakkyawan Bayani. Lafiyarku.",
  e_report_reason: "Damuwa da ta dace da daidai bayani ko tsaro",
  f_location: "Wuri",
  f_category: "Rukuni",
  f_all_states: "Dukkan jihohi",
  f_facility_one: "wurin",
  f_facility_many: "wuraren",
  f_book_sent: "An aika buƙatar. Wurin zai tuntube ku.",
  f_form_msg: "Saƙo",
  f_form_date: "Ranar da aka fi so",
  f_emergency: "Ana samun sabis na gaggawa a wannan wurin sa'o'i 24.",
  f_provider_visit: "Ziyarar mai bayarwa",
  s_we_provide: "Ayyukan lafiya da muke bayarwa",
  s_check_head: "Duba Lafiyata",
  s_open_health: "Bude shafata na lafiya",
  s_intro: "Nemi aikin tantancewa, walwala ko asibiti ta wayar hannu don kanka, iyalinka, ma'aikatunka ko al'ummarka. Ba buƙatar biya don neman — wani daga ƙungiya zai tabbatar da bayanai ta waya.",
  s_form_head: "Nemi aiki ko ziyara",
  s_service: "Aiki",
  s_date: "Ranar da aka fi so",
  s_area: "Yanki / al'umma / wurin aiki",
  s_submit: "Nemi aiki",
  s_free_note: "Ba buƙatar biya don neman. Wani daga ƙungiya zai tabbatar da cancantar ku, farashi da bayanai ta waya.",
  s_book_another: "Yi booking na ziyara wani",
  s_on_date: " a ",
  s_success: "Na gode {name}! Wani daga ƙungiyar CareNBuddi zai tuntube {phone} don tabbatar da ziyarar {service}{date}. Muna tabbatar da kowane booking ta waya da saƙon rubutu.",
  sc_bp: "Hawan jini",
  sc_bp_d: "Dubawa na BP mai sauki tare da shawara mai sauki.",
  sc_glu: "Glucose na jini",
  sc_glu_d: "Gwajin glucose da shawara kan rayuwa mai lafiya.",
  sc_well: "Duba wellness",
  sc_well_d: "Muhimman abubuwa da tantance lafiyar gaba.",
  srv_education: "Ilimin lafiya",
  srv_education_d: "Darussan harshe mai sauki game da rigakafi da halaye masu kyau.",
  srv_outreach: "Walwalar al'umma",
  srv_outreach_d: "Abubuwan gwaji da wayar da kai a unguwarku.",
  srv_corporate: "Lafiyar ma'aikata",
  srv_corporate_d: "Kwanakin lafiya na wurin aiki don kungiyoyi.",
  srv_mobile: "Ziyarar asibitocin tafi-da-gidanka",
  srv_mobile_d: "Gwaji, walwala da ayyukan lafiya inda kuka kasance.",
  srv_referral: "Ayyuka na tura zuwa",
  srv_referral_d: "Taimako na jagorantar zuwa mai bayarwa dake daidai.",
  srv_campaigns: "Kamfen na lafiya",
  srv_campaigns_d: "Kwanakin gwaji na al'umma kamar “San Lambunanka”.",
  em_call: "Kira lambar gaggawa nan take",
  em_call_d: "Idan akwai rashin sani, ciwon kirji, wahalar numfashi, zubar jini mai yawa, cikakkiya, bugun jini ko wani rikici — kada ku jira kuma kada ku dogara da app.",
  em_while: "Yayin da kuke neman taimakon kwararru",
  em_s1: "Kare kanka da mutumin — kar a motsa shi sai idan yana cikin hatsari.",
  em_s2: "Idan bai sani ba amma yana numfashi, sanya shi a matsayin dawo da hankali.",
  em_s3: "Ga kona, zuba ruwan famfo mai sanyi a kansa na akalla mintuna 20 — kar a yi amfani da kankara, man shanu ko man shafa dibero.",
  em_s4: "Ga zubar jini, danna rauni da karfi da tsabtataccen kaya.",
  em_s5: "Ga alamun bugun jini (fuskantar zainuwar, rauni a hannu, magana mai ruɗani), je wurin gaggawa da sauri.",
  em_find_care: "Nemo kulawa dake da sabis na gaggawa",
  em_find_d: "Don kulawa ba mai barazana ba, nemo wurin dake bayar da sabis na gaggawa kusa da ku.",
  em_find_hospital: "Nemo asibiti",
  em_find_clinic: "Nemo asibiti",
  em_footer: "A cikin gaggawa, kira sabis na gaggawa da farko. CareNBuddi na ilimi da jagora ne kawai.",
  hh_know: "San lambarku",
  hh_open: "Bude",
  hh_know_d: "Fara Kwanacin Lafiya na Al'umma na CareNBuddi ko yin booking na asibiti ta wayar hannu don duba hawan jinin ku da glucose tare da kulawar kwararru.",
  n_passport: "Fasfo",
  n_ask: "Tambaya",
  a_code_sent: "An aika da imel na demo — duba lambar a ƙasa.",
  a_email_required: "Shigar da imel da farko.",
  a_code_mismatch: "Lambar ba ta dace ba. Duba ka sake gwadawa.",
  a_demo_mode: "Yanayin demo yana nuna lambar maimakon aika imel.",
  a_demo_note: "Wuraren mai bayarwa da admin ana tsarinsu ta hanyar matsayi a cikin hanyoyin shiga.",
  a_email_ph: "kai@misali.com",
  a_member_default: "Memba na CareNBuddi",
  pv_confirm_done: "Tabbatar",
  pv_guard: "Wannan yanki na masu bayarwa da aka tabbatar ne. Shiga tare da asusun mai bayarwa ko admin don ci gaba.",
  pv_services_label: "Ayyuka (rabu da comma)",
  pv_about: "Game da wannan wurin",
  pv_no_message: "Babu saƙo",
  prg_lead: "Masu bayarwa suna rajista sau ɗaya; ƙungiyar CareNBuddi na tabbatar da kowane wuri kafin ya bayyana a Nemi Kulawa a matsayin mai bayarwa da aka tabbatar.",
  prg_facility: "Sunan wuri",
  prg_category: "Rukuni",
  prg_state: "Jiha",
  prg_lga: "LGA / yanki",
  prg_address: "Adireshi",
  prg_submit: "Mika don tabbatarwa",
  prg_note: "Tabbatarwa tana kare al'umma: masu bayarwa da aka tabbatar ne kawai ake nuna su da alamar ✓ a Nemi Kulawa.",
  prg_success_1: "An aika {facility} don dubawa.",
  prg_success_2: "Za ku iya sarrafa bukatunku da bayanan ku daga ma'aikacin mai bayarwa da zarar an amince da ku.",
  ad_signin_req: "Wannan yanki na ƙungiyar CareNBuddi ne. Yi amfani da asusun admin na demo don bincika sarrafa abun ciki, tabbatarwa, masu amfani, kididdiga da rahotanni.",
  ad_providers: "Masu bayarwa",
  ad_verified_p: "Masu bayarwa da aka tabbatar",
  ad_topics: "Batutuwa",
  ad_verify_pending: "Tabbatarwa masu jiran",
  ad_bookings: "Bookings",
  ad_reports_open: "Rahotanni masu bude",
  ad_c_add: "Addara batu (daftari)",
  ad_c_slug: "slug",
  ad_c_title: "Taken",
  ad_c_summary: "Takaitawa",
  ad_c_category: "Rukuni",
  ad_c_add_draft: "Addara daftari",
  ad_c_publish: "Buga",
  ad_c_unpublish: "Cire daga buga",
  ad_c_delete: "Share",
  ad_c_required: "Ana buƙatar slug da taken.",
  ad_c_draft_note: "Daftari — addara takaitawa kafin bugawa.",
  ad_c_empty_summary: "Zaidi.",
  ad_c_exists: "Akwai batu da wannan slug riga.",
  ad_c_created: "An halicci daftari — buga daga jerin dake ƙasa.",
  ad_v_none: "Babu buƙatun rajista.",
  ad_v_verify: "Tabbatar & buga",
  ad_v_reject: "Ƙi",
  ad_v_approved_desc: "CareNBuddi ne ya tabbatar bayan duba takardun.",
  ad_u_name: "Suna",
  ad_u_email: "Imel",
  ad_u_role: "Matsayi",
  ad_u_joined: "Shugaba",
  ad_a_cat: "Masu bayarwa ta rukuni",
  ad_a_state: "Masu bayarwa ta jiha",
  ad_a_bookings: "Buƙatun booking — kwanakin 14 da suka wuce",
  ad_a_requests: "Buƙatu",
  ad_a_pipeline: "Jerin rajista:",
  ad_a_submitted: "an mika",
  ad_a_approved: "an amince",
  ad_a_pending0: "suna jiran",
  ad_r_none: "Babu rahotanni.",
  ad_r_resolve: "Warware",
  pr_requests: "Buƙatuna",
  pr_no_requests: "Babu buƙatun booking tukuna.",
  pr_get_started: "don fara.",
  pr_provider: "Ziyarar mai bayarwa",
  pr_appt: "Alƙawura",
  pr_appt_d: "Ziyarun dake zuwa da buƙatu za su bayyana a nan.",
  pr_rem: "Abubuwan tunatarwa",
  pr_rem_d: "Ana shirin tunatarwa na magani da gwaji.",
  pr_saved: "Masu bayarwa da aka ajiye",
  pr_saved_d: "Alamar wuraren da kwararru da kuke amince da su.",
  pr_records: "Bayanan lafiya",
  pr_records_d: "Bayanan suna bayyana ne kawai inda doka ta yarda.",
  pr_soon: "Zaidi",
  j_title: "Littafin lafiya",
  j_sub: "Rubuta halinka, alamomi, da muhimman abubuwa a kowace rana.",
  j_new: "Sabataccen shiga",
  j_date: "Kwanan wata",
  j_mood: "Halitta",
  j_symptoms: "Alamomi",
  j_weight: "Nauyi (kg)",
  j_heart: "Bugun zuciya (bpm)",
  j_sleep: "Barci (hrs)",
  j_steps: "Matakai",
  j_bp_sys: "BP na sama",
  j_bp_dia: "BP na ƙasa",
  j_notes: "Bayani",
  j_note_ph: "Yaya ranarka ta kasance?",
  j_save: "Ajiye shiga",
  j_empty: "Babu shigarwar journal tukuna. Addara ta farko.",
  j_collapse: "Nara",
  j_details: "Cikakkun bayanai",
  j_delete: "Share",
  r_title: "Abubuwan tunatarwa",
  r_sub: "Magani, ruwa, aiki, da alƙawura.",
  r_new: "Sabon abun tunatarwa",
  r_title_field: "Taken",
  r_title_ph: "misali. Maganin yamma",
  r_time: "Lokaci",
  r_type: "Iri",
  r_repeat: "Maimaita a",
  r_notes: "Bayani",
  r_notes_ph: "Ƙarin bayani…",
  r_add: "Addara abun tunatarwa",
  r_today: "Yau",
  r_none_today: "Babu abin da aka shirya don yau.",
  r_all: "Duk abubun tunatarwa",
  r_none: "Babu abun tunatarwa tukuna. Addara na farko.",
  r_on: "A kan",
  r_off: "A kashe",
  r_disable: "Kashe",
  r_enable: "Kunnuwa",
  r_delete: "Share",
  rc_title: "Bayanan likit a",
  rc_sub: "Tsaya dasuwar zubar da shawara na ziyara, sakamakon dakin gwaji, da magunguna.",
  rc_add: "Addara bayanai",
  rc_title_field: "Taken",
  rc_title_ph: "misali. Sakamakon gwajin jini",
  rc_provider: "Mai bayarwa / wurin aiki",
  rc_provider_ph: "misali. Dr. Smith, City Clinic",
  rc_date: "Kwanan wata",
  rc_category: "Rukuni",
  rc_summary: "Takaitawa / sakamako",
  rc_summary_ph: "Muhimman bayanai ko bayani…",
  rc_link: "Hanyar haɗi (zaɓi)",
  rc_save: "Ajiye bayanai",
  rc_all: "Duk",
  rc_empty: "Babu bayanai a nan tukuna.",
  rc_delete: "Share",
  rc_open: "Bude bayanan da aka ɗora",
  ex_back: "Komawa Lafiya Ta",
  ex_title: "Jagorancin Motsa Jiki & Nauyi",
  ex_sub: "Saita burinku, rubuta ayyukanku a kowace rana, kuma duba ci gaban ku. Bayananku ya zauna akan wannan na'ura.",
  ex_streak: "{n} kwanakin sauka",
  ex_goal_1: "Burinku",
  ex_loss_goal: "Burin rage nauyi",
  ex_gain_goal: "Burin kara nauyi",
  ex_goalfmt: " — daga {start} kg zuwa {goal} kg (tsayin {h} cm).",
  ex_height: "Tsayi (cm)",
  ex_start_w: "Nauyin farawa (kg)",
  ex_goal_w: "Nauyin buri (kg)",
  ex_save_goal: "Ajiye buri",
  ex_today_w_ph: "Rubuta nauyin yau (kg)",
  ex_record_w: "Rubuta nauyi",
  ex_warn: "Da fatan za a mayar da tsayi, nauyin farawa da nauyin buri a cm / kg.",
  ex_cur_w: "Nauyin yanzu",
  ex_lost: "Ragewa",
  ex_gained: "Karawa",
  ex_to_goal: "zuwa buri",
  ex_progress: "Ci gaban jagorar",
  ex_goal_x: "Buri {g} kg",
  ex_week_active: "Mai aiki wannan mako",
  ex_logged_today: "{n} an rubuta yau",
  ex_weight_journey_2: "Jagorancin nauyi",
  ex_checkins: "{n} dubawa",
  ex_goal_label: "Buri",
  ex_date: "Kwanan wata",
  ex_weight: "Nauyi",
  ex_change: "Canji",
  ex_start: "farawa",
  ex_train_3: "Horar a kowace rana",
  ex_done: "Yi yau",
  ex_not_done: "Ba a yi ba tukuna yau",
  ex_exercise: "Motsa jiki",
  ex_minutes: "Mintuna",
  ex_note_opt: "Bayani (zaɓi)",
  ex_note_ph: "misali. ji daɗi, zangon safe",
  ex_log: "Rubuta motsa jiki",
  ex_remove: "Cire",
  ex_no_today: "Ba a rubuta motsa jiki yau ba. Zaba motsa jiki a sama ko daga ɗakin karatu a ƙasa.",
  ex_reminder_4: "Tunatarwar motsa jiki a kowace rana",
  ex_rem_on: "Mai aiki — an kafa tunatarwa don {time}.",
  ex_rem_off: "Tunatarwa tana kashe.",
  ex_rem_time: "Lokacin tunatarwa",
  ex_rem_note: "Tunatarwa ta yankin tana taimaka muku ci gaba da dabi'a ta kullum. Ana shirya aiko saƙonni don MVP na dijital.",
  ex_library_5: "Dakin karatu na motsa jiki",
  ex_library_d: "Hotuna da bidiyo na motsa jiki iri-iri. Zaba ɗaya kuma rubuta shi a matsayin motsa jiki na yau.",
  ex_hide: "Boye",
  ex_howto: "Yadda ake yi",
  ex_log_today: "Rubuta yau",
  ex_media_1: "Don bada ƙarin hotunanka da kai: zuba hotuna a",
  ex_media_2: "da bidiyo a",
  ex_media_3: "Za su bayyana ta atomatik.",
  hd_when: "Lokacin da ya kamata a nemi taimakon kwararru",
  hd_what: "Menene",
  hd_symptoms: "Alamomi da alamun haɗari",
  hd_risk: "Abubuwan hadari",
  hd_prevention: "Rigakafi",
  hd_faqs: "Tambayoyi akai-akai",
  hd_read_more: "Kara karatu",
  hd_reviewed: "An sake dubawa da",
  hd_report: "Rahoto",
  hd_source: "Tushe:",
  hd_find_help: "Nemo Taimako Kusa Dake",
  sv_emergency: "Gaggawa",
  sv_hospitals: "Asibitoci",
  sv_phc: "Wuraren lafiya na farko",
  sv_labs: "Dakunan gwaji",
  sv_pharmacies: "Kantin magani",
  sv_professionals: "Kwararru",
  count_results: "{n} mai bayarwa",
  lang: "Harshen Hausa",

  // Mobile app redesign: appointments, find care, health, profile, auth, onboarding
  home_guest: "Baƙo",
  home_overview: "Bayani kan lafiya",
  home_next_appt: "Alƙawarin gaba",
  home_no_appt: "Babu alƙawari tukuna",
  home_view: "Duba",
  home_reminders: "Abubuwan tunatarwa",
  home_meds: "Magunguna",
  home_bp: "Hawan jini",
  home_meds_due_1: "Akwai tunatarwar magani 1 da ke aiki",
  home_meds_due_n: "{n} tunatarwar magunguna suna aiki",
  home_no_meds: "Babu tunatarwar magani",
  home_details: "Cikakkun bayanai",
  home_quick: "Ayyukan gaggawa",
  home_upcoming: "Alƙawarin dake zuwa",
  home_all: "Duk",
  home_no_appt_title: "Babu alƙawari da aka yi",
  home_no_appt_d: "Nemi mai bayarwa kuma ka yi booking cikin dannawa kaɗan.",
  home_find_care: "Nemi kula",
  home_nearby: "Sabis na lafiya kusa da ku",
  home_see_all: "Duba duka",
  home_tips: "Nasihu kan lafiya",
  home_emergency_d: "Kada ku jira app. Kira lambar gaggawa da farko, sannan ku amfani da CareNBuddi bayan haka.",
  home_call_112: "Kira 112",
  home_passport_d: "Katin gaggawar ku da taƙaitaccen bayanin lafiyarku",
  hx_title: "Motsa jiki & walwala",
  home_wellness_d: "Matakai, nauyi da barci",
  f_cost_low: "₦ Farashi ƙasa",
  f_cost_high: "₦₦₦ Mai zaman kansa",
  f_cost_mid: "₦₦ Matsakaici",
  appt_rescheduled: "An sake tsara alƙawari",
  appt_cancelled_toast: "An soke alƙawari",
  appt_title: "Alƙawura",
  appt_sub: "Bi diddigin ziyarar ku kuma nemi sabon lokaci cikin dannawa kaɗan.",
  appt_refresh: "Sabunta alƙawura",
  appt_next: "Alƙawarin gaba",
  appt_view_provider: "Duba mai bayarwa",
  appt_reschedule: "Sake tsara",
  appt_reschedule_d: "Zaɓi sabon rana da lokaci",
  appt_cancel_visit: "Soke wannan ziyara",
  appt_cancel_visit_d: "Za a sanar da mai bayarwa",
  appt_none_title: "Babu alƙawari da aka yi",
  appt_none_d: "Nemi mai bayarwa da aka tabbatar kusa da ku kuma nemi ziyara cikin dannawa kaɗan.",
  appt_find_care: "Nemi kula",
  appt_tab_upcoming: "Dake zuwa",
  appt_tab_completed: "An kammala",
  appt_tab_cancelled: "An soke",
  appt_need_sooner: "Kuna buƙatar kulawa da wuri?",
  appt_services: "Nemi sabis na lafiya",
  appt_services_d: "Gwaje-gwaje, walwala da ziyarar asibitin tafi-da-gidanka",
  appt_emergency_d: "Lambobin gaggawa da matakan farko na agaji",
  appt_confirm_time: "Tabbatar da sabon lokaci",
  appt_current: "A halin yanzu",
  appt_pick_date: "Zaɓi rana",
  appt_pick_time: "Zaɓi lokaci",
  appt_cancel_title: "A soke wannan alƙawari?",
  appt_cancel_body: "Za a soke wannan alƙawari. Kuna iya sake booking daga baya.",
  appt_cancel_confirm: "Ee, soke",
  appt_keep: "Bar shi",
  fc_sub: "Asibitoci, PHCs, dakunan gwaji, kantin magani da kwararru — tare da wurin da ke akwai nan gaba.",
  fc_refresh: "Sabunta sakamako",
  fc_clear_search: "Share bincike",
  fc_filters: "Tacewa",
  fc_error_title: "Ba za a iya ɗaukar sakamako ba",
  fc_error_d: "Ba za mu iya karanta jerin wuraren ku ba. Sake gwadawa nan da nan.",
  fc_retry: "Sake gwadawa",
  fc_empty_title: "Babu mai bayarwa da aka samu",
  fc_empty_d: "Gwada wani kalmar bincike dabam, ko share tacewar ku don ganin duk.",
  fc_clear_filters: "Share tacewa",
  fc_choose_state: "Zaɓi jiha",
  fc_reset: "Sake saiti",
  fc_show_n: "Nuna sakamako {n}",
  fc_name_req: "Shigar da cikakken sunan ku",
  fc_phone_req: "Shigar da lambar waya",
  fc_missing_title: "Ba a samu wannan wuri ba",
  fc_missing_d: "Wannan wuri ba ya cikin jerin yanzu. Duba sauran wuraren dake kusa da ku.",
  fc_request_sent: "An aika buƙatar ziyara",
  fc_report_title: "Rahoto game da wannan wuri",
  fc_report_reason: "Mene ne matsalar wannan jerin?",
  fc_book_appointment: "Yi booking na alƙawari",
  fc_whatsapp_d: "Yi tambaya a WhatsApp",
  fc_request_d: "Aika buƙata kuma wurin zai tuntube ku don tsara ziyara.",
  fc_no_date: "Babu ranar da aka fi so",
  hd_steady: "Babu canji",
  hd_reminder_on: "An kunna tunatarwa",
  hd_reminder_off: "An kashe tunatarwa",
  hd_eyebrow: "Lafiyar ku a taƙaitacce",
  hd_title: "Lafiyar ku",
  hd_guest_title: "Shiga don adana bayanin lafiyarku",
  hd_guest_body: "Idan kun shiga, littafin lafiyarku, bayananku da abubuwan tunatarwar ku za su kasance a kowane na'ura.",
  hd_guest_cta: "Shiga ko ƙirƙiri asusu",
  hd_vitals: "Alamun muhimmanci",
  hd_vitals_sub: "Sabbin abubuwan da kuka rubuta",
  hd_log: "Rubuta",
  hd_wellness: "Walwala",
  hd_wellness_sub: "Kwanaki 7 da suka gabata",
  hd_open: "Bude",
  hd_activity: "Ayyukan mako",
  hd_min: "mintuna",
  hd_weight_goal: "Burin nauyi",
  hd_no_weighin: "Ba a rubuta nauyi ba tukuna",
  hd_unit_kg: "kg",
  hd_steps: "Matakai",
  hd_daily_avg: "Matsakaici na yau da kullum",
  hd_steps_sub: "Na baya-bayan nan",
  hd_meds: "Magunguna",
  hd_all: "Duk",
  hd_next_dose: "Kashi na gaba",
  hd_paused: "An dakatar",
  hd_toggle_med: "Kunna/kashe tunatarwar magani",
  hd_active: "yana aiki",
  hd_manage: "Sarrafa",
  hd_no_meds: "Babu tunatarwar magani",
  hd_no_meds_d: "Ƙara ɗaya domin kada ku manta kashi",
  hd_add: "Ƙara",
  hd_records: "Sakamakon gwaji da bayanai",
  hd_view_all: "Duba duka",
  hd_no_records: "Babu bayanai tukuna",
  hd_add_record: "Ƙara bayani",
  hd_passport: "Fasfo na lafiya",
  hd_passport_d: "Katin gaggawar ku da taƙaitaccen bayanin lafiyarku",
  hd_vaccines: "Rigakafi",
  hd_no_vaccines: "Ba a rubuta rigakafi ba",
  hd_no_vaccines_d: "Ƙara rigakafi domin adana tarihin allurar rigakafin ku a wuri ɗaya.",
  hd_journey: "Tafiyar lafiya",
  hd_journey_sub: "Abubuwan da kuka rubuta kwanan nan",
  hd_no_symptoms: "Ba a rubuta alamomi ba",
  hd_no_journal: "Ba a rubuta komai ba tukuna",
  hd_chronic: "Cututtuka da suka daɗe",
  hd_chronic_d: "Hawan jini, ciwon suga da shanƙafa",
  hd_support: "Ƙungiyar kulawa da goyon baya",
  prof_saved: "An ajiye bayanan asusu",
  prof_emergency_saved: "An ajiye mai tuntuɓar gaggawa",
  prof_sub: "Bayanan ku, zaɓuɓɓukan ku da sirrin ku a wuri ɗaya.",
  prof_signed_out_title: "Ba ku shiga ba tukuna",
  prof_signed_out_d: "Shiga domin adana alƙawura da bayananku tare, ko ci gaba a matsayin baƙo.",
  gate_continue_guest: "Ci gaba a matsayin baƙo",
  prof_photo_failed: "Ba mu iya amfani da wannan hoto. Gwada wani.",
  prof_photo_no_room: "Wannan na'urar tana cike sauran make. Ka share ko yafi hoton.",
  prof_photo_remove: "Janye hoto",
  prof_photo_removed: "An janye hoto",
  prof_photo_saved: "An sabunta hoto",
  prof_photo_too_large: "Wannan hoto yana da girma. Za ka iya zaɓi karamin hoto.",
  prof_change_photo: "Canza hoto",
  prof_no_phone: "Ba a ƙara lambar waya ba",
  prof_edit: "Gyara bayanan asusu",
  prof_account_sync: "Asusu da daidaitawa",
  prof_emergency: "Mai tuntuɓar gaggawa",
  prof_no_emergency: "Ba a ƙara mai tuntuɓar gaggawa ba tukuna",
  prof_no_emergency_d: "Ƙara wanda za a iya kira a lokacin gaggawa",
  prof_call: "Kira",
  prof_view_all: "Duba duka",
  prof_bookings_1: "Akwai buƙatar booking 1",
  prof_bookings_n: "buƙatun booking",
  prof_bookings_d: "Bi diddigin matsayin kowane ziyara da kuka nema.",
  auth_phone_label: "Waya (ba tilas ba)",
  auth_phone_hint: "Masu bayarwa zasu iya amfani da shi don tabbatar da ziyara",
  prof_phone_ph: "+234 ...",
  prof_email_fixed: "Ba za a iya canza imel a nan ba",
  prof_emergency_ph: "misali. Tayo Ogunleye (ɗan'uwa)",
  prof_emergency_note: "Wannan lambar ce za a nuna a katin gaggawar Fasfo na Lafiya.",
  auth_err_email_required: "Shigar da adireshin imel ɗinku.",
  auth_err_email_invalid: "Wannan adireshin imel ba daidai ba ne.",
  auth_reset_offline: "Sake saita kalmar sirri yana buƙatar asusun CareNBuddi na cloud. A yanayin demo ba a duba kalmar sirri ba.",
  auth_reset_unconfigured: "Ba a saita aiko imel ba tukuna. Yi amfani da 'Asusu da daidaitawa' don kammala saita asusun ku.",
  auth_reset_sent: "An aika hanyar haɗi don sake saita kalmar sirri",
  auth_reset_failed: "Ba za mu iya aika imel ɗin ba. Sake gwadawa nan da nan.",
  auth_reset_title: "Sake saita kalmar sirri",
  auth_reset_sub: "Shigar da imel ɗin da ke kan asusun ku, za mu aika muku hanyar haɗi don zaɓar sabon kalmar sirri.",
  auth_reset_sent_d: "Idan wannan adireshin yana da asusu, hanyar haɗin na kan hanyarsa.",
  auth_resend_in: "Ana aika...",
  auth_reset_cta: "Aika hanyar haɗi",
  auth_reset_cta_resend: "Sake aika hanyar haɗi",
  auth_back_signin: "Komawa zuwa shiga",
  auth_back: "Komawa zuwa CareNBuddi",
  auth_home: "Gidan CareNBuddi",
  brand_name: "CareNBuddi",
  auth_err_password_required: "Shigar da kalmar sirri.",
  auth_err_password_short: "Kalmar sirri dole ya zama aƙalla haruffa 8.",
  auth_signin_no_account: "Babu asusun da ke amfani da wannan imel a wannan na'ura. Ƙirƙiri asusu da farko.",
  auth_signed_in: "Kun shiga",
  auth_signin_title: "Barka da dawowa",
  auth_signin_sub: "Shiga don ganin alƙawura, bayananku da fasfo na lafiya a wannan na'ura.",
  auth_password_ph: "••••••••",
  auth_password_hint: "Aƙalla haruffa 8",
  auth_forgot: "Manta kalmar sirri?",
  auth_no_account: "Sabon zuwa CareNBuddi?",
  auth_demo_link: "Kuna kawai bincike?",
  auth_err_name_required: "Shigar da cikakken sunan ku.",
  auth_err_phone_invalid: "Shigar da lambar waya mai inganci, misali +234 800 000 0000.",
  auth_err_confirm_mismatch: "Kalmar sirrin biyu ba su dace ba.",
  auth_check_email: "Duba imel ɗinku don tabbatar da asusun ku",
  auth_account_created: "An ƙirƙiri asusu",
  auth_signup_failed: "Ba za mu iya ƙirƙirar wannan asusu ba.",
  auth_signup_title: "Ƙirƙiri asusun ku",
  auth_signup_sub: "Asusu guda ɗaya ke adana alƙawura da bayanan lafiyar ku tare. Ba tilas ba ne — kuna iya bincike a matsayin baƙo.",
  auth_role_patient: "Mai jinya",
  auth_confirm_label: "Tabbatar da kalmar sirri",
  auth_creating: "Ana ƙirƙiri...",
  auth_have_account: "Kuna da asusu?",
  auth_verify_no_email: "Ba mu san adireshin imel da za a tabbatar ba tukuna.",
  auth_confirmed: "An tabbatar da imel",
  auth_verify_short: "Shigar da lambar 6 da ke cikin imel ɗinku.",
  auth_verify_failed: "Wannan lambar ba ta aiki ba.",
  auth_resent_demo: "A yanayin demo ba a aika lamba ta gaske ba.",
  auth_resent: "An sake aika sabon lamba. Duba akwatin imel ɗinku.",
  auth_resend_failed: "Ba za mu iya sake aika lambar ba.",
  auth_verify_title: "Tabbatar da imel ɗinku",
  auth_verify_sub: "Mun aika hanyar haɗi da lambar 6 zuwa imel ɗinku. Buɗe hanyar haɗin, ko shigar da lambar a ƙasa.",
  auth_verify_sub_off: "A yanayin demo ba a aika imel ta gaske ba. Ci gaba idan kun shirya.",
  auth_email_label: "Adireshin imel",
  auth_code_label: "Lambar tabbatarwa",
  auth_resend: "Sake aika lamba",
  auth_verify_hint: "Kun riga kun tabbatar? Shiga da imel ɗinku da kalmar sirri.",
  auth_verify_continue: "Ci gaba zuwa CareNBuddi",
  gate_signin_title: "Shiga don ci gaba",
  gate_signin_body: "Wannan sashin app ɗin yana adana bayanan lafiyar ku na sirri. Shiga don ganin bayananku.",
  gate_signin_cta: "Shiga",
  gate_staff_title: "Ma'aikata kawai",
  gate_staff_body: "Wannan yanki na masu bayarwa da ma'aikatan CareNBuddi ne.",
  gate_back_profile: "Komawa zuwa bayanan asusu",
  appt_cancelled_note: "An soke wannan alƙawari.",
  appt_book_again: "Sake booking",
  appt_cancel: "Soke",
  booking_done: "An yi booking na alƙawari",
  fc_book_title: "Yi booking na alƙawari",
  fc_confirm_booking: "Tabbatar da booking",
  fc_visit_type: "Irin ziyara",
  fc_pick_date: "Zaɓi rana",
  fc_pick_time: "Zaɓi lokaci",
  fc_notes: "Bayani (ba tilas ba)",
  fc_notes_ph: "Wani abu da mai bayarwa zai bukata kafin ziyara...",
  fc_book_note: "Kuna iya sake tsara ko soke daga shafin Alƙawura.",
  onb_skip: "Tsallake",
  onb_step_word: "Mataki",
  onb_step_1: "Mataki 1 na 3",
  onb_step_2: "Mataki 2 na 3",
  onb_step_3: "Mataki 3 na 3",
  onb_back: "Komawa baya",
  onb_start: "Fara",
  onb_next: "Na gaba",
  prof_signed_out: "Kun fita daga asusu",
  prof_health_prefs: "Zaɓuɓɓukan lafiya",
  prof_units: "Ma'aunai",
  prof_units_d: "Yadda ake nuna nauyi, tsayi da zafin jiki",
  prof_units_metric: "Metric (kg)",
  prof_units_imperial: "Imperial (lb)",
  prof_hmo_empty: "Ba a ƙara ba tukuna — a cikin Fasfo na Lafiya",
  prof_notifications: "Sanarwa",
  prof_notif_appt: "Tunatarwar alƙawura",
  prof_notif_appt_d: "Tunatarwa kafin kowane alƙawari",
  prof_notif_meds: "Tunatarwar magunguna",
  prof_notif_meds_d: "Za a aiko da tunatarwa idan kun kunna su",
  prof_notif_tips: "Nasihu kan lafiya",
  prof_notif_tips_d: "Wasu shawarwari kan rigakafi da gwaje-gwaje lokaci-lokaci",
  prof_privacy: "Sirri da tsaro",
  prof_account_sync_d: "Adana bayananku kuma sarrafa asusun cloud",
  prof_privacy_notice: "Sanarwa kan sirri",
  prof_privacy_notice_d: "Abin da ke kan wannan na'ura da abin da ake daidaita",
  prof_change_password: "Canza kalmar sirri",
  prof_change_password_d: "Za mu aika muku hanyar haɗi mai tsaro ta imel",
  prof_help: "Taimako da goyon baya",
  prof_contact_support: "Tuntuɓi goyon baya",
  prof_support_email: "support@healthlink.ng",
  prof_find_d: "Nemi masu bayarwa da asibitoci kusa da ku",
  prof_signout_d: "Bayanan ku za su kasance kan wannan na'ura",
  prof_privacy_local_title: "Ana adana shi kan wannan na'ura",
  prof_privacy_local_d: "A asali, duk abin da kuka rubuta — alƙawura, littafin lafiya, bayanai, fasfo, zaɓuɓɓuka da hoton bayananka — ana adana su ne kawai a wannan waya.",
  prof_privacy_cloud_title: "Daidaitawa na cloud ne kawai idan kuna da asusu",
  prof_privacy_cloud_d: "Idan kun haɗa asusun CareNBuddi na cloud, ana ɓoye bayananku yayin tura su kuma ana daidaita su domin ku iya amfani da app a wata na'ura. Yi amfani da 'Asusu da daidaitawa' don haɗawa ko cirewa.",
  prof_privacy_share_title: "Abin da masu bayarwa ke gani",
  prof_privacy_share_d: "Mai bayarwa zai ga sunan ku da lambar waya da kuka bayar kawai lokacin neman ziyara, da kuma abin da kuka zaɓa don nuna daga Fasfo na Lafiya.",
  prof_signout_title: "Fita daga CareNBuddi?",
  prof_signout_body: "Bayanan da kuka adana za su kasance kan wannan na'ura. Kuna iya shiga kuma a kowane lokaci.",
  fc_slots_call: "Kira don ganin lokutan da suke akwai",
  fc_next_slot: "Wurin da ke akwai gaba",
  fc_book: "Yi booking",
  fc_details: "Cikakkun bayanai",
  appt_empty_upcoming: "Babu alƙawura dake zuwa",
  appt_empty_upcoming_d: "Yi booking na ziyara tare da mai bayarwa da aka tabbatar cikin dannawa kaɗan.",
  appt_empty_completed: "Babu ziyarar da ta wuce tukuna",
  appt_empty_completed_d: "Alƙawura za su koma nan idan ranar ziyara ta wuce.",
  appt_empty_cancelled: "Babu abin da aka soke",
  appt_empty_cancelled_d: "Ziyara da kuka soke za a jera su nan, tare da sauran tarihin ku.",
  hx_sub: "Motsa jiki sosai don jin daɗi",
  n_appts: "Alƙawura",
  n_care: "Nemi kula",
  n_my_health: "Lafiyata",
  n_staff: "Kayan aiki na ma'aikata",
  n_more: "Ƙari",
  n_notifications: "Sanarwa",
  n_main_nav: "Babban tafiya",
  ad_v_approved_toast: "An tabbatar da cihi",
  ad_v_none_d: "Nemi yin da aka yi rajista za a nuna a nan don duba.",
  ad_r_empty: "Babu kararamin",
  ad_r_empty_d: "Kararamin al'umma za a nuna a nan don duba.",
  askx_greeting: "Sannu! Ina ne Ask CareNBuddi. Na iya taimaka mu ka fahimta batun lafiya da kuma amfani da app — ba na likita ba ne. Me ka son sani?",
  askx_disclaimer: "Kayan ilimi kawai — ba maye canza gurbin harkar likita ba ne.",
  askx_emergency_hint: "Gaggaba? Kira 112 daga \"Ka Taimako Yanzu\".",
  emx_national: "Gaggaban kasa: 112",
  chx_title: "Mai Hasken Lafiya",
  chx_sub: "Tsarin yero da kowane rana da fahimta a cikin wata.",
  chx_today: "Yau",
  chx_month: "Wannan wata",
  chx_bp_logged: "An rubuta karatamin BP",
  chx_entries_logged: "shafi da aka rubuta",
  chx_latest: "Sabo",
  chx_care: "Kula",
  chx_find: "Nemo cibi da ke kusa",
  chx_reminder_set: "An saita garga don wannan tsarin",
  chx_remind: "Ka tuna da ni",
  exx_warn: "Don shigar da tsawara, nauyin farawa da nauyin makoman a cikin cm / kg.",
  exx_goal_saved: "An ajiye makoman",
  exx_weight_saved: "An rubuta nauyi",
  exx_workout_logged: "An rubuta horar kanka",
  h_dashboard: "Lafiyata Ta",
  ex_not_yet: "Ba a yi yi a yau",
  ex_current: "Nauyin yanzu",
  ex_week: "Aiki a cikin makon",
  ex_today: "yau",
  ex_bmi: "BMI",
  ex_goal: "Makoman",
  ex_set_goal: "Saita makoman ka",
  ex_journey: "Tafiyar nauyi",
  exx_no_weighins: "Babu nauyin da aka rubuta sosai.",
  exx_ph_weight: "Nauyin yau (kg)",
  ex_record: "Rubuta",
  ex_reminder: "Garga na horar kanka kowane rana",
  ex_active: "Aiki",
  ex_at: "an saita don",
  ex_off: "An kammanta garga.",
  ex_time: "Lokacin garga",
  ex_reminder_note: "Garga na gariya na taimaka da kanka ka kiyaye tsarin yero. An shafi saƙo harka don MVP na dijitaal.",
  ex_library: "Kyakkyawa horar kanka",
  ex_how: "Yadda ake yi",
  ex_save: "Ajiye makoman",
  ex_from: "daga",
  ex_to: "zuwa",
  exx_f_height: "Tsawara (cm)",
  exx_f_start: "Nauyin farawa (kg)",
  exx_f_goal: "Nauyin makoman (kg)",
  ex_add: "Rubuta horar kanka",
  exx_f_exercise: "Horar kanka",
  exx_f_minutes: "Mintuna",
  exx_f_note: "Bayanai (na zaɗi)",
  exx_ph_note: "misali: karo na safiya",
  ex_today_logged: "An rubuta yau",
  exx_none_today: "Babu horar kanka da aka rubuta yau. Za ka zaɗi wani daga kasa ko ko daga kyakkyawa.",
  exx_nice: "Kyau a yau",
  exx_nice_d: "Koma kuma sai an ci gaba da yawa don ka ci gaba da kanka.",
  jyx_journal: "Shafin lafiya",
  jyx_mood: "Hatsarin zuciya",
  jyx_request: "Nemi lafiya",
  jyx_screening: "Binciken al'umma",
  jyx_screening_d: "Sanar da \"Sanin lambinka da kanka\"",
  jyx_referred: "An tura zuwa asibiti tsawon karkashi",
  jyx_referred_d: "An lamar da karatmin BP yayin bincike",
  jyx_empty: "Layinka babu komai",
  jyx_empty_d: "Rubutanni shafi, kayanda da nemi lafiya za a nuna a nan idan ka sanya su.",
  jyx_legend_records: "Kaidanni",
  jyx_legend_care: "Lafiya",
  jyx_legend_requests: "Nemi",
  hdx_created: "An ƙirƙira ran lafiya",
  hdx_screened: "An bincike",
  hdx_referred: "An tura",
  hdx_followup_due: "Bincike na gaba yana buƙatar farawa",
  hdx_followed: "An biyo gaba",
  hdx_empty: "Babu ran lafiya yanzu",
  hdx_empty_d: "Ƙirƙiri wata don ka sami binciken da tuma.",
  jr_saved: "An ajiye shafi",
  jr_deleted: "An sanye shafi",
  jr_title_page: "Shafin lafiya",
  jr_sub_page: "Rubuta hatsarin zuciya, alamomin ciwon da kowane rana.",
  jr_add_entry: "Ƙara shafi",
  jr_empty_title: "Babu shafi da aka rubuta",
  jr_empty_body: "Fara sa ido da lafiyarka da kanka ƙara shafi na farko a yau.",
  jr_edit: "Gyara",
  jr_delete: "Sanye",
  jr_edit_entry: "Gyara shafi",
  jr_form_new: "Sabin shafi",
  jr_save: "Ajiye shafi",
  jr_date: "Ran",
  jr_mood: "Hatsarin zuciya",
  jr_symptoms: "Alamomin ciwon",
  jr_vitals_weight: "Nauyi (kg)",
  jr_vitals_heart: "Ƙarfin zuciya (bpm)",
  jr_vitals_sleep: "Barci (awanni)",
  jr_vitals_steps: "Tawa",
  jr_vitals_bp_sys: "BP na sama",
  jr_vitals_bp_dia: "BP na kasa",
  jr_notes: "Bayanai",
  jr_note_ph: "Yadda yinka ka yi?",
  jr_delete_confirm_title: "Sanye shafin shafi?",
  jr_delete_confirm_body: "Za a sanye wannan shafi har ya shiga cikin maimaitawa.",
  jr_confirm_delete: "Eh, sanye",
  jr_cancel: "Soke",
  pvx_staff_only: "Shiga kawai ga masu ba da",
  pv_pending_d: "Mu team na duba kowane rajista kafin a buɗe babban shafi.",
  pvx_no_requests: "Nemi marasa da aka yi da cihi za a nuna a nan.",
  pvx_register_d: "Sabunta ko ko ƙara wata",
  pvx_ph_name: "misali: Dr. Ngozi Eze",
  pvx_ph_lga: "misali: Abeokuta South",
  rc2_saved: "An ajiye kayan aiki",
  rc2_removed: "An sanye kayan aiki",
  rc2_title: "Kayan aikin likita",
  rc2_sub: "Ka adana ziyare da za a iya kunna ta na ziyare, gwaji da wasafi.",
  rc2_add: "Ƙara kayan aiki",
  rc2_filter_all: "Duka",
  rc2_empty_title: "Babu kayan aiki a nan yanzu",
  rc2_empty_body: "Ƙara ziyare, sakamako ko ko alloga don ka rike shi tare da kanka.",
  rc2_delete: "Sanye kayan aiki",
  rc2_open: "Buɗe kayan aikin da aka haɗa",
  rc2_add_title: "Ƙara kayan aiki",
  rc2_save: "Ajiye kayan aiki",
  rc2_f_title: "Taken",
  rc2_f_ph_title: "misali: sakamako jini",
  rc2_f_provider: "Mai ba da / cibi",
  rc2_f_ph_provider: "misali: Dr. Smith, Asibitin Birane",
  rc2_f_date: "Ran",
  rc2_f_category: "Rukuni",
  rc2_f_summary: "Taƙaƙari / nasara",
  rc2_f_summary_ph: "Babban ganawa ko bayanai…",
  rc2_f_link: "Hanyali (na zaɗi)",
  rc2_confirm_title: "Sanye wannan kayan aiki?",
  rc2_confirm_body: "Ba za a iya mayar da shi ba.",
  rc2_confirm_yes: "Eh, sanye",
  rc2_confirm_no: "Ri shi",
  rm2_saved: "An ƙara garga",
  rm2_removed: "An sanye garga",
  rm2_on: "Aiki",
  rm2_off: "Kammawa",
  rm2_delete: "Sanye garga",
  rm2_title: "Garguna",
  rm2_sub: "Owa magani, ruwan sha, aiki da ziyare.",
  rm2_add: "Ƙara garga",
  rm2_today: "Yau",
  rm2_empty_today: "Babu wani da aka tsara a yau",
  rm2_empty_today_d: "Garganka na yau za a nuna a nan.",
  rm2_all: "Duk garguna",
  rm2_empty_all: "Babu garga sosai",
  rm2_empty_all_d: "Ƙara gargar da farko don ka ka manta karashin ko wani ziyare.",
  rm2_sheet_title: "Sabin garga",
  rm2_save: "Ƙara garga",
  rm2_f_title: "Taken",
  rm2_ph_title: "misali: magani na yamma",
  rm2_f_time: "Lokaci",
  rm2_f_type: "Iri",
  rm2_f_days: "Maimaita a kan",
  rm2_f_notes: "Bayanai",
  rm2_ph_notes: "Bayanai na zaɗi…",
  rm2_confirm_title: "Sanye wannan garga?",
  rm2_confirm_body: "Ba za a iya maye da ba a.",
  rm2_confirm_yes: "Eh, sanye",
  rm2_confirm_no: "Ri shi",
  wkr_saved: "An rubuta binciken",
  wkr_online: "Na kan layin — an haɗa",
  wkr_offline: "Babu layin — canza sun jiran",
  wkr_empty: "Babu bincike da aka rubuta",
  wkr_empty_d: "Rubuta bincike bayan wata don ka ba a manta bincike na gaba.",
  wkr_f_date: "Ran",
  wkr_f_type: "Iri",
  wkr_f_participants: "Masu sha'",
  wkr_f_referred: "An tura",
  wkr_f_notes: "Bayanai",
  jr_mood_great: "Mai kyau",
  jr_mood_good: "Mai kyau",
  jr_mood_okay: "Al'ada",
  jr_mood_low: "Kamar",
  jr_mood_poor: "Mummuna",
  jr_mood_unknown: "Hatsarin zuciya",
  jr_symptom_headache: "Zazzabin kai",
  jr_symptom_nausea: "Kai",
  jr_symptom_fatigue: "Karuwa",
  jr_symptom_cough: "Dari",
  jr_symptom_fever: "Zazzabi",
  jr_symptom_dizziness: "Ruwan kai",
  jr_symptom_sore_throat: "Horo",
  jr_symptom_stomach: "Cibi",
  jr_symptom_back: "Bayasa",
  jr_symptom_allergy: "Sensitivities",
  jr_symptom_other: "Wani",
  rc2_cat_visit: "Ziyare",
  rc2_cat_lab: "Sakamako",
  rc2_cat_imaging: "Hoto",
  rc2_cat_prescription: "Wasafi",
  rc2_cat_vaccination: "Alloga",
  a_enter_email: "Shigar da adireshin imail a farko.",
  cc2_added: "An sabunta mada'irar kulawa",
  cc2_removed: "An cire",
  cc2_empty: "Ba a yi ƙara wani ba a",
  cc2_empty_d: "Ƙara mutane da kake kula da su don ka ka kiyaye mahimman lafiyarsu.",
  pp_saved: "An sabunta pasapoti",
  pp_none: "Ba a saita",
  s_on: "a ran",
  s_ph_name: "misali: Amina Yusuf",
  s_ph_area: "misali: Ikeja, Lagos",
};
