import type { Dict } from "../i18n";

export const haDict: Dict = {
    n_home: "Gida", n_explore: "Binciko", n_find: "Nemi Kula", n_services: "Ayyuka",
    n_health: "Lafiya", n_profile: "Bayanan", n_provider: "Mai bayarwa", n_admin: "Gudanarwa", n_account: "Asusu",
    h_title: "Ta yaya zamu taimaka muku a yau?",
    h_sub: "Koyi game da lafiyar ku, duba lambobin ku, nemi kulawa mai kyau, ku saka ido ga masu bayar da kulawa.",
    h_learn: "Koyi game da lafiya", h_learn_d: "Labarai masu sauki kan cututtuka da rigakafi.",
    h_check: "Duba lafiyar ku", h_check_d: "Gwaji, asibitoci, da shafi na lafiyar ku.",
    h_find: "Nemi kula a kusa", h_find_d: "Asibitoci, PHC, dakunan gwaji, kantin magani da kwararru a jihar ku.",
    h_connect: "Saka ido ga mai kula", h_connect_d: "Tuntuɓi masu bayar da kulawa kai tsaye don yin booking.",
    h_search: "Bincika batutuwan lafiya, cututtuka, ko ayyuka…",
    h_emergency: "Nemi taimako yanzu", h_emergency_d: "Lambobin gaggawa da matakan agaji.",
    h_browse: "Duba duk batutuwan lafiya", h_readmore: "Kara karatu",
    e_title: "Bincika ilimin lafiya", e_sub: "Zaɓi rukuni ko karanta wani batu a ƙasa.",
    e_allcat: "Duk rukunoni", e_topics: "Batutuwa", e_draft: "Daftari", e_publish: "Buga", e_report: "Rahoto",
    f_title: "Nemi Kula", f_sub: "Nemi asibitoci, PHC, dakunan gwaji, kantin magani da kwararru — ku tuntuɓi su kai tsaye.",
    f_search: "Nemi da suna, aiki, ko LGA…", f_all: "Duk rukuni", f_verified: "An tabbatar", f_call: "Kira",
    f_whatsapp: "WhatsApp", f_dir: "Hanyar", f_request: "Nemi ziyara", f_reportP: "Rahoton mai bayarwa",
    f_open_24: "Yana buɗe 24 awa", f_no_results: "Babu mai bayarwa da ya dace da bincikenku.", f_services: "Ayyuka",
    f_hours: "Lokaci", f_desc: "Game da wannan wurin",
    s_title: "Ayyuka", s_sub: "Duba lafiyar ku kuma ku yi booking na ayyukan rigakafi.",
    s_book: "Yi booking na aiki ko ziyara", s_received: "An karɓi buƙatar",
    em_title: "Nemi Taimako Yanzu", em_sub: "Jagorancin gaggawa da inda za a kira.",
    hh_title: "Lafiya Ta", hh_sub: "Gurin ku — motsa jiki, rikodi, ci gaba.",
    hh_exercise: "Motsa jiki & nauyi", hh_exercise_d: "Yi motsa jiki kullum, sa masu tunani, bin diddigin nauyi.",
    hh_journal: "Littafin lafiya", hh_journal_d: "Halin, alamomi da lafiya ta yau da kullum.",
    hh_records: "Bayanan lafiya", hh_records_d: "Ziyara, sakamakon dakin gwaji da takardu.",
    hh_reminders: "Abubuwan tunatarwa", hh_reminders_d: "Magani, motsa jiki, alƙawura.",
    a_title: "Asusu", a_sub: "Ƙirƙiri asusu na son rai ko ci gaba kamar baƙo.",
    a_name: "Cikakken suna", a_email: "Imel", a_phone: "Waya", a_role: "Ni ne",
    a_consumer: "Mara lafiya / al'umma", a_provider: "Mai bayar da lafiya", a_admin: "Ƙungiyar HealthLink",
    a_signup: "Ƙirƙiri asusu", a_signin: "Shiga", a_signout: "Fita",
    a_send_code: "Aiko mini lambar sirri", a_verify: "Tabbatar", a_code: "Lambar 6",
    a_language: "Harshe", a_language_d: "Canza harshen dashboard da abun cikin lafiya.",
    a_demo: "Shiga demo", a_demo_admin: "Buɗe demo gudanarwa", a_demo_provider: "Buɗe demo mai bayarwa", a_demo_consumer: "Buɗe demo mara lafiya",
    a_welcome: "An shigar da kai", c_back: "Baya", c_save: "Ajiye", c_cancel: "Soke",
    c_remove: "Cire", c_send: "Aika", c_new: "Sabo", c_status: "Matsayi", c_pending: "Jiran",
    c_approved: "An amince", c_rejected: "An ƙi", c_resolved: "An warware", c_none: "Babu",
    c_manage: "Sarrafa", c_reason: "Dalili",
    pv_title: "Mashaya mai bayarwa", pv_sub: "Sarrafa bayanan wurin ku da buƙatun kulawa.",
    pv_register: "Yi rajistar wurin ku", pv_requests: "Buƙatun tuntuɓa / booking", pv_profile: "Bayanan wuri na",
    pv_services: "Ayyuka", pv_save: "Ajiye bayanan", pv_pending: "Ana duba rajistar ku.",
    pv_none: "Babu wuri da aka tabbatar a wannan asusu.",
    pv_new_req: "Sabbin buƙatun", pv_confirm: "Alama aka tuntuɓa",
    ad_title: "Mashaya gudanarwa", ad_sub: "Abubuwa, tabbatarwa, masu amfani, kididdiga da tsaro.",
    ad_overview: "Kallo", ad_content: "Abun ciki", ad_verification: "Tabbatarwa",
    ad_users: "Masu amfani", ad_analytics: "Kididdiga", ad_reports: "Rahotanni",
    ft_nav: "HealthLink — Tsarin Kewayon Lafiyar Ku na Kai Tsaye.",
    ft_desc: "Muna haɗa ilimin lafiya da mataki mai kyau — duba lambobin ku, nemi kulawa da aka tabbatar, yi booking na ayyuka, ku bi diddigin — ga daidaikun mutane, iyalai da al'ummomi a Najeriya.",
    ft_notdx: "HealthLink yana ba da bayanin lafiya na gabaɗaya da kewayawa. Ba binciken likita ba ne kuma baya maye gurbin ƙwararren lafiya.",
    ft_emergency: "A gaggawa, koyaushe kira lambar gaggawa ta gida da farko — kafin amfani da wannan dandali.",
    ft_lang: "Akwai cikin Turanci, Yarbanci, Hausa da Igbo.",
    ft_report: "Nemi bayani da ba daidai ba ko ya tsufa",
  n_chronic: "Kulawar cututtukan da suka daɗe", n_chronic_d: "Jagorori don cututtuka kamar hawan jini.",
  n_journey: "Tafiyar lafiya", n_journey_d: "Bayanan ku da ziyarta cikin layin lokaci guda.",
  n_carecircle: "Da'irar Kulawa", n_carecircle_d: "Lafiyar iyali a gani daya.",
  n_healthdays: "Kwanakin Lafiya", n_healthdays_d: "Gwaje-gwajen al'umma da bibiyarwa.",
  n_worker: "Yanayin ma'aikaci", n_worker_d: "Kayan aiki na masu aikin lafiya na al'umma.",
  n_ask_d: "Jagor neman yanayi, kulawa da dandali.",
  cc_title: "Abokin Kulawar Cututtuka", cc_sub: "Tsarin yau da kullum da nazarin wata don cututtuka da suka daɗe.",
  cc_today: "Yau", cc_month: "Wannan wata", cc_latest: "Na baya-bayan nan", cc_care: "Kulawa", cc_find: "Nemo wurin kulawa kusa →",
  cc_hypertension: "Tafiya Hauwan Jini", cc_diabetes: "Tafiya na Ciwon Sugar",
  cc_sicklecell: "Tafiya na Ciwon Kwayar Jini", cc_asthma: "Tafiya na Shaqa",
  cc2_title: "Da'irar Kulawa", cc2_sub: "Bibiyar lafiyar wadanda kuke kula da su.",
  cc2_remove: "Cire", cc2_bp: "BP", cc2_med: "Magani", cc2_appt: "Alƙawari", cc2_screen: "Bincike na gaba",
  cc2_add: "Ƙara memba na iyali", cc2_name: "Suna / lakabi", cc2_rel: "Dangantaka", cc2_save: "Ajiye", cc2_cancel: "Soke", cc2_addb: "Ƙara memba",
  hd2_title: "Kwanakin Lafiyar Al'umma", hd2_sub: "Gwaje-gwaje da ilimi inda mutane ke taruwa.",
  hd2_create: "Ƙirƙiri rana lafiya", hd2_f_title: "Suna", hd2_f_org: "Mai shiryawa (coci, makaranta…)",
  hd2_f_date: "Kwanan wata", hd2_f_loc: "Wuri", hd2_f_srv: "Ayyuka", hd2_save: "Ƙirƙirar", hd2_cancel: "Soke", hd2_createb: "Ƙirƙiri rana lafiya",
  jt_title: "Tafiyar Lafiyar Ku", jt_sub: "Duk abin da ya faru, cikin layi guda.",
  pp_title: "Fasfo na Lafiya", pp_sub: "Bayani ɗaya. Tarihin lafiya ɗaya. A kowane wuri.",
  pp_details: "Cikakkun bayanai", pp_edit: "Gyara", pp_save: "Ajiye", pp_cancel: "Soke",
  pp_name: "Cikakken suna", pp_blood: "Jinin", pp_allergies: "Allergies", pp_meds: "Magungunan da ake bawa",
  pp_conditions: "Cututtuka da suka daɗe", pp_history: "Tarihin magani", pp_imm: "Alurar riga kafi", pp_hmo: "Inshora / HMO",
  pp_ec: "Mai tuntuɓar gaggawa", pp_ecp: "Wayar gaggawa",
  pp_card: "Katin gaggawa", pp_card_d: "Nuna wannan ga ma'aikacin lafiya a gaggawa.", pp_scan: "Duba da manhajar ma'aikatan HealthLink",
  w_title: "Yanayin Ma'aikacin Lafiya", w_sub: "Gwaje-gwaje, turawa da bibiyarwa daga filin aiki.",
  w_events: "Abubuwan", w_participants: "An gwada", w_referred: "An tura", w_pending: "Bibiyarwa ake buƙata",
  w_log: "Rubuta gwaji", w_add: "Ƙara", w_recent: "Rubutun baya-bayan nan", w_sync: "Ana adanawa a na'ura kuma za a aika idan an dawo da intanet.", w_days: "Duba kwanakin lafiya →",
  ask_title: "Tambayi HealthLink", ask_ph: "Tambaya kan yanayi, samun kulawa, farashi…", ask_send: "Aika",
  f_cost: "Farashi", f_any_cost: "Duk farashi", f_low_cost: "₦ Ƙasa", f_mid_cost: "₦₦ Matsakaici", f_high_cost: "₦₦₦ Mai tsada",
  h_tagline: "Kyakkyawan Bayani. Lafiyarku.",
  e_report_reason: "Damuwa da ta dace da daidai bayani ko tsaro",
  f_location: "Wuri",
  f_category: "Rukuni",
  f_all_states: "Dukkan jihohi",
  f_facility_one: "wurin",
  f_facility_many: "wuraren",
  f_book_sent: "An aika buƙatar. Wurin zai tuntube ku.",
  f_form_msg: "Saƙo",
  f_form_date: "Ranar da aka fi so",
  f_emergency: "Ana samun sabis na gaggawa a wannan wurin sa'o'i 24.",
  f_provider_visit: "Ziyarar mai bayarwa",
  s_we_provide: "Ayyukan lafiya da muke bayarwa",
  s_check_head: "Duba Lafiyata",
  s_open_health: "Bude shafata na lafiya",
  s_intro: "Nemi aikin tantancewa, walwala ko asibiti ta wayar hannu don kanka, iyalinka, ma'aikatunka ko al'ummarka. Ba buƙatar biya don neman — wani daga ƙungiya zai tabbatar da bayanai ta waya.",
  s_form_head: "Nemi aiki ko ziyara",
  s_service: "Aiki",
  s_date: "Ranar da aka fi so",
  s_area: "Yanki / al'umma / wurin aiki",
  s_submit: "Nemi aiki",
  s_free_note: "Ba buƙatar biya don neman. Wani daga ƙungiya zai tabbatar da cancantar ku, farashi da bayanai ta waya.",
  s_book_another: "Yi booking na ziyara wani",
  s_on_date: " a ",
  s_success: "Na gode {name}! Wani daga ƙungiyar HealthLink zai tuntube {phone} don tabbatar da ziyarar {service}{date}. Muna tabbatar da kowane booking ta waya da saƙon rubutu.",
  sc_bp: "Hawan jini",
  sc_bp_d: "Dubawa na BP mai sauki tare da shawara mai sauki.",
  sc_glu: "Glucose na jini",
  sc_glu_d: "Gwajin glucose da shawara kan rayuwa mai lafiya.",
  sc_well: "Duba wellness",
  sc_well_d: "Muhimman abubuwa da tantance lafiyar gaba.",
  srv_education: "Ilimin lafiya",
  srv_education_d: "Darussan harshe mai sauki game da rigakafi da halaye masu kyau.",
  srv_outreach: "Walwalar al'umma",
  srv_outreach_d: "Abubuwan gwaji da wayar da kai a unguwarku.",
  srv_corporate: "Lafiyar ma'aikata",
  srv_corporate_d: "Kwanakin lafiya na wurin aiki don kungiyoyi.",
  srv_mobile: "Ziyarar asibitocin tafi-da-gidanka",
  srv_mobile_d: "Gwaji, walwala da ayyukan lafiya inda kuka kasance.",
  srv_referral: "Ayyuka na tura zuwa",
  srv_referral_d: "Taimako na jagorantar zuwa mai bayarwa dake daidai.",
  srv_campaigns: "Kamfen na lafiya",
  srv_campaigns_d: "Kwanakin gwaji na al'umma kamar “San Lambunanka”.",
  em_call: "Kira lambar gaggawa nan take",
  em_call_d: "Idan akwai rashin sani, ciwon kirji, wahalar numfashi, zubar jini mai yawa, cikakkiya, bugun jini ko wani rikici — kada ku jira kuma kada ku dogara da app.",
  em_while: "Yayin da kuke neman taimakon kwararru",
  em_s1: "Kare kanka da mutumin — kar a motsa shi sai idan yana cikin hatsari.",
  em_s2: "Idan bai sani ba amma yana numfashi, sanya shi a matsayin dawo da hankali.",
  em_s3: "Ga kona, zuba ruwan famfo mai sanyi a kansa na akalla mintuna 20 — kar a yi amfani da kankara, man shanu ko man shafa dibero.",
  em_s4: "Ga zubar jini, danna rauni da karfi da tsabtataccen kaya.",
  em_s5: "Ga alamun bugun jini (fuskantar zainuwar, rauni a hannu, magana mai ruɗani), je wurin gaggawa da sauri.",
  em_find_care: "Nemo kulawa dake da sabis na gaggawa",
  em_find_d: "Don kulawa ba mai barazana ba, nemo wurin dake bayar da sabis na gaggawa kusa da ku.",
  em_find_hospital: "Nemo asibiti",
  em_find_clinic: "Nemo asibiti",
  em_footer: "A cikin gaggawa, kira sabis na gaggawa da farko. HealthLink na ilimi da jagora ne kawai.",
  hh_know: "San lambarku",
  hh_open: "Bude",
  hh_know_d: "Fara Kwanacin Lafiya na Al'umma na HealthLink ko yin booking na asibiti ta wayar hannu don duba hawan jinin ku da glucose tare da kulawar kwararru.",
  n_passport: "Fasfo",
  n_ask: "Tambaya",
  a_code_sent: "An aika da imel na demo — duba lambar a ƙasa.",
  a_email_required: "Shigar da imel da farko.",
  a_code_mismatch: "Lambar ba ta dace ba. Duba ka sake gwadawa.",
  a_demo_mode: "Yanayin demo yana nuna lambar maimakon aika imel.",
  a_demo_note: "Wuraren mai bayarwa da admin ana tsarinsu ta hanyar matsayi a cikin hanyoyin shiga.",
  a_email_ph: "kai@misali.com",
  a_member_default: "Memba na HealthLink",
  pv_confirm_done: "Tabbatar",
  pv_guard: "Wannan yanki na masu bayarwa da aka tabbatar ne. Shiga tare da asusun mai bayarwa ko admin don ci gaba.",
  pv_services_label: "Ayyuka (rabu da comma)",
  pv_about: "Game da wannan wurin",
  pv_no_message: "Babu saƙo",
  prg_lead: "Masu bayarwa suna rajista sau ɗaya; ƙungiyar HealthLink na tabbatar da kowane wuri kafin ya bayyana a Nemi Kulawa a matsayin mai bayarwa da aka tabbatar.",
  prg_facility: "Sunan wuri",
  prg_category: "Rukuni",
  prg_state: "Jiha",
  prg_lga: "LGA / yanki",
  prg_address: "Adireshi",
  prg_submit: "Mika don tabbatarwa",
  prg_note: "Tabbatarwa tana kare al'umma: masu bayarwa da aka tabbatar ne kawai ake nuna su da alamar ✓ a Nemi Kulawa.",
  prg_success_1: "An aika {facility} don dubawa.",
  prg_success_2: "Za ku iya sarrafa bukatunku da bayanan ku daga ma'aikacin mai bayarwa da zarar an amince da ku.",
  ad_signin_req: "Wannan yanki na ƙungiyar HealthLink ne. Yi amfani da asusun admin na demo don bincika sarrafa abun ciki, tabbatarwa, masu amfani, kididdiga da rahotanni.",
  ad_providers: "Masu bayarwa",
  ad_verified_p: "Masu bayarwa da aka tabbatar",
  ad_topics: "Batutuwa",
  ad_verify_pending: "Tabbatarwa masu jiran",
  ad_bookings: "Bookings",
  ad_reports_open: "Rahotanni masu bude",
  ad_c_add: "Addara batu (daftari)",
  ad_c_slug: "slug",
  ad_c_title: "Taken",
  ad_c_summary: "Takaitawa",
  ad_c_category: "Rukuni",
  ad_c_add_draft: "Addara daftari",
  ad_c_publish: "Buga",
  ad_c_unpublish: "Cire daga buga",
  ad_c_delete: "Share",
  ad_c_required: "Ana buƙatar slug da taken.",
  ad_c_draft_note: "Daftari — addara takaitawa kafin bugawa.",
  ad_c_empty_summary: "Zaidi.",
  ad_c_exists: "Akwai batu da wannan slug riga.",
  ad_c_created: "An halicci daftari — buga daga jerin dake ƙasa.",
  ad_v_none: "Babu buƙatun rajista.",
  ad_v_verify: "Tabbatar & buga",
  ad_v_reject: "Ƙi",
  ad_v_approved_desc: "HealthLink ne ya tabbatar bayan duba takardun.",
  ad_u_name: "Suna",
  ad_u_email: "Imel",
  ad_u_role: "Matsayi",
  ad_u_joined: "Shugaba",
  ad_a_cat: "Masu bayarwa ta rukuni",
  ad_a_state: "Masu bayarwa ta jiha",
  ad_a_bookings: "Buƙatun booking — kwanakin 14 da suka wuce",
  ad_a_requests: "Buƙatu",
  ad_a_pipeline: "Jerin rajista:",
  ad_a_submitted: "an mika",
  ad_a_approved: "an amince",
  ad_a_pending0: "suna jiran",
  ad_r_none: "Babu rahotanni.",
  ad_r_resolve: "Warware",
  pr_requests: "Buƙatuna",
  pr_no_requests: "Babu buƙatun booking tukuna.",
  pr_get_started: "don fara.",
  pr_provider: "Ziyarar mai bayarwa",
  pr_appt: "Alƙawura",
  pr_appt_d: "Ziyarun dake zuwa da buƙatu za su bayyana a nan.",
  pr_rem: "Abubuwan tunatarwa",
  pr_rem_d: "Ana shirin tunatarwa na magani da gwaji.",
  pr_saved: "Masu bayarwa da aka ajiye",
  pr_saved_d: "Alamar wuraren da kwararru da kuke amince da su.",
  pr_records: "Bayanan lafiya",
  pr_records_d: "Bayanan suna bayyana ne kawai inda doka ta yarda.",
  pr_soon: "Zaidi",
  j_title: "Littafin lafiya",
  j_sub: "Rubuta halinka, alamomi, da muhimman abubuwa a kowace rana.",
  j_new: "Sabataccen shiga",
  j_date: "Kwanan wata",
  j_mood: "Halitta",
  j_symptoms: "Alamomi",
  j_weight: "Nauyi (kg)",
  j_heart: "Bugun zuciya (bpm)",
  j_sleep: "Barci (hrs)",
  j_steps: "Matakai",
  j_bp_sys: "BP na sama",
  j_bp_dia: "BP na ƙasa",
  j_notes: "Bayani",
  j_note_ph: "Yaya ranarka ta kasance?",
  j_save: "Ajiye shiga",
  j_empty: "Babu shigarwar journal tukuna. Addara ta farko.",
  j_collapse: "Nara",
  j_details: "Cikakkun bayanai",
  j_delete: "Share",
  r_title: "Abubuwan tunatarwa",
  r_sub: "Magani, ruwa, aiki, da alƙawura.",
  r_new: "Sabon abun tunatarwa",
  r_title_field: "Taken",
  r_title_ph: "misali. Maganin yamma",
  r_time: "Lokaci",
  r_type: "Iri",
  r_repeat: "Maimaita a",
  r_notes: "Bayani",
  r_notes_ph: "Ƙarin bayani…",
  r_add: "Addara abun tunatarwa",
  r_today: "Yau",
  r_none_today: "Babu abin da aka shirya don yau.",
  r_all: "Duk abubun tunatarwa",
  r_none: "Babu abun tunatarwa tukuna. Addara na farko.",
  r_on: "A kan",
  r_off: "A kashe",
  r_disable: "Kashe",
  r_enable: "Kunnuwa",
  r_delete: "Share",
  rc_title: "Bayanan likit a",
  rc_sub: "Tsaya dasuwar zubar da shawara na ziyara, sakamakon dakin gwaji, da magunguna.",
  rc_add: "Addara bayanai",
  rc_title_field: "Taken",
  rc_title_ph: "misali. Sakamakon gwajin jini",
  rc_provider: "Mai bayarwa / wurin aiki",
  rc_provider_ph: "misali. Dr. Smith, City Clinic",
  rc_date: "Kwanan wata",
  rc_category: "Rukuni",
  rc_summary: "Takaitawa / sakamako",
  rc_summary_ph: "Muhimman bayanai ko bayani…",
  rc_link: "Hanyar haɗi (zaɓi)",
  rc_save: "Ajiye bayanai",
  rc_all: "Duk",
  rc_empty: "Babu bayanai a nan tukuna.",
  rc_delete: "Share",
  rc_open: "Bude bayanan da aka ɗora",
  ex_back: "Komawa Lafiya Ta",
  ex_title: "Jagorancin Motsa Jiki & Nauyi",
  ex_sub: "Saita burinku, rubuta ayyukanku a kowace rana, kuma duba ci gaban ku. Bayananku ya zauna akan wannan na'ura.",
  ex_streak: "{n} kwanakin sauka",
  ex_goal_1: "Burinku",
  ex_loss_goal: "Burin rage nauyi",
  ex_gain_goal: "Burin kara nauyi",
  ex_goalfmt: " — daga {start} kg zuwa {goal} kg (tsayin {h} cm).",
  ex_height: "Tsayi (cm)",
  ex_start_w: "Nauyin farawa (kg)",
  ex_goal_w: "Nauyin buri (kg)",
  ex_save_goal: "Ajiye buri",
  ex_today_w_ph: "Rubuta nauyin yau (kg)",
  ex_record_w: "Rubuta nauyi",
  ex_warn: "Da fatan za a mayar da tsayi, nauyin farawa da nauyin buri a cm / kg.",
  ex_cur_w: "Nauyin yanzu",
  ex_lost: "Ragewa",
  ex_gained: "Karawa",
  ex_to_goal: "zuwa buri",
  ex_progress: "Ci gaban jagorar",
  ex_goal_x: "Buri {g} kg",
  ex_week_active: "Mai aiki wannan mako",
  ex_logged_today: "{n} an rubuta yau",
  ex_weight_journey_2: "Jagorancin nauyi",
  ex_checkins: "{n} dubawa",
  ex_goal_label: "Buri",
  ex_date: "Kwanan wata",
  ex_weight: "Nauyi",
  ex_change: "Canji",
  ex_start: "farawa",
  ex_train_3: "Horar a kowace rana",
  ex_done: "Yi yau",
  ex_not_done: "Ba a yi ba tukuna yau",
  ex_exercise: "Motsa jiki",
  ex_minutes: "Mintuna",
  ex_note_opt: "Bayani (zaɓi)",
  ex_note_ph: "misali. ji daɗi, zangon safe",
  ex_log: "Rubuta motsa jiki",
  ex_remove: "Cire",
  ex_no_today: "Ba a rubuta motsa jiki yau ba. Zaba motsa jiki a sama ko daga ɗakin karatu a ƙasa.",
  ex_reminder_4: "Tunatarwar motsa jiki a kowace rana",
  ex_rem_on: "Mai aiki — an kafa tunatarwa don {time}.",
  ex_rem_off: "Tunatarwa tana kashe.",
  ex_rem_time: "Lokacin tunatarwa",
  ex_rem_note: "Tunatarwa ta yankin tana taimaka muku ci gaba da dabi'a ta kullum. Ana shirya aiko saƙonni don MVP na dijital.",
  ex_library_5: "Dakin karatu na motsa jiki",
  ex_library_d: "Hotuna da bidiyo na motsa jiki iri-iri. Zaba ɗaya kuma rubuta shi a matsayin motsa jiki na yau.",
  ex_hide: "Boye",
  ex_howto: "Yadda ake yi",
  ex_log_today: "Rubuta yau",
  ex_media_1: "Don bada ƙarin hotunanka da kai: zuba hotuna a",
  ex_media_2: "da bidiyo a",
  ex_media_3: "Za su bayyana ta atomatik.",
  hd_when: "Lokacin da ya kamata a nemi taimakon kwararru",
  hd_what: "Menene",
  hd_symptoms: "Alamomi da alamun haɗari",
  hd_risk: "Abubuwan hadari",
  hd_prevention: "Rigakafi",
  hd_faqs: "Tambayoyi akai-akai",
  hd_read_more: "Kara karatu",
  hd_reviewed: "An sake dubawa da",
  hd_report: "Rahoto",
  hd_source: "Tushe:",
  hd_find_help: "Nemo Taimako Kusa Dake",
  sv_emergency: "Gaggawa",
  sv_hospitals: "Asibitoci",
  sv_phc: "Wuraren lafiya na farko",
  sv_labs: "Dakunan gwaji",
  sv_pharmacies: "Kantin magani",
  sv_professionals: "Kwararru",
  count_results: "{n} mai bayarwa",
  lang: "Harshen Hausa",
};
