import type { Dict } from "../i18n";

export const haDict: Dict = {
    n_home: "Gida", n_explore: "Binciko", n_find: "Nemi Kula", n_services: "Ayyuka",
    n_health: "Lafiya", n_profile: "Bayanan", n_provider: "Mai bayarwa", n_admin: "Gudanarwa", n_account: "Asusu",
    h_title: "Ta yaya zamu taimaka muku a yau?",
    h_sub: "Koyi game da lafiyar ku, duba lambobin ku, nemi kulawa mai kyau, ku saka ido ga masu bayar da kulawa.",
    h_learn: "Koyi game da lafiya", h_learn_d: "Labarai masu sauki kan cututtuka da rigakafi.",
    h_check: "Duba lafiyar ku", h_check_d: "Gwaji, asibitoci, da shafi na lafiyar ku.",
    h_find: "Nemi kula a kusa", h_find_d: "Asibitoci, PHC, dakunan gwaji, kantin magani da kwararru a jihar ku.",
    h_connect: "Saka ido ga mai kula", h_connect_d: "Tuntuɓi masu bayar da kulawa kai tsaye don yin booking.",
    h_search: "Bincika batutuwan lafiya, cututtuka, ko ayyuka…",
    h_emergency: "Nemi taimako yanzu", h_emergency_d: "Lambobin gaggawa da matakan agaji.",
    h_browse: "Duba duk batutuwan lafiya", h_readmore: "Kara karatu",
    e_title: "Bincika ilimin lafiya", e_sub: "Zaɓi rukuni ko karanta wani batu a ƙasa.",
    e_allcat: "Duk rukunoni", e_topics: "Batutuwa", e_draft: "Daftari", e_publish: "Buga", e_report: "Rahoto",
    f_title: "Nemi Kula", f_sub: "Nemi asibitoci, PHC, dakunan gwaji, kantin magani da kwararru — ku tuntuɓi su kai tsaye.",
    f_search: "Nemi da suna, aiki, ko LGA…", f_all: "Duk rukuni", f_verified: "An tabbatar", f_call: "Kira",
    f_whatsapp: "WhatsApp", f_dir: "Hanyar", f_request: "Nemi ziyara", f_reportP: "Rahoton mai bayarwa",
    f_open_24: "Yana buɗe 24 awa", f_no_results: "Babu mai bayarwa da ya dace da bincikenku.", f_services: "Ayyuka",
    f_hours: "Lokaci", f_desc: "Game da wannan wurin",
    s_title: "Ayyuka", s_sub: "Duba lafiyar ku kuma ku yi booking na ayyukan rigakafi.",
    s_book: "Yi booking na aiki ko ziyara", s_received: "An karɓi buƙatar",
    em_title: "Nemi Taimako Yanzu", em_sub: "Jagorancin gaggawa da inda za a kira.",
    hh_title: "Lafiya Ta", hh_sub: "Gurin ku — motsa jiki, rikodi, ci gaba.",
    hh_exercise: "Motsa jiki & nauyi", hh_exercise_d: "Yi motsa jiki kullum, sa masu tunani, bin diddigin nauyi.",
    hh_journal: "Littafin lafiya", hh_journal_d: "Halin, alamomi da lafiya ta yau da kullum.",
    hh_records: "Bayanan lafiya", hh_records_d: "Ziyara, sakamakon dakin gwaji da takardu.",
    hh_reminders: "Abubuwan tunatarwa", hh_reminders_d: "Magani, motsa jiki, alƙawura.",
    a_title: "Asusu", a_sub: "Ƙirƙiri asusu na son rai ko ci gaba kamar baƙo.",
    a_name: "Cikakken suna", a_email: "Imel", a_phone: "Waya", a_role: "Ni ne",
    a_consumer: "Mara lafiya / al'umma", a_provider: "Mai bayar da lafiya", a_admin: "Ƙungiyar HealthLink",
    a_signup: "Ƙirƙiri asusu", a_signin: "Shiga", a_signout: "Fita",
    a_send_code: "Aiko mini lambar sirri", a_verify: "Tabbatar", a_code: "Lambar 6",
    a_language: "Harshe", a_language_d: "Canza harshen dashboard da abun cikin lafiya.",
    a_demo: "Shiga demo", a_demo_admin: "Buɗe demo gudanarwa", a_demo_provider: "Buɗe demo mai bayarwa", a_demo_consumer: "Buɗe demo mara lafiya",
    a_welcome: "An shigar da kai", c_back: "Baya", c_save: "Ajiye", c_cancel: "Soke",
    c_remove: "Cire", c_send: "Aika", c_new: "Sabo", c_status: "Matsayi", c_pending: "Jiran",
    c_approved: "An amince", c_rejected: "An ƙi", c_resolved: "An warware", c_none: "Babu",
    c_manage: "Sarrafa", c_reason: "Dalili",
    pv_title: "Mashaya mai bayarwa", pv_sub: "Sarrafa bayanan wurin ku da buƙatun kulawa.",
    pv_register: "Yi rajistar wurin ku", pv_requests: "Buƙatun tuntuɓa / booking", pv_profile: "Bayanan wuri na",
    pv_services: "Ayyuka", pv_save: "Ajiye bayanan", pv_pending: "Ana duba rajistar ku.",
    pv_none: "Babu wuri da aka tabbatar a wannan asusu.",
    pv_new_req: "Sabbin buƙatun", pv_confirm: "Alama aka tuntuɓa",
    ad_title: "Mashaya gudanarwa", ad_sub: "Abubuwa, tabbatarwa, masu amfani, kididdiga da tsaro.",
    ad_overview: "Kallo", ad_content: "Abun ciki", ad_verification: "Tabbatarwa",
    ad_users: "Masu amfani", ad_analytics: "Kididdiga", ad_reports: "Rahotanni",
    ft_nav: "HealthLink — Tsarin Kewayon Lafiyar Ku na Kai Tsaye.",
    ft_desc: "Muna haɗa ilimin lafiya da mataki mai kyau — duba lambobin ku, nemi kulawa da aka tabbatar, yi booking na ayyuka, ku bi diddigin — ga daidaikun mutane, iyalai da al'ummomi a Najeriya.",
    ft_notdx: "HealthLink yana ba da bayanin lafiya na gabaɗaya da kewayawa. Ba binciken likita ba ne kuma baya maye gurbin ƙwararren lafiya.",
    ft_emergency: "A gaggawa, koyaushe kira lambar gaggawa ta gida da farko — kafin amfani da wannan dandali.",
    ft_lang: "Akwai cikin Turanci, Yarbanci, Hausa da Igbo.",
    ft_report: "Nemi bayani da ba daidai ba ko ya tsufa",
  n_chronic: "Kulawar cututtukan da suka daɗe", n_chronic_d: "Jagorori don cututtuka kamar hawan jini.",
  n_journey: "Tafiyar lafiya", n_journey_d: "Bayanan ku da ziyarta cikin layin lokaci guda.",
  n_carecircle: "Da'irar Kulawa", n_carecircle_d: "Lafiyar iyali a gani daya.",
  n_healthdays: "Kwanakin Lafiya", n_healthdays_d: "Gwaje-gwajen al'umma da bibiyarwa.",
  n_worker: "Yanayin ma'aikaci", n_worker_d: "Kayan aiki na masu aikin lafiya na al'umma.",
  n_ask_d: "Jagor neman yanayi, kulawa da dandali.",
  cc_title: "Abokin Kulawar Cututtuka", cc_sub: "Tsarin yau da kullum da nazarin wata don cututtuka da suka daɗe.",
  cc_today: "Yau", cc_month: "Wannan wata", cc_latest: "Na baya-bayan nan", cc_care: "Kulawa", cc_find: "Nemo wurin kulawa kusa →",
  cc_hypertension: "Tafiya Hauwan Jini", cc_diabetes: "Tafiya na Ciwon Sugar",
  cc_sicklecell: "Tafiya na Ciwon Kwayar Jini", cc_asthma: "Tafiya na Shaqa",
  cc2_title: "Da'irar Kulawa", cc2_sub: "Bibiyar lafiyar wadanda kuke kula da su.",
  cc2_remove: "Cire", cc2_bp: "BP", cc2_med: "Magani", cc2_appt: "Alƙawari", cc2_screen: "Bincike na gaba",
  cc2_add: "Ƙara memba na iyali", cc2_name: "Suna / lakabi", cc2_rel: "Dangantaka", cc2_save: "Ajiye", cc2_cancel: "Soke", cc2_addb: "Ƙara memba",
  hd2_title: "Kwanakin Lafiyar Al'umma", hd2_sub: "Gwaje-gwaje da ilimi inda mutane ke taruwa.",
  hd2_create: "Ƙirƙiri rana lafiya", hd2_f_title: "Suna", hd2_f_org: "Mai shiryawa (coci, makaranta…)",
  hd2_f_date: "Kwanan wata", hd2_f_loc: "Wuri", hd2_f_srv: "Ayyuka", hd2_save: "Ƙirƙirar", hd2_cancel: "Soke", hd2_createb: "Ƙirƙiri rana lafiya",
  jt_title: "Tafiyar Lafiyar Ku", jt_sub: "Duk abin da ya faru, cikin layi guda.",
  pp_title: "Fasfo na Lafiya", pp_sub: "Bayani ɗaya. Tarihin lafiya ɗaya. A kowane wuri.",
  pp_details: "Cikakkun bayanai", pp_edit: "Gyara", pp_save: "Ajiye", pp_cancel: "Soke",
  pp_name: "Cikakken suna", pp_blood: "Jinin", pp_allergies: "Allergies", pp_meds: "Magungunan da ake bawa",
  pp_conditions: "Cututtuka da suka daɗe", pp_history: "Tarihin magani", pp_imm: "Alurar riga kafi", pp_hmo: "Inshora / HMO",
  pp_ec: "Mai tuntuɓar gaggawa", pp_ecp: "Wayar gaggawa",
  pp_card: "Katin gaggawa", pp_card_d: "Nuna wannan ga ma'aikacin lafiya a gaggawa.", pp_scan: "Duba da manhajar ma'aikatan HealthLink",
  w_title: "Yanayin Ma'aikacin Lafiya", w_sub: "Gwaje-gwaje, turawa da bibiyarwa daga filin aiki.",
  w_events: "Abubuwan", w_participants: "An gwada", w_referred: "An tura", w_pending: "Bibiyarwa ake buƙata",
  w_log: "Rubuta gwaji", w_add: "Ƙara", w_recent: "Rubutun baya-bayan nan", w_sync: "Ana adanawa a na'ura kuma za a aika idan an dawo da intanet.", w_days: "Duba kwanakin lafiya →",
  ask_title: "Tambayi HealthLink", ask_ph: "Tambaya kan yanayi, samun kulawa, farashi…", ask_send: "Aika",
  f_cost: "Farashi", f_any_cost: "Duk farashi", f_low_cost: "₦ Ƙasa", f_mid_cost: "₦₦ Matsakaici", f_high_cost: "₦₦₦ Mai tsada",
};
