import type { Dict } from "../i18n";

export const igDict: Dict = {
    n_home: "Ụlọ", n_explore: "Chọpụta", n_find: "Chọọ Nlekọta", n_services: "Ọrụ",
    n_health: "Ahụike", n_profile: "Profaịlụ", n_provider: "Onye nye", n_admin: "Nchịkwa", n_account: "Akaụntụ",
    h_title: "Kedu ka anyị ga-esi nyere gị aka taa?",
    h_sub: "Mụta banyere ahụike gị, lelee ọnụọgụ gị, chọta nlekọta kwesịrị ekwesị, ma kpọtụrụ ndị nnye aka.",
    h_learn: "Mụta banyere ahụike", h_learn_d: "Edemede dị mfe banyere ọrịa na mgbochi.",
    h_check: "Lelee ahụike gị", h_check_d: "Nlele anya, ụlọ ọgwụ, na dashboard ahụike gị.",
    h_find: "Chọọ nlekọta dị nso", h_find_d: "Ụlọ ọgwụ, PHC, ụlọ nyocha, ọgwụ na ndị ọkachamara na steeti gị.",
    h_connect: "Kpọtụrụ onye nnye aka", h_connect_d: "Kpọtụrụ ndị nnye aka ozugbo ịchọọ mbata.",
    h_search: "Chọọ isiokwu ahụike, ọrịa, ma ọ bụ ọrụ…",
    h_emergency: "Nweta enyemaka ugbu a", h_emergency_d: "Nọmba mberede na usoro mbụ enyemaka.",
    h_browse: "Chọpụta isiokwu ahụike niile", h_readmore: "Gụọ ọzọ",
    e_title: "Chọpụta agụmakwụkwọ ahụike", e_sub: "Họrọ otu ma ọ bụ gụọ isiokwu n'okpuru.",
    e_allcat: "Otu niile", e_topics: "Isiokwu", e_draft: "Dịta", e_publish: "Bipụta", e_report: "Mkpesa",
    f_title: "Chọọ Nlekọta", f_sub: "Chọọ ụlọ ọgwụ, PHC, ụlọ nyocha, ụlọ ọgwụ na ndị ọkachamara — ma kpọtụrụ ha ozugbo.",
    f_search: "Chọọ site n'aha, ọrụ, ma ọ bụ LGA…", f_all: "Otu niile", f_verified: "Egosiara", f_call: "Kpọọ",
    f_whatsapp: "WhatsApp", f_dir: "Ntụziaka", f_request: "Rịọ mbata", f_reportP: "Kpesa onye nnye",
    f_open_24: "Na-emeghe awa 24", f_no_results: "Ọ dịghị onye nnye kwekọrọ na ọchụchọ gị.", f_services: "Ọrụ",
    f_hours: "Oge", f_desc: "Banyere ebe a",
    s_title: "Ọrụ", s_sub: "Lelee ahụike gị ma debanyere ọrụ mgbochi.",
    s_book: "Debanye ọrụ ma ọ bụ mbata", s_received: "A nabatara arịrịọ",
    em_title: "Nweta Enyemaka Ugbu a", em_sub: "Ntụziaka mberede na ebe ị ga-akpọ.",
    hh_title: "Ahụike M", hh_sub: "Mpaghara gị — soro, zụọ ahụ, dekọọ, nọgide.",
    hh_exercise: "Mmega ahụ & ibu", hh_exercise_d: "Zụọ ahụ kwa ụbọchị, setịpụ ihe ncheta, soro ụzọ ibu gị.",
    hh_journal: "Akwụkwọ ahụike kwa ụbọchị", hh_journal_d: "Ọnọdụ, ihe mgbaàmà na ahụike.",
    hh_records: "Ndekọ ahụike", hh_records_d: "Mbata, nsonaazụ nyocha na akwụkwọ.",
    hh_reminders: "Ihe ncheta m", hh_reminders_d: "Ọgwụ, mmega ahụ, oge ọzọ.",
    a_title: "Akaụntụ", a_sub: "Mepụta akaụntụ ma ọ bụ nọgide dị ka ọbịa.",
    a_name: "Aha zuru ezu", a_email: "Ozi ịntanetị", a_phone: "Ekwentị", a_role: "Abụ m",
    a_consumer: "Ọrịa / onye obodo", a_provider: "Onye nnye ahụike", a_admin: "Ndị HealthLink",
    a_signup: "Mepụta akaụntụ", a_signin: "Banye", a_signout: "Pụọ",
    a_send_code: "Ziga m koodu magik", a_verify: "Kwado", a_code: "Koodu ọnụọgụ 6",
    a_language: "Asụsụ", a_language_d: "Gbanwee asụsụ nke dashboard na ọdịnaya ahụike.",
    a_demo: "Ohere ngosi", a_demo_admin: "Meghe demo nchịkwa", a_demo_provider: "Meghe demo onye nnye", a_demo_consumer: "Meghe demo ọrịa",
    a_welcome: "Abanyela", c_back: "Laghachi", c_save: "Chekwaa", c_cancel: "Kagbuo",
    c_remove: "Wepụ", c_send: "Zipu", c_new: "Ọhụrụ", c_status: "Ọnọdụ", c_pending: "Na-echere",
    c_approved: "Kwadoro", c_rejected: "Jụrụ", c_resolved: "Emeziworo", c_none: "Ọ dịghị",
    c_manage: "Jikwaa", c_reason: "Ihe kpatara",
    pv_title: "Portal onye nnye", pv_sub: "Jikwaa profaịlụ ụlọ ọrụ gị na arịrịọ nlekọta.",
    pv_register: "Deba aha ụlọ ọrụ gị", pv_requests: "Arịrịọ nzipu / mbata", pv_profile: "Profaịlụ ụlọ ọrụ m",
    pv_services: "Ọrụ", pv_save: "Chekwaa profaịlụ", pv_pending: "A na-enyocha ndebanye aha gị.",
    pv_none: "Enweghị ụlọ ọrụ kwadoro na akaụntụ a.",
    pv_new_req: "Arịrịọ ọhụrụ", pv_confirm: "Akara ekpọtụrụ",
    ad_title: "Console nchịkwa", ad_sub: "Ọdịnaya, nyocha, ndị ọrụ, nyocha na nchekwa.",
    ad_overview: "Nlele", ad_content: "Ọdịnaya", ad_verification: "Nyocha",
    ad_users: "Ndị ọrụ", ad_analytics: "Nyocha", ad_reports: "Mkpesa",
    ft_nav: "HealthLink — Sistemụ Nduzi Ahụike gị.",
    ft_desc: "Anyị na-ejikọ agụmakwụkwọ ahụike na nzọụkwụ ziri ezi — lelee ọnụọgụ gị, chọta nlekọta ekwadoro, debanye ọrụ, ma soro — maka ndị mmadụ, ezinụlọ na obodo niile na Naijiria.",
    ft_notdx: "HealthLink na-enye ozi ahụike izugbe na nduzi. Ọ bụghị nyocha ahụike ma ọ naghị anọchi anya onye ọkachamara ahụike.",
    ft_emergency: "N'ọnọdụ mberede, kpọọ nọmba mberede mpaghara gị nke mbụ — tupu i jiri ikpo okwu a.",
    ft_lang: "Dị na Bekee, Yoruba, Hausa na Igbo.",
    ft_report: "Kpesa ozi na-ezighị ezi ma ọ bụ nke ochie",
  n_chronic: "Nlekọta ọrịa oge", n_chronic_d: "Nduzi maka ọrịa na-adịte aka dịka ọbara mgbali elu.",
  n_journey: "Njem ahụike", n_journey_d: "Ndekọ na nleta gị n'otu ndepụta.",
  n_carecircle: "Gburugburu Nlekọta", n_carecircle_d: "Ahụike ezinụlọ n'otu ebe.",
  n_healthdays: "Ụbọchị Ahụike", n_healthdays_d: "Nyocha obodo na nleso anya.",
  n_worker: "Ọnọdụ onye ọrụ", n_worker_d: "Ngwa maka ndị ọrụ ahụike obodo.",
  n_ask_d: "Onye nduzi maka ọnọdụ, nlekọta na ọrụ.",
  cc_title: "Otu Nlekọta Ọrịa Oge", cc_sub: "Nhazi kwa ụbọchị na nghọta kwa ọnwa maka ọrịa na-adịte aka.",
  cc_today: "Taa", cc_month: "Ọnwa a", cc_latest: "Kacha ọhụrụ", cc_care: "Nlekọta", cc_find: "Chọta ụlọọgwụ dị nso →",
  cc_hypertension: "Njem Ọbara Mgbali Elu", cc_diabetes: "Njem Ọrịa Shuga",
  cc_sicklecell: "Njem Ọrịa Selllụ Ọbara", cc_asthma: "Njem Ụkwara Aho",
  cc2_title: "Gburugburu Nlekọta", cc2_sub: "Debe ahụike nke ndị ị na-elekọta.",
  cc2_remove: "Wepu", cc2_bp: "BP", cc2_med: "Ọgwụ", cc2_appt: "Nnọkọ", cc2_screen: "Nyocha na-abịa",
  cc2_add: "Tinye otu ezinụlọ", cc2_name: "Aha", cc2_rel: "Mmekọrịta", cc2_save: "Chekwaa", cc2_cancel: "Kagbuo", cc2_addb: "Tinye otu ezinụlọ",
  hd2_title: "Ụbọchị Ahụike Obodo", hd2_sub: "Nyocha na mmụta ebe ndị mmadụ na-ezukọ.",
  hd2_create: "Mepụta ụbọchị ahụike", hd2_f_title: "Aha", hd2_f_org: "Onye nhazi (ụka, ụlọakwụkwọ…)",
  hd2_f_date: "Ụbọchị", hd2_f_loc: "Ebe", hd2_f_srv: "Ọrụ", hd2_save: "Mepụta", hd2_cancel: "Kagbuo", hd2_createb: "Mepụta ụbọchị ahụike",
  jt_title: "Njem Ahụike Gị", jt_sub: "Ihe niile mere, n'otu ndepụta.",
  pp_title: "Paspọtụ Ahụike", pp_sub: "Otu ndepụta. Otu akụkọ ahụike. Ebe ọ bụla.",
  pp_details: "Nkọwa gị", pp_edit: "Dezie", pp_save: "Chekwaa", pp_cancel: "Kagbuo",
  pp_name: "Aha n'uju", pp_blood: "Ọbara", pp_allergies: "Ihe nfụkasị", pp_meds: "Ọgwụ ugbu a",
  pp_conditions: "Ọrịa na-adịte aka", pp_history: "Akụkọ ọgwụ", pp_imm: "Ịgba ọgwụ mgbochi", pp_hmo: "Nchekwa / HMO",
  pp_ec: "Onye kọntaktị mberede", pp_ecp: "Ekwentị mberede",
  pp_card: "Kaadị mberede", pp_card_d: "Gosi nke a nye onye ọrụ ahụike n'oge mberede.", pp_scan: "Gụọ ya na ngwa ndị ọrụ HealthLink",
  w_title: "Ọnọdụ Onye Ọrụ Ahụike", w_sub: "Nyocha, ndụmọdụ na nleso anya site n'ọgbọ.",
  w_events: "Ihe omume", w_participants: "A nyochara", w_referred: "A zigara", w_pending: "Nleso anya chọrọ",
  w_log: "Dee nyocha", w_add: "Tinye", w_recent: "Ndekọ na-adịbeghị anya", w_sync: "A na-echekwa n'ógbè ma na-ezipụ mgbe ị laghachiri n'ịntanetị.", w_days: "Lelee ụbọchị ahụike →",
  ask_title: "Jụọ HealthLink", ask_ph: "Jụọ maka ọnọdụ, inweta nlekọta, ọnụahịa…", ask_send: "Zipụ",
  f_cost: "Ọnụahịa", f_any_cost: "Ọnụahịa ọ bụla", f_low_cost: "₦ Dị ọnụ ala", f_mid_cost: "₦₦ Nkịtị", f_high_cost: "₦₦₦ Dị oke ọnụ ahịa",
  h_tagline: "Ozi Dị Mma. Ahụike Gị Ka Mma.",
  e_report_reason: "Ọktokpọ ziri ezi ma ọ bụ nsogbu nchekwa",
  f_location: "Ebe",
  f_category: "Ụdị",
  f_all_states: "Steeti nile",
  f_facility_one: "ụlọọgwụ",
  f_facility_many: "ụlọọgwụ",
  f_book_sent: "Ezigala arịrịọ. Ụlọọgwụ ahụ ga-akpọtụrụ gị.",
  f_form_msg: "Ozi",
  f_form_date: "Ụbọchị a họọrọ",
  f_emergency: "A na-enwe ọrụ mberede awa 24 n'ụlọọgwụ a.",
  f_provider_visit: "Nleta onye nye ọrụ",
  s_we_provide: "Ọrụ ahụike anyị na-enye",
  s_check_head: "Lelee Ahụike M",
  s_open_health: "Mepee ibe ahụike m",
  s_intro: "Rịọ ọrụ nyocha, njikwa obodo, ahụike ma ọ bụ nleta ụlọọgwụ mkpanaka maka onwe gị, ezinụlọ gị, ọrụ gị ma ọ bụ obodo gị. Ọ dịghị ego achọrọ iji rịọ — otu onye ga-akwado nkọwa site na ekwentị.",
  s_form_head: "Rịọ ọrụ ma ọ bụ nleta",
  s_service: "Ọrụ",
  s_date: "Ụbọchị a họọrọ",
  s_area: "Mpaghara / obodo / ebe ọrụ",
  s_submit: "Rịọ ọrụ",
  s_free_note: "Ọ dịghị ego achọrọ iji rịọ. Otu onye ga-akwado ikike, ọnụahịa na nkọwa site na ekwentị.",
  s_book_another: "Tụgharịa nleta ọzọ",
  s_on_date: " na ",
  s_success: "Daalụ {name}! Onye otu HealthLink ga-akpọtụrụ {phone} iji kwado nleta {service} gị{date}. Anyị na-akwado nkenke ọnụ ọgụgụ site na ekwentị na ihe ederede.",
  sc_bp: "Ọbara mgbali elu",
  sc_bp_d: "Nyocha BP dị mfe ma soro ntụziaka mfe.",
  sc_glu: "Glucose ọbara",
  sc_glu_d: "Nyocha glucose na ndụmọdụ ndụ.",
  sc_well: "Nlele ahụike zuru oke",
  sc_well_d: "Nleta nkịtị nke vitals na nlele ahụike zuru oke.",
  srv_education: "Mmụta ahụike",
  srv_education_d: "Oge ihe mmụta dị mfe gbasara mgbochi na omume dị mma.",
  srv_outreach: "Njikwa obodo",
  srv_outreach_d: "Ihe omume nyocha na ịkpa amata n'obodo gị.",
  srv_corporate: "Ahụike ụlọ ọrụ",
  srv_corporate_d: "Ụbọchị ahụike ụlọ ọrụ maka otu na òtù.",
  srv_mobile: "Nleta ụlọọgwụ mkpanaka",
  srv_mobile_d: "Nyocha, njikwa na ọrụ ahụike ebe ị nọ.",
  srv_referral: "Ọrụ iziga onye",
  srv_referral_d: "Njikọ a na-eduzi gaa na onye nye ọrụ kwesịrị ekwesị.",
  srv_campaigns: "Ihe omume ahụike",
  srv_campaigns_d: "Ụbọchị nyocha obodo dịka “Mara Nọmba Gị”.",
  em_call: "Kpọ nọmba mberede ozugbo",
  em_call_d: "Maka amaghị onye, mgbu obi, nsogbu iku ume, oke ọbara ọnwụ, ọkụ ọkụ, ihe ịrịba ama ọrịa strok, ma ọ bụ nsogbu ọ bụla — emela chere ma ghara ịdabere na ngwa a.",
  em_while: "Mgbe ị na-echere enyemaka ọrụaka",
  em_s1: "Debe onwe gị na onye ahụ n'udo — ekwela ịmegharị ha ma ọ bụrụ na ha nọ n'ihe ize ndụ.",
  em_s2: "Ọ bụrụ na amaghị onye mana ọ na-eku ume, tinye ha n'ọnọdụ mgbake.",
  em_s3: "Maka ọkụ ọkụ, wụsa mmiri ọkpọkọ dị jụụ n'elu ya ma ọ dịkarịa ala nkeji 20 — ejila ice, bọta ma ọ bụ ntụ ntụ.",
  em_s4: "Maka ọbara ọnwụ, pịa ọnya ahụ ike na mpempe akwa dị ọcha.",
  em_s5: "Maka ihe ịrịba ama ọrịa strok (ihu na-ala azụ, ogwe aka na-adịghị ike, okwu na-emeghachi), rute nlekọta mberede ngwa ngwa.",
  em_find_care: "Chọọ nlekọta dị mberede",
  em_find_d: "Maka nlekọta na-adịghị ize ndụ ndụ, chọta ụlọọgwụ na-enye ohere mberede nso gị.",
  em_find_hospital: "Chọọ ụlọọgwụ",
  em_find_clinic: "Chọọ ụlọọgwụ",
  em_footer: "Na mberede ahụike, kpọtụrụ nlekọta mberede ụzọ. HealthLink bụ maka mmụta na nduzi naanị.",
  hh_know: "Mara nọmba gị",
  hh_open: "Mepee",
  hh_know_d: "Malite Ụbọchị Ahụike Obodo HealthLink ma ọ bụ tụgharịa nleta ụlọọgwụ mkpanaka iji lelee ọbara mgbali elu gị na glucose site na nlekọta ọrụaka.",
  n_passport: "Paspọtụ",
  n_ask: "Jụọ",
  a_code_sent: "Ezigala imel ọpụrụiche — lelee koodu dị n'okpuru.",
  a_email_required: "Tinye imel mbụ.",
  a_code_mismatch: "Koodu ahụ dakọtara. Lelee ma nwaa ọzọ.",
  a_demo_mode: "ọnọdụ ọpụrụiche a na-egosi koodu kama iziga imel.",
  a_demo_note: "Ebe ndị nye ọrụ na admin ka edobere n'akụkụ ọrụ na njikọ igbe.",
  a_email_ph: "gị@ọmụmaatụ.com",
  a_member_default: "Otu onye HealthLink",
  pv_confirm_done: "Kwado",
  pv_guard: "Ebe a bụ maka ndị nye ọrụ ahụike e nyochara. Banye site na akaụntụ onye nye ọrụ ma ọ bụ admin iji gaa n'ihu.",
  pv_services_label: "Ọrụ (kewaa site na kọma)",
  pv_about: "Gbasara ụlọọgwụ a",
  pv_no_message: "Enweghị ozi",
  prg_lead: "Ndị nye ọrụ na-edebanye aha otu ugboro; ndị otu HealthLink na-enyocha ụlọọgwụ ọ bụla tupu ha pụta na Chọọ Nlekọta dịka onye nye ọrụ nyochara.",
  prg_facility: "Aha ụlọọgwụ",
  prg_category: "Ụdị",
  prg_state: "Steeti",
  prg_lga: "LGA / mpaghara",
  prg_address: "Adreesi",
  prg_submit: "Nyefee maka nnyocha",
  prg_note: "Nnyocha na-echebe obodo: naanị ndị nye ọrụ nyochara ka a na-egosi kaa ✓ na Chọọ Nlekọta.",
  prg_success_1: "Ezigala {facility} maka nnyocha.",
  prg_success_2: "Ị ga-enwe ike ijikwa arịrịọ na profaịlụ gị site na ọdụ onye nye ọrụ ozugbo e nyere ya nkwenye.",
  ad_signin_req: "Ebe a ka ndị otu HealthLink ka ejidere. Jiri akaụntụ ọpụrụiche admin iji hụ njikwa ọdịnaya, nnyocha, ndị ọrụ, nyocha na akụkọ.",
  ad_providers: "Ndị nye ọrụ",
  ad_verified_p: "Ndị nye ọrụ nyochara",
  ad_topics: "Isiokwu",
  ad_verify_pending: "Nnyocha ndị na-echere",
  ad_bookings: "Nhọpụta",
  ad_reports_open: "Akụkọ ndị meghere",
  ad_c_add: "Tinye isiokwu (draft)",
  ad_c_slug: "slug",
  ad_c_title: "Aha",
  ad_c_summary: "Nchịkọta",
  ad_c_category: "Ụdị",
  ad_c_add_draft: "Tinye draft",
  ad_c_publish: "Bipụta",
  ad_c_unpublish: "Kwụsị ibipụta",
  ad_c_delete: "Hichapụ",
  ad_c_required: "Achọrọ slug na aha.",
  ad_c_draft_note: "Draft — tinye nchịkọta tupu ibipụta.",
  ad_c_empty_summary: "Na-abịa n'oge na-adịghị anya.",
  ad_c_exists: "Isiokwu nwere slug a dịlarị.",
  ad_c_created: "Emepụtala draft — bipụta site na ndepụta dị n'okpuru.",
  ad_v_none: "Enweghị arịrịọ ndebanye aha.",
  ad_v_verify: "Nyochaa & bipụta",
  ad_v_reject: "Jụ",
  ad_v_approved_desc: "HealthLink nyochara nke a mgbe okwu akwụkwọ.",
  ad_u_name: "Aha",
  ad_u_email: "Email",
  ad_u_role: "Ọrụ",
  ad_u_joined: "Sonye",
  ad_a_cat: "Ndị nye ọrụ site n'ụdị",
  ad_a_state: "Ndị nye ọrụ site n'ụdị steeti",
  ad_a_bookings: "Arịrịọ nhọpụta — ụbọchị 14 gara aga",
  ad_a_requests: "Arịrịọ",
  ad_a_pipeline: "Nhazi ndebanye aha:",
  ad_a_submitted: "e nyefere",
  ad_a_approved: "akwadoro",
  ad_a_pending0: "na-eche",
  ad_r_none: "Enweghị akụkọ.",
  ad_r_resolve: "Mee ngwọta",
  pr_requests: "Arịrịọ m",
  pr_no_requests: "Enweghị arịrịọ nhọpụta ọ bụla.",
  pr_get_started: "iji malite.",
  pr_provider: "Nleta onye nye ọrụ",
  pr_appt: "Nhọpụta",
  pr_appt_d: "Nleta na arịrịọ na-abịa ga-apụta ebe a.",
  pr_rem: "Ihe ncheta",
  pr_rem_d: "Ezitela ihe ncheta ọgwụ na nyocha.",
  pr_saved: "Ndị nye ọrụ e chebere",
  pr_saved_d: "Samisịa ụlọọgwụ na ndị ọrụaka ị na-atụkwasị obi.",
  pr_records: "Ndekọ ahụike",
  pr_records_d: "Ndekọ na-apụta naanị ebe iwu kwetara.",
  pr_soon: "Na-abịa n'oge na-adịghị anya",
  j_title: "Akwụkwọ akụkọ ahụike",
  j_sub: "Dee ọnọdụ gị, ihe mgbaàmà gị, na ihe dị mkpa nke vitals ụbọchị ọ bụla.",
  j_new: "Ntinye ọhụrụ",
  j_date: "Ụbọchị",
  j_mood: "Ọnọdụ",
  j_symptoms: "Ihe mgbaàmà",
  j_weight: "Arọ (kg)",
  j_heart: "Ọnụ obi (bpm)",
  j_sleep: "Ụra (hrs)",
  j_steps: "Nzọụkwụ",
  j_bp_sys: "BP kwesiri elu",
  j_bp_dia: "BP kwesiri ala",
  j_notes: "Ndetu",
  j_note_ph: "Kedu ka ụbọchị gị si gara?",
  j_save: "Chekwaa ntinye",
  j_empty: "Enweghị ntinye akụkọ akụkọ ọ bụla. Tinye nke mbụ gị.",
  j_collapse: "Dwụlikwuo",
  j_details: "Nkọwa",
  j_delete: "Hichapụ",
  r_title: "Ihe ncheta",
  r_sub: "Ọgwụ, mmiri, mmega ahụ, na nhọpụta.",
  r_new: "Ncheta ọhụrụ",
  r_title_field: "Aha",
  r_title_ph: "dịka. Ọgwụ mgbede",
  r_time: "Oge",
  r_type: "Ụdị",
  r_repeat: "Megharịa na",
  r_notes: "Ndetu",
  r_notes_ph: "Nkọwa nhọrọ…",
  r_add: "Tinye ncheta",
  r_today: "Taa",
  r_none_today: "Enweghị ihe edozi maka taa.",
  r_all: "Ncheta niile",
  r_none: "Enweghị ncheta ọ bụla. Tinye nke mbụ gị.",
  r_on: "Ọnụ",
  r_off: "Gbanyụọ",
  r_disable: "Gbanyụọ",
  r_enable: "Gbanye",
  r_delete: "Hichapụ",
  rc_title: "Ndekọ ahụike",
  rc_sub: "Debe ebe a na-ejikọ akụkọ nleta, akụkọ laabu, na ndenye ọgwụ.",
  rc_add: "Tinye ndekọ",
  rc_title_field: "Aha",
  rc_title_ph: "dịka. Nsonaazụ nnwale ọbara",
  rc_provider: "Onye nye ọrụ / ụlọọgwụ",
  rc_provider_ph: "dịka. Dr. Smith, Ụlọọgwụ Obodo",
  rc_date: "Ụbọchị",
  rc_category: "Ụdị",
  rc_summary: "Nchịkọta / nsonaazụ",
  rc_summary_ph: "Ọchọpụta ma ọ bụ nkuzi akwụkwọ…",
  rc_link: "Njikọ (nhọrọ)",
  rc_save: "Chekwaa ndekọ",
  rc_all: "Niile",
  rc_empty: "Enweghị ndekọ ebe a.",
  rc_delete: "Hichapụ",
  rc_open: "Mepee ndekọ ejiri njikọ",
  ex_back: "Laghachi Azụ na Ahụike M",
  ex_title: "Njem Mmega Ahụ & Arọ",
  ex_sub: "Debe ihe mgbaru ọsọ gị, dee omume gị kwa ụbọchị, ma lelee ọganihu gị. Data gị na-anọ na ngwaọrụ a.",
  ex_streak: "{n} ụbọchị usoro",
  ex_goal_1: "Ihe mgbaru ọsọ gị",
  ex_loss_goal: "Ihe mgbaru ọsọ mbelata arọ",
  ex_gain_goal: "Ihe mgbaru ọsọ ịba arọ",
  ex_goalfmt: " — site na {start} kg ruo {goal} kg ( ịdị elu {h} cm).",
  ex_height: "Ịdị elu (cm)",
  ex_start_w: "Arọ mmalite (kg)",
  ex_goal_w: "Arọ ihe mgbaru ọsọ (kg)",
  ex_save_goal: "Chekwaa ihe mgbaru ọsọ",
  ex_today_w_ph: "De ndekọ arọ taa (kg)",
  ex_record_w: "De ndekọ arọ",
  ex_warn: "Biko tinye ịdị elu, arọ mmalite na arọ ihe mgbaru ọsọ n'ime cm / kg.",
  ex_cur_w: "Arọ ugbu a",
  ex_lost: "Mbelata ruo ugbu a",
  ex_gained: "Ịbawanye ruo ugbu a",
  ex_to_goal: "gaa na ihe mgbaru ọsọ",
  ex_progress: "Ọganihu njem",
  ex_goal_x: "Ihe mgbaru ọsọ {g} kg",
  ex_week_active: "Na-arụ ọrụ n'izu a",
  ex_logged_today: "{n} e dekọtara taa",
  ex_weight_journey_2: "Njem arọ",
  ex_checkins: "{n} nyocha",
  ex_goal_label: "Ihe mgbaru ọsọ",
  ex_date: "Ụbọchị",
  ex_weight: "Arọ",
  ex_change: "Mgbanwe",
  ex_start: "mmalite",
  ex_train_3: "Ọzụzụ kwa ụbọchị",
  ex_done: "Mee taa",
  ex_not_done: "Emebeghị taa",
  ex_exercise: "Mmega ahụ",
  ex_minutes: "Nkeji",
  ex_note_opt: "Ndetu (nhọrọ)",
  ex_note_ph: "dịka. mmetụta ọma, oge mgbede",
  ex_log: "De ndekọ mmega ahụ",
  ex_remove: "Wepụ",
  ex_no_today: "Enweghị mmega ahụ e dekọtara taa. Họrọ mmega ahụ n'elu ma ọ bụ site na ọba akwụkwọ dị n'okpuru.",
  ex_reminder_4: "Ncheta mmega ahụ kwa ụbọchị",
  ex_rem_on: "Na-arụ ọrụ — emebere ncheta maka {time}.",
  ex_rem_off: "A gbanyụọ ncheta.",
  ex_rem_time: "Oge ncheta",
  ex_rem_note: "Ncheta mpaghara na-enyere gị aka idowe usoro kwa ụbọchị. A na-eme atụmatụ ịzipu ọkwa maka MVP dijitalụ.",
  ex_library_5: "Ọba akwụkwọ mmega ahụ",
  ex_library_d: "Foto na vidiyo njedebe dị iche iche nke mmega ahụ. Họrọ otu wee dekọọ ya ka mmega ahụ taa.",
  ex_hide: "Zoo",
  ex_howto: "Otu esi eme ya",
  ex_log_today: "De ndekọ taa",
  ex_media_1: "Iji tinye mgbasa ozi nke gị: tụba foto n'ime",
  ex_media_2: "na vidiyo n'ime",
  ex_media_3: "Ha na-apụta ozugbo.",
  hd_when: "Mgbe ị ga-achọ enyemaka ọrụaka",
  hd_what: "Kedu ihe ọ bụ",
  hd_symptoms: "Ihe mgbaàmà na ihe ịrịba ama",
  hd_risk: "Ihe ize ndụ",
  hd_prevention: "Mgbochi",
  hd_faqs: "Ajụjụ ndị a na-ajụkarị",
  hd_read_more: "Gụkwuo",
  hd_reviewed: "Kọmitii nyochara",
  hd_report: "Mkpesa",
  hd_source: "Isi mmalite:",
  hd_find_help: "Chọta Enyemaka Nso",
  sv_emergency: "Mberede",
  sv_hospitals: "Ụlọọgwụ",
  sv_phc: "Ụlọọgwụ mbụ",
  sv_labs: "Ụlọ nyocha",
  sv_pharmacies: "Ụlọogo ọgwụ",
  sv_professionals: "Ndị ọkachamara",
  count_results: "{n} onye nye ọrụ",
  lang: "Asụsụ Igbo",
};
