import type { Dict } from "../i18n";

export const igDict: Dict = {
    n_home: "Ụlọ", n_explore: "Chọpụta", n_find: "Chọọ Nlekọta", n_services: "Ọrụ",
    n_health: "Ahụike", n_profile: "Profaịlụ", n_provider: "Onye nye", n_admin: "Nchịkwa", n_account: "Akaụntụ",
    h_title: "Kedu ka anyị ga-esi nyere gị aka taa?",
    h_sub: "Mụta banyere ahụike gị, lelee ọnụọgụ gị, chọta nlekọta kwesịrị ekwesị, ma kpọtụrụ ndị nnye aka.",
    h_learn: "Mụta banyere ahụike", h_learn_d: "Edemede dị mfe banyere ọrịa na mgbochi.",
    h_check: "Lelee ahụike gị", h_check_d: "Nlele anya, ụlọ ọgwụ, na dashboard ahụike gị.",
    h_find: "Chọọ nlekọta dị nso", h_find_d: "Ụlọ ọgwụ, PHC, ụlọ nyocha, ọgwụ na ndị ọkachamara na steeti gị.",
    h_connect: "Kpọtụrụ onye nnye aka", h_connect_d: "Kpọtụrụ ndị nnye aka ozugbo ịchọọ mbata.",
    h_search: "Chọọ isiokwu ahụike, ọrịa, ma ọ bụ ọrụ…",
    h_emergency: "Nweta enyemaka ugbu a", h_emergency_d: "Nọmba mberede na usoro mbụ enyemaka.",
    h_browse: "Chọpụta isiokwu ahụike niile", h_readmore: "Gụọ ọzọ",
    e_title: "Chọpụta agụmakwụkwọ ahụike", e_sub: "Họrọ otu ma ọ bụ gụọ isiokwu n'okpuru.",
    e_allcat: "Otu niile", e_topics: "Isiokwu", e_draft: "Dịta", e_publish: "Bipụta", e_report: "Mkpesa",
    f_title: "Chọọ Nlekọta", f_sub: "Chọọ ụlọ ọgwụ, PHC, ụlọ nyocha, ụlọ ọgwụ na ndị ọkachamara — ma kpọtụrụ ha ozugbo.",
    f_search: "Chọọ site n'aha, ọrụ, ma ọ bụ LGA…", f_all: "Otu niile", f_verified: "Egosiara", f_call: "Kpọọ",
    f_whatsapp: "WhatsApp", f_dir: "Ntụziaka", f_request: "Rịọ mbata", f_reportP: "Kpesa onye nnye",
    f_open_24: "Na-emeghe awa 24", f_no_results: "Ọ dịghị onye nnye kwekọrọ na ọchụchọ gị.", f_services: "Ọrụ",
    f_hours: "Oge", f_desc: "Banyere ebe a",
    s_title: "Ọrụ", s_sub: "Lelee ahụike gị ma debanyere ọrụ mgbochi.",
    s_book: "Debanye ọrụ ma ọ bụ mbata", s_received: "A nabatara arịrịọ",
    em_title: "Nweta Enyemaka Ugbu a", em_sub: "Ntụziaka mberede na ebe ị ga-akpọ.",
    hh_title: "Ahụike M", hh_sub: "Mpaghara gị — soro, zụọ ahụ, dekọọ, nọgide.",
    hh_exercise: "Mmega ahụ & ibu", hh_exercise_d: "Zụọ ahụ kwa ụbọchị, setịpụ ihe ncheta, soro ụzọ ibu gị.",
    hh_journal: "Akwụkwọ ahụike kwa ụbọchị", hh_journal_d: "Ọnọdụ, ihe mgbaàmà na ahụike.",
    hh_records: "Ndekọ ahụike", hh_records_d: "Mbata, nsonaazụ nyocha na akwụkwọ.",
    hh_reminders: "Ihe ncheta m", hh_reminders_d: "Ọgwụ, mmega ahụ, oge ọzọ.",
    a_title: "Akaụntụ", a_sub: "Mepụta akaụntụ ma ọ bụ nọgide dị ka ọbịa.",
    a_name: "Aha zuru ezu", a_email: "Ozi ịntanetị", a_phone: "Ekwentị", a_role: "Abụ m",
    a_consumer: "Ọrịa / onye obodo", a_provider: "Onye nnye ahụike", a_admin: "Ndị HealthLink",
    a_signup: "Mepụta akaụntụ", a_signin: "Banye", a_signout: "Pụọ",
    a_send_code: "Ziga m koodu magik", a_verify: "Kwado", a_code: "Koodu ọnụọgụ 6",
    a_language: "Asụsụ", a_language_d: "Gbanwee asụsụ nke dashboard na ọdịnaya ahụike.",
    a_demo: "Ohere ngosi", a_demo_admin: "Meghe demo nchịkwa", a_demo_provider: "Meghe demo onye nnye", a_demo_consumer: "Meghe demo ọrịa",
    a_welcome: "Abanyela", c_back: "Laghachi", c_save: "Chekwaa", c_cancel: "Kagbuo",
    c_remove: "Wepụ", c_send: "Zipu", c_new: "Ọhụrụ", c_status: "Ọnọdụ", c_pending: "Na-echere",
    c_approved: "Kwadoro", c_rejected: "Jụrụ", c_resolved: "Emeziworo", c_none: "Ọ dịghị",
    c_manage: "Jikwaa", c_reason: "Ihe kpatara",
    pv_title: "Portal onye nnye", pv_sub: "Jikwaa profaịlụ ụlọ ọrụ gị na arịrịọ nlekọta.",
    pv_register: "Deba aha ụlọ ọrụ gị", pv_requests: "Arịrịọ nzipu / mbata", pv_profile: "Profaịlụ ụlọ ọrụ m",
    pv_services: "Ọrụ", pv_save: "Chekwaa profaịlụ", pv_pending: "A na-enyocha ndebanye aha gị.",
    pv_none: "Enweghị ụlọ ọrụ kwadoro na akaụntụ a.",
    pv_new_req: "Arịrịọ ọhụrụ", pv_confirm: "Akara ekpọtụrụ",
    ad_title: "Console nchịkwa", ad_sub: "Ọdịnaya, nyocha, ndị ọrụ, nyocha na nchekwa.",
    ad_overview: "Nlele", ad_content: "Ọdịnaya", ad_verification: "Nyocha",
    ad_users: "Ndị ọrụ", ad_analytics: "Nyocha", ad_reports: "Mkpesa",
    ft_nav: "HealthLink — Sistemụ Nduzi Ahụike gị.",
    ft_desc: "Anyị na-ejikọ agụmakwụkwọ ahụike na nzọụkwụ ziri ezi — lelee ọnụọgụ gị, chọta nlekọta ekwadoro, debanye ọrụ, ma soro — maka ndị mmadụ, ezinụlọ na obodo niile na Naijiria.",
    ft_notdx: "HealthLink na-enye ozi ahụike izugbe na nduzi. Ọ bụghị nyocha ahụike ma ọ naghị anọchi anya onye ọkachamara ahụike.",
    ft_emergency: "N'ọnọdụ mberede, kpọọ nọmba mberede mpaghara gị nke mbụ — tupu i jiri ikpo okwu a.",
    ft_lang: "Dị na Bekee, Yoruba, Hausa na Igbo.",
    ft_report: "Kpesa ozi na-ezighị ezi ma ọ bụ nke ochie",
  n_chronic: "Nlekọta ọrịa oge", n_chronic_d: "Nduzi maka ọrịa na-adịte aka dịka ọbara mgbali elu.",
  n_journey: "Njem ahụike", n_journey_d: "Ndekọ na nleta gị n'otu ndepụta.",
  n_carecircle: "Gburugburu Nlekọta", n_carecircle_d: "Ahụike ezinụlọ n'otu ebe.",
  n_healthdays: "Ụbọchị Ahụike", n_healthdays_d: "Nyocha obodo na nleso anya.",
  n_worker: "Ọnọdụ onye ọrụ", n_worker_d: "Ngwa maka ndị ọrụ ahụike obodo.",
  n_ask_d: "Onye nduzi maka ọnọdụ, nlekọta na ọrụ.",
  cc_title: "Otu Nlekọta Ọrịa Oge", cc_sub: "Nhazi kwa ụbọchị na nghọta kwa ọnwa maka ọrịa na-adịte aka.",
  cc_today: "Taa", cc_month: "Ọnwa a", cc_latest: "Kacha ọhụrụ", cc_care: "Nlekọta", cc_find: "Chọta ụlọọgwụ dị nso →",
  cc_hypertension: "Njem Ọbara Mgbali Elu", cc_diabetes: "Njem Ọrịa Shuga",
  cc_sicklecell: "Njem Ọrịa Selllụ Ọbara", cc_asthma: "Njem Ụkwara Aho",
  cc2_title: "Gburugburu Nlekọta", cc2_sub: "Debe ahụike nke ndị ị na-elekọta.",
  cc2_remove: "Wepu", cc2_bp: "BP", cc2_med: "Ọgwụ", cc2_appt: "Nnọkọ", cc2_screen: "Nyocha na-abịa",
  cc2_add: "Tinye otu ezinụlọ", cc2_name: "Aha", cc2_rel: "Mmekọrịta", cc2_save: "Chekwaa", cc2_cancel: "Kagbuo", cc2_addb: "Tinye otu ezinụlọ",
  hd2_title: "Ụbọchị Ahụike Obodo", hd2_sub: "Nyocha na mmụta ebe ndị mmadụ na-ezukọ.",
  hd2_create: "Mepụta ụbọchị ahụike", hd2_f_title: "Aha", hd2_f_org: "Onye nhazi (ụka, ụlọakwụkwọ…)",
  hd2_f_date: "Ụbọchị", hd2_f_loc: "Ebe", hd2_f_srv: "Ọrụ", hd2_save: "Mepụta", hd2_cancel: "Kagbuo", hd2_createb: "Mepụta ụbọchị ahụike",
  jt_title: "Njem Ahụike Gị", jt_sub: "Ihe niile mere, n'otu ndepụta.",
  pp_title: "Paspọtụ Ahụike", pp_sub: "Otu ndepụta. Otu akụkọ ahụike. Ebe ọ bụla.",
  pp_details: "Nkọwa gị", pp_edit: "Dezie", pp_save: "Chekwaa", pp_cancel: "Kagbuo",
  pp_name: "Aha n'uju", pp_blood: "Ọbara", pp_allergies: "Ihe nfụkasị", pp_meds: "Ọgwụ ugbu a",
  pp_conditions: "Ọrịa na-adịte aka", pp_history: "Akụkọ ọgwụ", pp_imm: "Ịgba ọgwụ mgbochi", pp_hmo: "Nchekwa / HMO",
  pp_ec: "Onye kọntaktị mberede", pp_ecp: "Ekwentị mberede",
  pp_card: "Kaadị mberede", pp_card_d: "Gosi nke a nye onye ọrụ ahụike n'oge mberede.", pp_scan: "Gụọ ya na ngwa ndị ọrụ HealthLink",
  w_title: "Ọnọdụ Onye Ọrụ Ahụike", w_sub: "Nyocha, ndụmọdụ na nleso anya site n'ọgbọ.",
  w_events: "Ihe omume", w_participants: "A nyochara", w_referred: "A zigara", w_pending: "Nleso anya chọrọ",
  w_log: "Dee nyocha", w_add: "Tinye", w_recent: "Ndekọ na-adịbeghị anya", w_sync: "A na-echekwa n'ógbè ma na-ezipụ mgbe ị laghachiri n'ịntanetị.", w_days: "Lelee ụbọchị ahụike →",
  ask_title: "Jụọ HealthLink", ask_ph: "Jụọ maka ọnọdụ, inweta nlekọta, ọnụahịa…", ask_send: "Zipụ",
  f_cost: "Ọnụahịa", f_any_cost: "Ọnụahịa ọ bụla", f_low_cost: "₦ Dị ọnụ ala", f_mid_cost: "₦₦ Nkịtị", f_high_cost: "₦₦₦ Dị oke ọnụ ahịa",
};
