import type { Dict } from "../i18n";

export const igDict: Dict = {
    n_home: "Ụlọ", n_explore: "Chọpụta", n_find: "Chọọ Nlekọta", n_services: "Ọrụ",
    n_health: "Ahụike", n_profile: "Profaịlụ", n_provider: "Onye nye", n_admin: "Nchịkwa", n_account: "Akaụntụ",
    mh_title: "Akwụkwọ Ahụike M", mh_sub: "Dekọọ nsọ, ọnọdụ na mgbaàmà.",
    home_good_morning: "Ụtụtụ ọma",
    home_good_afternoon: "Ehihie ọma",
    home_good_evening: "Mgbede ọma",
    h_title: "Kedu ka anyị ga-esi nyere gị aka taa?",
    h_sub: "Mụta banyere ahụike gị, lelee ọnụọgụ gị, chọta nlekọta kwesịrị ekwesị, ma kpọtụrụ ndị nnye aka.",
    h_learn: "Mụta banyere ahụike", h_learn_d: "Edemede dị mfe banyere ọrịa na mgbochi.",
    h_check: "Lelee ahụike gị", h_check_d: "Nlele anya, ụlọ ọgwụ, na dashboard ahụike gị.",
    h_find: "Chọọ nlekọta dị nso", h_find_d: "Ụlọ ọgwụ, PHC, ụlọ nyocha, ọgwụ na ndị ọkachamara na steeti gị.",
    h_connect: "Kpọtụrụ onye nnye aka", h_connect_d: "Kpọtụrụ ndị nnye aka ozugbo ịchọọ mbata.",
    h_search: "Chọọ isiokwu ahụike, ọrịa, ma ọ bụ ọrụ…",
    h_emergency: "Nweta enyemaka ugbu a", h_emergency_d: "Nọmba mberede na usoro mbụ enyemaka.",
    h_browse: "Chọpụta isiokwu ahụike niile", h_readmore: "Gụọ ọzọ",
    e_title: "Chọpụta agụmakwụkwọ ahụike", e_sub: "Họrọ otu ma ọ bụ gụọ isiokwu n'okpuru.",
    e_allcat: "Otu niile", e_topics: "Isiokwu", e_draft: "Dịta", e_publish: "Bipụta", e_report: "Mkpesa",
    f_title: "Chọọ Nlekọta", f_sub: "Chọọ ụlọ ọgwụ, PHC, ụlọ nyocha, ụlọ ọgwụ na ndị ọkachamara — ma kpọtụrụ ha ozugbo.",
    f_search: "Chọọ site n'aha, ọrụ, ma ọ bụ LGA…", f_all: "Otu niile", f_verified: "Egosiara", f_call: "Kpọọ",
    f_whatsapp: "WhatsApp", f_dir: "Ntụziaka", f_request: "Rịọ mbata", f_reportP: "Kpesa onye nnye",
    f_open_24: "Na-emeghe awa 24", f_no_results: "Ọ dịghị onye nnye kwekọrọ na ọchụchọ gị.", f_services: "Ọrụ",
    f_hours: "Oge", f_desc: "Banyere ebe a",
    s_title: "Ọrụ", s_sub: "Lelee ahụike gị ma debanyere ọrụ mgbochi.",
    s_book: "Debanye ọrụ ma ọ bụ mbata", s_received: "A nabatara arịrịọ",
    em_title: "Nweta Enyemaka Ugbu a", em_sub: "Ntụziaka mberede na ebe ị ga-akpọ.",
    hh_title: "Ahụike M", hh_sub: "Mpaghara gị — soro, zụọ ahụ, dekọọ, nọgide.",
    hh_exercise: "Mmega ahụ & ibu", hh_exercise_d: "Zụọ ahụ kwa ụbọchị, setịpụ ihe ncheta, soro ụzọ ibu gị.",
    hh_journal: "Akwụkwọ ahụike kwa ụbọchị", hh_journal_d: "Ọnọdụ, ihe mgbaàmà na ahụike.",
    hh_records: "Ndekọ ahụike", hh_records_d: "Mbata, nsonaazụ nyocha na akwụkwọ.",
    hh_reminders: "Ihe ncheta m", hh_reminders_d: "Ọgwụ, mmega ahụ, oge ọzọ.",
    a_title: "Akaụntụ", a_sub: "Mepụta akaụntụ ma ọ bụ nọgide dị ka ọbịa.",
    a_name: "Aha zuru ezu", a_email: "Ozi ịntanetị", a_phone: "Ekwentị", a_role: "Abụ m",
    a_consumer: "Ọrịa / onye obodo", a_provider: "Onye nnye ahụike", a_admin: "Ndị CareNBuddi",
    a_signup: "Mepụta akaụntụ", a_signin: "Banye", a_signout: "Pụọ",
    a_send_code: "Ziga m koodu magik", a_verify: "Kwado", a_code: "Koodu ọnụọgụ 6",
    a_language: "Asụsụ", a_language_d: "Gbanwee asụsụ nke dashboard na ọdịnaya ahụike.",
    a_demo: "Ohere ngosi", a_demo_admin: "Meghe demo nchịkwa", a_demo_provider: "Meghe demo onye nnye", a_demo_consumer: "Meghe demo ọrịa",
    a_welcome: "Abanyela", c_back: "Laghachi", c_save: "Chekwaa", c_cancel: "Kagbuo",
    a_password: "Okwuntughe",
    a_cloud: "Akaụntụ igwe",
    a_cloud_d: "Banye iji chekwara nchekwa data gị ma jiri CareNBuddi na ngwaọ dị ọtụtụ.",
    a_signed_in_as: "Abanyere na",
    a_sync_now: "Hazi aha",
    a_syncing: "Na-eme…",
    a_synced: "Echerela data niile",
    a_sync_idle: "Njiri maka iji rịọ",
a_sync_off: "Nlọọgụ offline — data gị nọrọ na ngwaọ a",
  a_offline_note: "Arụ ọrụ n'ọflaịn — data gị nọ n'ngwaọ a. Banye iji ji anyaghị data n'etiti ngwaọ dị iche.",
  auth_or: "maọbụ",
  auth_google: "Google",
  auth_apple: "Apple",
  a_confirm_email: "Emere akaụntụ. Lelee ozi-e gị iji kwado, mgbe ahụ banye.",
    a_bad_login: "Ozi-e ma ọ bụ okwuntughe ezighi ezi.",
    a_missing_fields: "Banye ozi-e gị na okwuntughe gị.",
    c_remove: "Wepụ", c_send: "Zipu", c_new: "Ọhụrụ", c_status: "Ọnọdụ", c_pending: "Na-echere",
    c_approved: "Kwadoro", c_rejected: "Jụrụ", c_resolved: "Emeziworo", c_none: "Ọ dịghị",
    c_manage: "Jikwaa", c_reason: "Ihe kpatara",
    pv_title: "Portal onye nnye", pv_sub: "Jikwaa profaịlụ ụlọ ọrụ gị na arịrịọ nlekọta.",
    pv_register: "Deba aha ụlọ ọrụ gị", pv_requests: "Arịrịọ nzipu / mbata", pv_profile: "Profaịlụ ụlọ ọrụ m",
    pv_services: "Ọrụ", pv_save: "Chekwaa profaịlụ", pv_pending: "A na-enyocha ndebanye aha gị.",
    pv_none: "Enweghị ụlọ ọrụ kwadoro na akaụntụ a.",
    pv_new_req: "Arịrịọ ọhụrụ", pv_confirm: "Akara ekpọtụrụ",
    ad_title: "Console nchịkwa", ad_sub: "Ọdịnaya, nyocha, ndị ọrụ, nyocha na nchekwa.",
    ad_overview: "Nlele", ad_content: "Ọdịnaya", ad_verification: "Nyocha",
    ad_users: "Ndị ọrụ", ad_analytics: "Nyocha", ad_reports: "Mkpesa",
    ft_nav: "CareNBuddi — Sistemụ Nduzi Ahụike gị.",
    ft_desc: "Anyị na-ejikọ agụmakwụkwọ ahụike na nzọụkwụ ziri ezi — lelee ọnụọgụ gị, chọta nlekọta ekwadoro, debanye ọrụ, ma soro — maka ndị mmadụ, ezinụlọ na obodo niile na Naijiria.",
    ft_notdx: "CareNBuddi na-enye ozi ahụike izugbe na nduzi. Ọ bụghị nyocha ahụike ma ọ naghị anọchi anya onye ọkachamara ahụike.",
    ft_emergency: "N'ọnọdụ mberede, kpọọ nọmba mberede mpaghara gị nke mbụ — tupu i jiri ikpo okwu a.",
    ft_lang: "Dị na Bekee, Yoruba, Hausa na Igbo.",
    ft_report: "Kpesa ozi na-ezighị ezi ma ọ bụ nke ochie",
  n_chronic: "Nlekọta ọrịa oge", n_chronic_d: "Nduzi maka ọrịa na-adịte aka dịka ọbara mgbali elu.",
  n_journey: "Njem ahụike", n_journey_d: "Ndekọ na nleta gị n'otu ndepụta.",
  n_carecircle: "Gburugburu Nlekọta", n_carecircle_d: "Ahụike ezinụlọ n'otu ebe.",
  n_healthdays: "Ụbọchị Ahụike", n_healthdays_d: "Nyocha obodo na nleso anya.",
  n_worker: "Ọnọdụ onye ọrụ", n_worker_d: "Ngwa maka ndị ọrụ ahụike obodo.",
  n_ask_d: "Onye nduzi maka ọnọdụ, nlekọta na ọrụ.",
  cc_title: "Otu Nlekọta Ọrịa Oge", cc_sub: "Nhazi kwa ụbọchị na nghọta kwa ọnwa maka ọrịa na-adịte aka.",
  cc_today: "Taa", cc_month: "Ọnwa a", cc_latest: "Kacha ọhụrụ", cc_care: "Nlekọta", cc_find: "Chọta ụlọọgwụ dị nso →",
  cc_hypertension: "Njem Ọbara Mgbali Elu", cc_diabetes: "Njem Ọrịa Shuga",
  cc_sicklecell: "Njem Ọrịa Selllụ Ọbara", cc_asthma: "Njem Ụkwara Aho",
  cc2_title: "Gburugburu Nlekọta", cc2_sub: "Debe ahụike nke ndị ị na-elekọta.",
  cc2_remove: "Wepu", cc2_bp: "BP", cc2_med: "Ọgwụ", cc2_appt: "Nnọkọ", cc2_screen: "Nyocha na-abịa",
  cc2_add: "Tinye otu ezinụlọ", cc2_name: "Aha", cc2_rel: "Mmekọrịta", cc2_save: "Chekwaa", cc2_cancel: "Kagbuo", cc2_addb: "Tinye otu ezinụlọ",
  hd2_title: "Ụbọchị Ahụike Obodo", hd2_sub: "Nyocha na mmụta ebe ndị mmadụ na-ezukọ.",
  hd2_create: "Mepụta ụbọchị ahụike", hd2_f_title: "Aha", hd2_f_org: "Onye nhazi (ụka, ụlọakwụkwọ…)",
  hd2_f_date: "Ụbọchị", hd2_f_loc: "Ebe", hd2_f_srv: "Ọrụ", hd2_save: "Mepụta", hd2_cancel: "Kagbuo", hd2_createb: "Mepụta ụbọchị ahụike",
  jt_title: "Njem Ahụike Gị", jt_sub: "Ihe niile mere, n'otu ndepụta.",
  pp_title: "Paspọtụ Ahụike", pp_sub: "Otu ndepụta. Otu akụkọ ahụike. Ebe ọ bụla.",
  pp_details: "Nkọwa gị", pp_edit: "Dezie", pp_save: "Chekwaa", pp_cancel: "Kagbuo",
  pp_name: "Aha n'uju", pp_blood: "Ọbara", pp_allergies: "Ihe nfụkasị", pp_meds: "Ọgwụ ugbu a",
  pp_conditions: "Ọrịa na-adịte aka", pp_history: "Akụkọ ọgwụ", pp_imm: "Ịgba ọgwụ mgbochi", pp_hmo: "Nchekwa / HMO",
  pp_ec: "Onye kọntaktị mberede", pp_ecp: "Ekwentị mberede",
  pp_card: "Kaadị mberede", pp_card_d: "Gosi nke a nye onye ọrụ ahụike n'oge mberede.", pp_scan: "Gụọ ya na ngwa ndị ọrụ CareNBuddi",
  w_title: "Ọnọdụ Onye Ọrụ Ahụike", w_sub: "Nyocha, ndụmọdụ na nleso anya site n'ọgbọ.",
  w_events: "Ihe omume", w_participants: "A nyochara", w_referred: "A zigara", w_pending: "Nleso anya chọrọ",
  w_log: "Dee nyocha", w_add: "Tinye", w_recent: "Ndekọ na-adịbeghị anya", w_sync: "A na-echekwa n'ógbè ma na-ezipụ mgbe ị laghachiri n'ịntanetị.", w_days: "Lelee ụbọchị ahụike →",
  ask_title: "Jụọ CareNBuddi", ask_ph: "Jụọ maka ọnọdụ, inweta nlekọta, ọnụahịa…", ask_send: "Zipụ",
  f_cost: "Ọnụahịa", f_any_cost: "Ọnụahịa ọ bụla", f_low_cost: "₦ Dị ọnụ ala", f_mid_cost: "₦₦ Nkịtị", f_high_cost: "₦₦₦ Dị oke ọnụ ahịa",
  h_tagline: "Ozi Dị Mma. Ahụike Gị Ka Mma.",
  e_report_reason: "Ọktokpọ ziri ezi ma ọ bụ nsogbu nchekwa",
  f_location: "Ebe",
  f_category: "Ụdị",
  f_all_states: "Steeti nile",
  f_facility_one: "ụlọọgwụ",
  f_facility_many: "ụlọọgwụ",
  f_book_sent: "Ezigala arịrịọ. Ụlọọgwụ ahụ ga-akpọtụrụ gị.",
  f_form_msg: "Ozi",
  f_form_date: "Ụbọchị a họọrọ",
  f_emergency: "A na-enwe ọrụ mberede awa 24 n'ụlọọgwụ a.",
  f_provider_visit: "Nleta onye nye ọrụ",
  s_we_provide: "Ọrụ ahụike anyị na-enye",
  s_check_head: "Lelee Ahụike M",
  s_open_health: "Mepee ibe ahụike m",
  s_intro: "Rịọ ọrụ nyocha, njikwa obodo, ahụike ma ọ bụ nleta ụlọọgwụ mkpanaka maka onwe gị, ezinụlọ gị, ọrụ gị ma ọ bụ obodo gị. Ọ dịghị ego achọrọ iji rịọ — otu onye ga-akwado nkọwa site na ekwentị.",
  s_form_head: "Rịọ ọrụ ma ọ bụ nleta",
  s_service: "Ọrụ",
  s_date: "Ụbọchị a họọrọ",
  s_area: "Mpaghara / obodo / ebe ọrụ",
  s_submit: "Rịọ ọrụ",
  s_free_note: "Ọ dịghị ego achọrọ iji rịọ. Otu onye ga-akwado ikike, ọnụahịa na nkọwa site na ekwentị.",
  s_book_another: "Tụgharịa nleta ọzọ",
  s_on_date: " na ",
  s_success: "Daalụ {name}! Onye otu CareNBuddi ga-akpọtụrụ {phone} iji kwado nleta {service} gị{date}. Anyị na-akwado nkenke ọnụ ọgụgụ site na ekwentị na ihe ederede.",
  sc_bp: "Ọbara mgbali elu",
  sc_bp_d: "Nyocha BP dị mfe ma soro ntụziaka mfe.",
  sc_glu: "Glucose ọbara",
  sc_glu_d: "Nyocha glucose na ndụmọdụ ndụ.",
  sc_well: "Nlele ahụike zuru oke",
  sc_well_d: "Nleta nkịtị nke vitals na nlele ahụike zuru oke.",
  srv_education: "Mmụta ahụike",
  srv_education_d: "Oge ihe mmụta dị mfe gbasara mgbochi na omume dị mma.",
  srv_outreach: "Njikwa obodo",
  srv_outreach_d: "Ihe omume nyocha na ịkpa amata n'obodo gị.",
  srv_corporate: "Ahụike ụlọ ọrụ",
  srv_corporate_d: "Ụbọchị ahụike ụlọ ọrụ maka otu na òtù.",
  srv_mobile: "Nleta ụlọọgwụ mkpanaka",
  srv_mobile_d: "Nyocha, njikwa na ọrụ ahụike ebe ị nọ.",
  srv_referral: "Ọrụ iziga onye",
  srv_referral_d: "Njikọ a na-eduzi gaa na onye nye ọrụ kwesịrị ekwesị.",
  srv_campaigns: "Ihe omume ahụike",
  srv_campaigns_d: "Ụbọchị nyocha obodo dịka “Mara Nọmba Gị”.",
  em_call: "Kpọ nọmba mberede ozugbo",
  em_call_d: "Maka amaghị onye, mgbu obi, nsogbu iku ume, oke ọbara ọnwụ, ọkụ ọkụ, ihe ịrịba ama ọrịa strok, ma ọ bụ nsogbu ọ bụla — emela chere ma ghara ịdabere na ngwa a.",
  em_while: "Mgbe ị na-echere enyemaka ọrụaka",
  em_s1: "Debe onwe gị na onye ahụ n'udo — ekwela ịmegharị ha ma ọ bụrụ na ha nọ n'ihe ize ndụ.",
  em_s2: "Ọ bụrụ na amaghị onye mana ọ na-eku ume, tinye ha n'ọnọdụ mgbake.",
  em_s3: "Maka ọkụ ọkụ, wụsa mmiri ọkpọkọ dị jụụ n'elu ya ma ọ dịkarịa ala nkeji 20 — ejila ice, bọta ma ọ bụ ntụ ntụ.",
  em_s4: "Maka ọbara ọnwụ, pịa ọnya ahụ ike na mpempe akwa dị ọcha.",
  em_s5: "Maka ihe ịrịba ama ọrịa strok (ihu na-ala azụ, ogwe aka na-adịghị ike, okwu na-emeghachi), rute nlekọta mberede ngwa ngwa.",
  em_find_care: "Chọọ nlekọta dị mberede",
  em_find_d: "Maka nlekọta na-adịghị ize ndụ ndụ, chọta ụlọọgwụ na-enye ohere mberede nso gị.",
  em_find_hospital: "Chọọ ụlọọgwụ",
  em_find_clinic: "Chọọ ụlọọgwụ",
  em_footer: "Na mberede ahụike, kpọtụrụ nlekọta mberede ụzọ. CareNBuddi bụ maka mmụta na nduzi naanị.",
  hh_know: "Mara nọmba gị",
  hh_open: "Mepee",
  hh_know_d: "Malite Ụbọchị Ahụike Obodo CareNBuddi ma ọ bụ tụgharịa nleta ụlọọgwụ mkpanaka iji lelee ọbara mgbali elu gị na glucose site na nlekọta ọrụaka.",
  n_passport: "Paspọtụ",
  n_ask: "Jụọ",
  a_code_sent: "Ezigala imel ọpụrụiche — lelee koodu dị n'okpuru.",
  a_email_required: "Tinye imel mbụ.",
  a_code_mismatch: "Koodu ahụ dakọtara. Lelee ma nwaa ọzọ.",
  a_demo_mode: "ọnọdụ ọpụrụiche a na-egosi koodu kama iziga imel.",
  a_demo_note: "Ebe ndị nye ọrụ na admin ka edobere n'akụkụ ọrụ na njikọ igbe.",
  a_email_ph: "gị@ọmụmaatụ.com",
  a_member_default: "Otu onye CareNBuddi",
  pv_confirm_done: "Kwado",
  pv_guard: "Ebe a bụ maka ndị nye ọrụ ahụike e nyochara. Banye site na akaụntụ onye nye ọrụ ma ọ bụ admin iji gaa n'ihu.",
  pv_services_label: "Ọrụ (kewaa site na kọma)",
  pv_about: "Gbasara ụlọọgwụ a",
  pv_no_message: "Enweghị ozi",
  prg_lead: "Ndị nye ọrụ na-edebanye aha otu ugboro; ndị otu CareNBuddi na-enyocha ụlọọgwụ ọ bụla tupu ha pụta na Chọọ Nlekọta dịka onye nye ọrụ nyochara.",
  prg_facility: "Aha ụlọọgwụ",
  prg_category: "Ụdị",
  prg_state: "Steeti",
  prg_lga: "LGA / mpaghara",
  prg_address: "Adreesi",
  prg_submit: "Nyefee maka nnyocha",
  prg_note: "Nnyocha na-echebe obodo: naanị ndị nye ọrụ nyochara ka a na-egosi kaa ✓ na Chọọ Nlekọta.",
  prg_success_1: "Ezigala {facility} maka nnyocha.",
  prg_success_2: "Ị ga-enwe ike ijikwa arịrịọ na profaịlụ gị site na ọdụ onye nye ọrụ ozugbo e nyere ya nkwenye.",
  ad_signin_req: "Ebe a ka ndị otu CareNBuddi ka ejidere. Jiri akaụntụ ọpụrụiche admin iji hụ njikwa ọdịnaya, nnyocha, ndị ọrụ, nyocha na akụkọ.",
  ad_providers: "Ndị nye ọrụ",
  ad_verified_p: "Ndị nye ọrụ nyochara",
  ad_topics: "Isiokwu",
  ad_verify_pending: "Nnyocha ndị na-echere",
  ad_bookings: "Nhọpụta",
  ad_reports_open: "Akụkọ ndị meghere",
  ad_c_add: "Tinye isiokwu (draft)",
  ad_c_slug: "slug",
  ad_c_title: "Aha",
  ad_c_summary: "Nchịkọta",
  ad_c_category: "Ụdị",
  ad_c_add_draft: "Tinye draft",
  ad_c_publish: "Bipụta",
  ad_c_unpublish: "Kwụsị ibipụta",
  ad_c_delete: "Hichapụ",
  ad_c_required: "Achọrọ slug na aha.",
  ad_c_draft_note: "Draft — tinye nchịkọta tupu ibipụta.",
  ad_c_empty_summary: "Na-abịa n'oge na-adịghị anya.",
  ad_c_exists: "Isiokwu nwere slug a dịlarị.",
  ad_c_created: "Emepụtala draft — bipụta site na ndepụta dị n'okpuru.",
  ad_v_none: "Enweghị arịrịọ ndebanye aha.",
  ad_v_verify: "Nyochaa & bipụta",
  ad_v_reject: "Jụ",
  ad_v_approved_desc: "CareNBuddi nyochara nke a mgbe okwu akwụkwọ.",
  ad_u_name: "Aha",
  ad_u_email: "Email",
  ad_u_role: "Ọrụ",
  ad_u_joined: "Sonye",
  ad_a_cat: "Ndị nye ọrụ site n'ụdị",
  ad_a_state: "Ndị nye ọrụ site n'ụdị steeti",
  ad_a_bookings: "Arịrịọ nhọpụta — ụbọchị 14 gara aga",
  ad_a_requests: "Arịrịọ",
  ad_a_pipeline: "Nhazi ndebanye aha:",
  ad_a_submitted: "e nyefere",
  ad_a_approved: "akwadoro",
  ad_a_pending0: "na-eche",
  ad_r_none: "Enweghị akụkọ.",
  ad_r_resolve: "Mee ngwọta",
  pr_requests: "Arịrịọ m",
  pr_no_requests: "Enweghị arịrịọ nhọpụta ọ bụla.",
  pr_get_started: "iji malite.",
  pr_provider: "Nleta onye nye ọrụ",
  pr_appt: "Nhọpụta",
  pr_appt_d: "Nleta na arịrịọ na-abịa ga-apụta ebe a.",
  pr_rem: "Ihe ncheta",
  pr_rem_d: "Ezitela ihe ncheta ọgwụ na nyocha.",
  pr_saved: "Ndị nye ọrụ e chebere",
  pr_saved_d: "Samisịa ụlọọgwụ na ndị ọrụaka ị na-atụkwasị obi.",
  pr_records: "Ndekọ ahụike",
  pr_records_d: "Ndekọ na-apụta naanị ebe iwu kwetara.",
  prof_theme: "Ndabere",
  prof_theme_light: "Ọmụma",
  prof_theme_dark: "Ọkụchukwu",
  prof_govt_id: "Nọmba Mmadu Ọchịchị",
  prof_govt_id_d: "E ji ya mabiri na enweghị ọsọ banyere ọrụ ahụike na enweghị nsogbu.",
  prof_nin: "NIN (Nọmba Mmadu Ọchịchị Naa-egosipụta Ọnwe Ya)",
  prof_nin_hint: "Nọmba 11 iji egosipụta onye na onye",
  prof_bvn: "BVN (Nọmba Mmadu Ọchịchị Naa-egosipụta Akwụntụ)",
  prof_bvn_hint: "Nọmba 11 iji egosipụta ọgụgụ akwụntụ",
  prof_crop_title: "Chọọchọ ọkwa gị",
  prof_crop_save: "Cheta",
  prof_rotate: "Ríe",
  prof_reset: "Mezie",
  j_title: "Akwụkwọ akụkọ ahụike",
  j_sub: "Dee ọnọdụ gị, ihe mgbaàmà gị, na ihe dị mkpa nke vitals ụbọchị ọ bụla.",
  j_new: "Ntinye ọhụrụ",
  j_date: "Ụbọchị",
  j_mood: "Ọnọdụ",
  j_symptoms: "Ihe mgbaàmà",
  j_weight: "Arọ (kg)",
  j_heart: "Ọnụ obi (bpm)",
  j_sleep: "Ụra (hrs)",
  j_steps: "Nzọụkwụ",
  j_bp_sys: "BP kwesiri elu",
  j_bp_dia: "BP kwesiri ala",
  j_notes: "Ndetu",
  j_note_ph: "Kedu ka ụbọchị gị si gara?",
  j_save: "Chekwaa ntinye",
  j_empty: "Enweghị ntinye akụkọ akụkọ ọ bụla. Tinye nke mbụ gị.",
  j_collapse: "Dwụlikwuo",
  j_details: "Nkọwa",
  j_delete: "Hichapụ",
  r_title: "Ihe ncheta",
  r_sub: "Ọgwụ, mmiri, mmega ahụ, na nhọpụta.",
  r_new: "Ncheta ọhụrụ",
  r_title_field: "Aha",
  r_title_ph: "dịka. Ọgwụ mgbede",
  r_time: "Oge",
  r_type: "Ụdị",
  r_repeat: "Megharịa na",
  r_notes: "Ndetu",
  r_notes_ph: "Nkọwa nhọrọ…",
  r_add: "Tinye ncheta",
  r_today: "Taa",
  r_none_today: "Enweghị ihe edozi maka taa.",
  r_all: "Ncheta niile",
  r_none: "Enweghị ncheta ọ bụla. Tinye nke mbụ gị.",
  r_on: "Ọnụ",
  r_off: "Gbanyụọ",
  r_disable: "Gbanyụọ",
  r_enable: "Gbanye",
  r_delete: "Hichapụ",
  rc_title: "Ndekọ ahụike",
  rc_sub: "Debe ebe a na-ejikọ akụkọ nleta, akụkọ laabu, na ndenye ọgwụ.",
  rc_add: "Tinye ndekọ",
  rc_title_field: "Aha",
  rc_title_ph: "dịka. Nsonaazụ nnwale ọbara",
  rc_provider: "Onye nye ọrụ / ụlọọgwụ",
  rc_provider_ph: "dịka. Dr. Smith, Ụlọọgwụ Obodo",
  rc_date: "Ụbọchị",
  rc_category: "Ụdị",
  rc_summary: "Nchịkọta / nsonaazụ",
  rc_summary_ph: "Ọchọpụta ma ọ bụ nkuzi akwụkwọ…",
  rc_link: "Njikọ (nhọrọ)",
  rc_save: "Chekwaa ndekọ",
  rc_all: "Niile",
  rc_empty: "Enweghị ndekọ ebe a.",
  rc_delete: "Hichapụ",
  rc_open: "Mepee ndekọ ejiri njikọ",
  ex_back: "Laghachi Azụ na Ahụike M",
  ex_title: "Njem Mmega Ahụ & Arọ",
  ex_sub: "Debe ihe mgbaru ọsọ gị, dee omume gị kwa ụbọchị, ma lelee ọganihu gị. Data gị na-anọ na ngwaọrụ a.",
  ex_streak: "{n} ụbọchị usoro",
  ex_goal_1: "Ihe mgbaru ọsọ gị",
  ex_loss_goal: "Ihe mgbaru ọsọ mbelata arọ",
  ex_gain_goal: "Ihe mgbaru ọsọ ịba arọ",
  ex_goalfmt: " — site na {start} kg ruo {goal} kg ( ịdị elu {h} cm).",
  ex_height: "Ịdị elu (cm)",
  ex_start_w: "Arọ mmalite (kg)",
  ex_goal_w: "Arọ ihe mgbaru ọsọ (kg)",
  ex_save_goal: "Chekwaa ihe mgbaru ọsọ",
  ex_today_w_ph: "De ndekọ arọ taa (kg)",
  ex_record_w: "De ndekọ arọ",
  ex_warn: "Biko tinye ịdị elu, arọ mmalite na arọ ihe mgbaru ọsọ n'ime cm / kg.",
  ex_cur_w: "Arọ ugbu a",
  ex_lost: "Mbelata ruo ugbu a",
  ex_gained: "Ịbawanye ruo ugbu a",
  ex_to_goal: "gaa na ihe mgbaru ọsọ",
  ex_progress: "Ọganihu njem",
  ex_goal_x: "Ihe mgbaru ọsọ {g} kg",
  ex_week_active: "Na-arụ ọrụ n'izu a",
  ex_logged_today: "{n} e dekọtara taa",
  ex_weight_journey_2: "Njem arọ",
  ex_checkins: "{n} nyocha",
  ex_goal_label: "Ihe mgbaru ọsọ",
  ex_date: "Ụbọchị",
  ex_weight: "Arọ",
  ex_change: "Mgbanwe",
  ex_start: "mmalite",
  ex_train_3: "Ọzụzụ kwa ụbọchị",
  ex_done: "Mee taa",
  ex_not_done: "Emebeghị taa",
  ex_exercise: "Mmega ahụ",
  ex_minutes: "Nkeji",
  ex_note_opt: "Ndetu (nhọrọ)",
  ex_note_ph: "dịka. mmetụta ọma, oge mgbede",
  ex_log: "De ndekọ mmega ahụ",
  ex_remove: "Wepụ",
  ex_no_today: "Enweghị mmega ahụ e dekọtara taa. Họrọ mmega ahụ n'elu ma ọ bụ site na ọba akwụkwọ dị n'okpuru.",
  ex_reminder_4: "Ncheta mmega ahụ kwa ụbọchị",
  ex_rem_on: "Na-arụ ọrụ — emebere ncheta maka {time}.",
  ex_rem_off: "A gbanyụọ ncheta.",
  ex_rem_time: "Oge ncheta",
  ex_rem_note: "Ncheta mpaghara na-enyere gị aka idowe usoro kwa ụbọchị. A na-eme atụmatụ ịzipu ọkwa maka MVP dijitalụ.",
  ex_library_5: "Ọba akwụkwọ mmega ahụ",
  ex_library_d: "Foto na vidiyo njedebe dị iche iche nke mmega ahụ. Họrọ otu wee dekọọ ya ka mmega ahụ taa.",
  ex_hide: "Zoo",
  ex_howto: "Otu esi eme ya",
  ex_log_today: "De ndekọ taa",
  ex_media_1: "Iji tinye mgbasa ozi nke gị: tụba foto n'ime",
  ex_media_2: "na vidiyo n'ime",
  ex_media_3: "Ha na-apụta ozugbo.",
  hd_when: "Mgbe ị ga-achọ enyemaka ọrụaka",
  hd_what: "Kedu ihe ọ bụ",
  hd_symptoms: "Ihe mgbaàmà na ihe ịrịba ama",
  hd_risk: "Ihe ize ndụ",
  hd_prevention: "Mgbochi",
  hd_faqs: "Ajụjụ ndị a na-ajụkarị",
  hd_read_more: "Gụkwuo",
  hd_reviewed: "Kọmitii nyochara",
  hd_report: "Mkpesa",
  hd_source: "Isi mmalite:",
  hd_find_help: "Chọta Enyemaka Nso",
  sv_emergency: "Mberede",
  sv_hospitals: "Ụlọọgwụ",
  sv_phc: "Ụlọọgwụ mbụ",
  sv_labs: "Ụlọ nyocha",
  sv_pharmacies: "Ụlọogo ọgwụ",
  sv_professionals: "Ndị ọkachamara",
  count_results: "{n} onye nye ọrụ",
  lang: "Asụsụ Igbo",

  // Mobile app redesign: appointments, find care, health, profile, auth, onboarding.
  home_guest: "Ọbịa",
  home_overview: "Nlele ahụike",
  home_next_appt: "Nnọkọ ọzọ",
  home_no_appt: "Enweghị ọgbọ e debere",
  home_view: "Lelee",
  home_reminders: "Ihe ncheta",
  home_meds: "Ọgwụ",
  home_bp: "Ọbara mgbali elu",
  home_meds_due_1: "Ncheta ọgwụ 1 na-arụ ọrụ",
  home_meds_due_n: "ncheta ọgwụ na-arụ ọrụ",
  home_no_meds: "Enweghị ncheta ọgwụ",
  home_details: "Nkọwa",
  home_quick: "Ngwa ngwa",
  home_upcoming: "Ọgbọ nleta ọzọ",
  home_all: "Niile",
  home_no_appt_title: "Enweghị nnọkọ e deberecha",
  home_no_appt_d: "Chọta onye nye ọrụ ma debere aha site na ụfọdụ mgbị.",
  home_find_care: "Chọọ Nlekọta",
  home_nearby: "Ọrụ ahụike dị nso gị",
  home_see_all: "Lelee niile",
  home_tips: "Tuzi ahụike",
  home_emergency_d: "Buru ọbụla igbanyeghị ngwa. Kpọọ mbụ, mgbe ahụ jiri CareNBuddi.",
  home_call_112: "Kpọọ 112",
  home_passport_d: "Kaadị mberede gị na nchịkọta ahụike gị",
  hx_title: "Mmega ahụ & ahụike mma",
  home_wellness_d: "Nzọụkwụ, arọ na ụra",
  f_cost_low: "₦ Ọnụahịa dị ala",
  f_cost_high: "₦₦₦ Nke onwe ya",
  f_cost_mid: "₦₦ Ọtụtụ",

  appt_rescheduled: "A hazigharịa ọgbọ ahụ",
  appt_cancelled_toast: "A kagbuola ọgbọ ahụ",
  appt_title: "Nhọpụta",
  appt_sub: "Soro nleta gị ma rịọ oge ọzọ site na ụfọdụ mgbị.",
  appt_refresh: "Ịmelite nhọpụta",
  appt_next: "Nnọkọ ọzọ",
  appt_view_provider: "Lelee onye nye ọrụ",
  appt_reschedule: "Hazigharị oge",
  appt_reschedule_d: "Họrọ ụbọchị na oge ọzọ",
  appt_cancel_visit: "Kagbuo nleta a",
  appt_cancel_visit_d: "A ga-eme ka onye nye ọrụ",
  appt_none_title: "Enweghị nnọkọ e deberecha",
  appt_none_d: "Chọta onye nye ọrụ e nyere aka dị nso gị, rịọ nleta site na ụfọdụ mgbị.",
  appt_find_care: "Chọọ Nlekọta",
  appt_tab_upcoming: "Na-abịa",
  appt_tab_completed: "Emechara",
  appt_tab_cancelled: "Akagbuola",
  appt_need_sooner: "Ị chọrọ nlekọta ngwa?",
  appt_services: "Rịọ ọrụ ahụike",
  appt_services_d: "Nyocha, ahụike mma na nleta ụlọọgwụ mkpanaka",
  appt_emergency_d: "Nọmba mberede na nzọzi enyemaka mbụ",
  appt_confirm_time: "Kwado oge ọzọ",
  appt_current: "Ugbu a",
  appt_pick_date: "Họrọ ụbọchị",
  appt_pick_time: "Họrọ oge",
  appt_cancel_title: "Kagbuo nnọkọ a?",
  appt_cancel_body: "A ga-akagbu nnọkọ a. Ị nwere ike ịdebere ya ọzọ mgbe ọzọ.",
  appt_cancel_confirm: "Ee, kagbuo",
  appt_keep: "Jide ya",

  fc_sub: "Ụlọọgwụ, PHC, ụlọ nyocha, ụlọ ọgwụ na ndị ọkachamara — na oge kacha nso dị.",
  fc_refresh: "Ịmelite nsonaazụ",
  fc_clear_search: "Hụfụ ọchụchọ",
  fc_filters: "Nzọọ",
  fc_error_title: "Enweghị ike ịbufu nsonaazụ",
  fc_error_d: "Anyị enweghị ike ịgụ ndepụta ụlọọgwụ gị. Lọdọ ọzọ mgbe oge gasị.",
  fc_retry: "Lọdọ ọzọ",
  fc_empty_title: "A chọtaghị onye nye ọrụ",
  fc_empty_d: "Lọdọ okwu ọchụchọ ọzọ, ma ọ bụ hụfụ nzọọ gị ka ịhụ ihe niile.",
  fc_clear_filters: "Wepụ nzọọ niile",
  fc_choose_state: "Họrọ steeti",
  fc_reset: "Tọghata",
  fc_show_n: "Lelee nsonaazụ {n}",
  fc_name_req: "Banye aha zuru ezu",
  fc_phone_req: "Banye nọmba ekwentị",
  fc_missing_title: "A chọtaghị ụlọọgwụ ahụ",
  fc_missing_d: "Enweghị ụlọọgwụ a n'edebere ndepụta anyị. Chọpụta ụlọọgwụ anyị nwere dị nso.",
  fc_request_sent: "Ezigala arịrịọ nleta",
  fc_report_title: "Kpesa ụlọọgwụ a",
  fc_report_reason: "Kedu ihe na-ezighị ezi na ndepụta a?",
  fc_book_appointment: "Debanye nnọkọ",
  fc_whatsapp_d: "Jụọ ajụjụ na WhatsApp",
  fc_request_d: "Zị arịrịọ, ụlọọgwụ ahụ ga-akpọtụrụ gị iji hazị nleta.",
  fc_no_date: "Enweghị ụbọchị a họọrọ",

  hd_steady: "Dọbụla",
  hd_reminder_on: "Egbanyụọ ncheta",
  hd_reminder_off: "Agbanyụọla ncheta",
  hd_eyebrow: "Ahụike gị na-akpọ anya n'otu oge",
  hd_title: "Ahụike gị",
  hd_guest_title: "Banye ka ịkwe ndekọ ahụike gị",
  hd_guest_body: "Mgbe ị banyere, akwụkwọ ahụike gị, ndekọ gị na ihe ncheta gị ga-akpọrụ gị na ngwa niile.",
  hd_guest_cta: "Banye ma ọ bụ mepụta akaụntụ",
  hd_vitals: "Vitals",
  hd_vitals_sub: "Nyocha ọhụrụ gị",
  hd_log: "Ntinye",
  hd_wellness: "Ahụike mma",
  hd_wellness_sub: "Ụbọchị 7 gara aga",
  hd_open: "Mepee",
  hd_activity: "Ihe omume kwa ụbọchị",
  hd_min: "Nkeji",
  hd_weight_goal: "Ihe mgbaru ọsọ arọ",
  hd_no_weighin: "Enweghị arọ e kpalịrịla",
  hd_unit_kg: "kg",
  hd_steps: "Nzọụkwụ",
  hd_daily_avg: "Ọnụ ọgụgụ kwa ụbọchị",
  hd_steps_sub: "Kacha ọhụrụ",
  hd_meds: "Ọgwụ",
  hd_all: "Niile",
  hd_next_dose: "Oke ọgwụ ọzọ",
  hd_paused: "Ogheghe",
  hd_toggle_med: "Gbanwee ncheta ọgwụ",
  hd_active: "na-arụ ọrụ",
  hd_manage: "Jikwaa",
  hd_no_meds: "Enweghị ncheta ọgwụ",
  hd_no_meds_d: "Tinye otu ka ị ghara ịfọ oke ọgwụ ọ bụla",
  hd_add: "Tinye",
  hd_records: "Nsonaazụ nnwale na ndekọ",
  hd_view_all: "Lelee niile",
  hd_no_records: "Enweghị ndekọ",
  hd_add_record: "Tinye ndekọ",
  hd_passport: "Paspọtụ Ahụike",
  hd_passport_d: "Kaadị mberede gị na nchịkọta ahụike gị",
  hd_vaccines: "Ịgba ọgwụ mgbochi",
  hd_no_vaccines: "Enweghị ịgba ọgwụ mgbochi e debere",
  hd_no_vaccines_d: "Dee ịgba otu ọgwụ mgbochi ka ikwado akụkọ ịgba gị n'otu ebe.",
  hd_journey: "Njem ahụike",
  hd_journey_sub: "Nyocha ọhụrụ gị",
  hd_no_symptoms: "Enweghị ihe mgbaàmà e dekọtara",
  hd_no_journal: "Enweghị nyocha",
  hd_chronic: "Ọrịa na-adịte aka",
  hd_chronic_d: "Atụmatụ nlekọta ọbara mgbali elu, shugar na ụkwara aho",
  hd_support: "Ndị nlekọta na nkwado",

  prof_saved: "Emelitela profaịlụ",
  prof_emergency_saved: "Emelitela onye kọntaktị mberede",
  prof_sub: "Ozi gị, ọrụ gị na nzuzere gị n'otu ebe.",
  prof_signed_out_title: "Ị banyeghị",
  prof_signed_out_d: "Banye ka nhọpụta gị na ndekọ gị dọka ọtụtụ n'ebe ahụ, ma ọ bụ nọgide dị ka ọbịa.",
  gate_continue_guest: "Nọgide dị ka ọbịa",
  prof_photo_failed: "Anyị enweghị ike ịji ịfoto a. Họpọta nke ọzọ.",
  prof_photo_no_room: "Oziọ a ejiri ozi. Biko freespace ma ọọ bụ dọcha ịfoto.",
  prof_photo_remove: "Wegbu ịfoto",
  prof_photo_removed: "A Wegbu ịfoto",
  prof_photo_saved: "Emelitela ịfoto",
  prof_photo_too_large: "Ịfoto a ukwuu. Biko họpọta nke ntakịrị.",
  prof_change_photo: "Gbanwee ịfoto",
  prof_no_phone: "Enweghị ekwentị aha",
  prof_edit: "Dezie profaịlụ",
  prof_account_sync: "Akaụntụ & nchekwa",
  prof_emergency: "Onye kọntaktị mberede",
  prof_no_emergency: "Enweghị onye kọntaktị mberede",
  prof_no_emergency_d: "Tinye onye onye ọrụ enyemaka nwere ike ịkpọrụ maka gị",
  prof_call: "Kpọọ",
  prof_view_all: "Lelee niile",
  prof_bookings_1: "Arịrịọ nhọpụta 1",
  prof_bookings_n: "arịrịọ nhọpụta",
  prof_bookings_d: "Soro ọnọdụ nke nleta niile ị rịọrọ.",

  auth_phone_label: "Ekwentị (nhọrọ)",
  auth_phone_hint: "Ndị nye ọrụ na-eji ya iji kwado nleta",
  prof_phone_ph: "+234 ...",
  prof_email_fixed: "Enweghị ike ịgbanwe ozi-e ebe a",
  prof_emergency_ph: "dịka. Tayo Ogunleye (nwanne)",
  prof_emergency_note: "Nke a bụ nọmba a ga-akpọta na kaadị mberede Paspọtụ Ahụike gị.",
  auth_err_email_required: "Banye ozi-e gị.",
  auth_err_email_invalid: "Ozi-e ahụ adịghị ezi ọ dị.",
  auth_reset_offline: "Ịtọghata okwuntughe chọrọ akaụntụ CareNBuddi igwe. N'oge nlele anyị nwere ọdịnaya, a na-akpaghị ọkọkọ okwuntughe.",
  auth_reset_unconfigured: "Ebe a dịghị eme ka izi ozi. Jiri Akaụntụ & nchekwa iji gbuvie akụkọ akaụntụ gị.",
  auth_reset_sent: "Ezigala njikọ ịtọghata",
  auth_reset_failed: "Anyị enweghị ike izi ozi-e ahụ. Lọdọ ọzọ mgbe oge gasị.",
  auth_reset_title: "Tọghata okwuntughe gị",
  auth_reset_sub: "Banye ozi-e akaụntụ gị, anyị ga-eziga gị njikọ iji họrọ okwuntughe ọzọ.",
  auth_reset_sent_d: "Ọ bụrụ na ozi-e ahụ nwere akaụntụ, njikọ ịtọghata dọla n'oge na-adịghị anya.",
  auth_resend_in: "Na-eziga…",
  auth_reset_cta: "Ziga njikọ ịtọghata",
  auth_reset_cta_resend: "Ọzọ ziga njikọ ịtọghata",
  auth_back_signin: "Laghachi ịbanye",
  auth_back: "Laghachi na CareNBuddi",
  auth_home: "Ụlọ CareNBuddi",
  brand_name: "CareNBuddi",
  auth_err_password_required: "Banye okwuntughe gị.",
  auth_err_password_short: "Okwuntughe ga-atịkarị mkpụrụedemede 8.",
  auth_signin_no_account: "Enweghị akaụntụ offline ọ bụla na-eji ozi-e ahụ. Mepụta akaụntụ mbụ.",
  auth_signed_in: "Ị banyere",
  auth_signin_title: "Abanyela",
  auth_signin_sub: "Banye ka ịhụ nhọpụta gị, ndekọ gị na paspọtụ gị na ngwa a.",
  auth_password_ph: "••••••••",
  auth_password_hint: "Mkpụrụedemede 8 n'arị",
  auth_forgot: "Chegharịa okwuntughe?",
  auth_no_account: "Onye ọhụrụ na CareNBuddi?",
  auth_demo_link: "Na-akpọrị ka?",
  auth_err_name_required: "Banye aha zuru ezu.",
  auth_err_phone_invalid: "Banye nọmba ekwentị dị ezi, dịka. +234 800 000 0000.",
  auth_err_confirm_mismatch: "Okwuntughe abụọ adịghị otu.",
  auth_check_email: "Lelee ozi-e gị iji kwado akaụntụ gị",
  auth_account_created: "Emepụtala akaụntụ",
  auth_signup_failed: "Anyị enweghị ike imepụta akaụntụ ahụ.",
  auth_signup_title: "Mepụta akaụntụ gị",
  auth_signup_sub: "Otu akaụntụ ga-akpọ nhọpụta gị na ndekọ ahụike gị ọtụtụ. Ọ dịghị ọrụ — ị nwere ike ịchọpụta dị ka ọbịa.",
  auth_role_patient: "Ọrịa",
  auth_confirm_label: "Kwado okwuntughe",
  auth_creating: "Na-eme…",
  auth_have_account: "Ị nwere akaụntụ?",
  auth_verify_no_email: "Anyị bụ dịghị ọzọ nke ozi-e a ga-akwado.",
  auth_confirmed: "Emelitela ozi-e",
  auth_verify_short: "Banye koodu mkpụrụedemede 6 dị na ozi-e gị.",
  auth_verify_failed: "Koodu ahụ araghị ọrụ.",
  auth_resent_demo: "N'oge nlele anyị nwere ọdịnaya, a na-ezighị koodu ọ bụla.",
  auth_resent: "Ezigala koodu ọzọ. Lelee n'igbe ozi gị.",
  auth_resend_failed: "Anyị enweghị ike ịzigharị koodu.",
  auth_verify_title: "Kwado ozi-e gị",
  auth_verify_sub: "Ezigala njikọ kwado na koodu mkpụrụedemede 6 na igbe ozi gị. Mepee njikọ ahụ, ma ọ bụ pụta koodu dị n'okpuru.",
  auth_verify_sub_off: "N'oge nlele anyị nwere ọdịnaya, a na-ezighị ozi-e ọ bụla. Gaa n'ihu mgbe ị dị njere.",
  auth_email_label: "Ozi-e",
  auth_code_label: "Koodu kwado",
  auth_resend: "Zigharị koodu",
  auth_verify_hint: "Emelitela? Banye jiji ozi-e na okwuntughe gị.",
  auth_verify_continue: "Gaa n'ihu na CareNBuddi",
  gate_signin_title: "Banye ka ịga n'ihu",
  gate_signin_body: "Oke a na-echere ozi ahụike nke onwe gị. Banye ka ịhụ ndekọ gị.",
  gate_signin_cta: "Banye",
  gate_staff_title: "N'ihi ndị ọrụ naanị",
  gate_staff_body: "Ebe a bụ maka ndị nye ọrụ ahụike CareNBuddi na ndị ọrụ ya.",
  gate_back_profile: "Laghachi na profaịlụ",

  appt_cancelled_note: "Akagbuola nnọkọ a.",
  appt_book_again: "Debere ọzọ",
  appt_cancel: "Kagbuo",
  booking_done: "Deberechara nnọkọ",
  fc_book_title: "Debanye nnọkọ",
  fc_confirm_booking: "Kwado ndebanye",
  fc_visit_type: "Ụdị nleta",
  fc_pick_date: "Họrọ ụbọchị",
  fc_pick_time: "Họrọ oge",
  fc_notes: "Ndetu (nhọrọ)",
  fc_notes_ph: "Ihe ọ bụla onye nye ọrụ kwesịrị ịmaka tupu nleta gị…",
  fc_book_note: "Ị nwere ike itọghata oge ma ọ bụ kagbuo ya na nchekọta Nhọpụta gị.",

  onb_skip: "Gbaghara",
  onb_step_word: "Nzọọ",
  onb_step_1: "Nzọọ 1 n'ụbọchị 3",
  onb_step_2: "Nzọọ 2 n'ụbọchị 3",
  onb_step_3: "Nzọọ 3 n'ụbọchị 3",
  onb_back: "Laghachi azụ",
  onb_start: "Bido",
  onb_next: "Ọzọ",

  prof_signed_out: "Ị pụọla",
  prof_health_prefs: "Mmasị ahụike",
  prof_units: "Ubu",
  prof_units_d: "Otu e si arọ, ịdị elu na okpompe na-apụta",
  prof_units_metric: "Metric (kg)",
  prof_units_imperial: "Imperial (lb)",
  prof_hmo_empty: "Aba esighị — debere ya na Paspọtụ Ahụike gị",
  prof_notifications: "Nchọpụta",
  prof_notif_appt: "Nchọpụta nnọkọ",
  prof_notif_appt_d: "Nchọpụta tupu nleta ọ bụla e debere",
  prof_notif_meds: "Nchọpụta ọgwụ",
  prof_notif_meds_d: "Ịọgụ ihe ncheta ị gbanwee",
  prof_notif_tips: "Tuzi ahụike",
  prof_notif_tips_d: "Tuzi mgbochi na nyocha oge ụfọdụ",
  prof_privacy: "Nzuzere na nchekwa",
  prof_account_sync_d: "Chekwala ndekọ gị ma jikwaa akaụntụ igwe",
  prof_privacy_notice: "Ọgbọ nzuzere",
  prof_privacy_notice_d: "Ihe niile dị na ngwaọ a na ihe na-akpọọta",
  prof_change_password: "Gbanwee okwuntughe",
  prof_change_password_d: "Anyị ga-eziga gị njikọ ịtọghata dọkọ",
  prof_help: "Enyemaka na nkwado",
  prof_contact_support: "Kpọtụrụ nkwado",
  prof_support_email: "support@healthlink.ng",
  prof_find_d: "Chọọ ndị nye ọrụ na ụlọọgwụ dị nso gị",
  prof_signout_d: "Ndekọ gị e chebere ga-abanye na ngwaọ a",
  prof_privacy_local_title: "A na-echekwa na ngwaọ a",
  prof_privacy_local_d: "N'akụkọ ọdịnaya, ihe ọ bụla ị na-akpọta — nhọpụta, akwụkwọ ahụike, ndekọ, paspọtụ, mmasị gị na ịfoto profaịlụ gị — a na-akpụta na nchekwa nke oge a n'ime onye naanị. A na-agaghị ewera ya.",
  prof_privacy_cloud_title: "Nchekwa igwe naanị ma ị jiri akaụntụ",
  prof_privacy_cloud_d: "Mgbe a jiri akaụntụ CareNBuddi igwe, ndekọ gị na-echekwa n'ụzọ nzuzere ma na-akpọọta, ka ị ga-akpo ọrụ ngwaọ dị ọzọ. Mepee Akaụntụ & nchekwa iji jikọ ma ọ bụ wepụ akaụntụ.",
  prof_privacy_share_title: "Ihe ndị nye ọrụ na-ahụ",
  prof_privacy_share_d: "Onye nye ọrụ na-ahụ naanị aha na ekwentị ị na-enye mgbe ị rịọ nleta, yana ihe ị họrọ ịgosi site na Paspọtụ Ahụike gị.",
  prof_signout_title: "Pụọ na CareNBuddi?",
  prof_signout_body: "Ndekọ gị e chebere ga-abanye na ngwaọ a. Ị nwere ike ịbanye ọzọ mgbe ọ bụla.",

  fc_slots_call: "Kpọọ maka oge dị",
  fc_next_slot: "Kacha nso dị",
  fc_book: "Debere",
  fc_details: "Nkọwa",
  appt_empty_upcoming: "Enweghị ọgbọ na-abịa",
  appt_empty_upcoming_d: "Debere nleta onye nye ọrụ e nyere aka site na ụfọdụ mgbị.",
  appt_empty_completed: "Enweghị nleta ọ bụla gara aga",
  appt_empty_completed_d: "Nhọpụta ga-akpọ n'ebe a mgbe ụbọchị nleta ahụ gasịrị.",
  appt_empty_cancelled: "A kagbuola ihe ọ bụla",
  appt_empty_cancelled_d: "Nleta ị kagbuola ga-apụta ebe a, ya na ndị ọzọ n'akụkọ gị.",
  hx_sub: "Kpọrọ ihe ọzọ, nwee mma",

  n_appts: "Nhọpụta",
  n_care: "Chọọ Nlekọta",
  n_my_health: "Ahụike m",
  n_staff: "Ngwa ndị ọrụ",
  n_more: "Ọzọ",
  n_notifications: "Nchọpụta",
  n_main_nav: "Ndinụta ukwu",
  ad_v_approved_toast: "Ekwuọla akụkọ ego emeela",
  ad_v_none_d: "Ndị nkọọ ị debanye aha na-akpọta ebe a ka anya chọpụta.",
  ad_r_empty: "Enweghi mkpọchi",
  ad_r_empty_d: "Mkpọchi ndị obodo ga-apụta ebe a ka anya lelee.",
  askx_greeting: "Ndewo! M bụ Ask CareNBuddi. Enwere m ike ịkọ nkọziaka ahụaka na ịji ngwa ahụ dị mma — ọ bụghị dọktọ ọ bụla. Kedu ihe ị chọrọ ịmọta?",
  askx_disclaimer: "Ozi akụkụ akụkụka dị ọtụtụtụ — ọ naghị dochie ọgbụ ọgwụ onye ọrụ ụdọ akụkụaka dọktọ.",
  askx_emergency_hint: "Oke mmadụ? Kpọ 112 site na \"Nwoke Nchọọta Ugbu a\".",
  emx_national: "Oke mmadụ mba: 112",
  chx_title: "Onye Nwanyị Na-anahụ Ogbu Ogbu",
  chx_sub: "Nchedo kwa ụbọchị na nchọpụta kwa ọnwa gbasara ọrụ daba n'ime gị.",
  chx_today: "Ọnụma ọzọ",
  chx_month: "Ọnwa ọzọ",
  chx_bp_logged: "Akpọtụrụ ọnụọ BP",
  chx_entries_logged: "nkụtakụ aka akpọtụrụ",
  chx_latest: "Nke ọzọnụma",
  chx_care: "Nlekọta",
  chx_find: "Chọta ọkwuo dị gịnị gịnị n'akụkụ gị",
  chx_reminder_set: "E setịla nkọwa maka nke a",
  chx_remind: "Cheta m",
  exx_warn: "Biko tinye nke obodo, mbụ nnọọ mbụ mgbe mkemwe na-akụkọ oke (cm / kg).",
  exx_goal_saved: "Ekezitere mgbe mkemwe",
  exx_weight_saved: "Echekara nnọọ",
  exx_workout_logged: "Echekara ọzọ nnọọ",
  h_dashboard: "Ahụmike M",
  ex_not_yet: "Ọ bụghị onye emesịrị taa",
  ex_current: "Nnọọ ugbu a",
  ex_week: "Na-arọ ọrụ na-adịghị ọtụtụ ọzọ",
  ex_today: "taa",
  ex_bmi: "BMI",
  ex_goal: "Mgbe mkemwe",
  ex_set_goal: "Debe ebe mgbe mkemwe gị",
  ex_journey: "Ụgbọ aka nnọọ gị",
  exx_no_weighins: "Enweghi ọnụọ edekwara taa.",
  exx_ph_weight: "Nnọọ taa (kg)",
  ex_record: "Echekara",
  ex_reminder: "Nkọwa ọzọ nnọọ kwa ụbọchị",
  ex_active: "Na-arọ ọrụ",
  ex_at: "e mere maka",
  ex_off: "Agbanyeghị nkọwa ahụ.",
  ex_time: "Oge nkọwa",
  ex_reminder_note: "Nkọwa nke gị na-enyere gị ka ị nọọrọ oge kwa ụbọchị. E ga-arị ịzụ ozi na MVP dijital.",
  ex_library: "Ụlọọọka exercises",
  ex_how: "Otu esi eme ya",
  ex_save: "Cheke mgbe mkemwe",
  ex_from: "site na",
  ex_to: "ruo na",
  exx_f_height: "Nke obodo (cm)",
  exx_f_start: "Nnọọ mmalite (kg)",
  exx_f_goal: "Nnọọ mgbe mkemwe (kg)",
  ex_add: "Debe ọzọ nnọọ",
  exx_f_exercise: "Exercise",
  exx_f_minutes: "Nkeji",
  exx_f_note: "Ndetu (na-eme ghị)",
  exx_ph_note: "atụle: nnọọ kpakpaku",
  ex_today_logged: "Echekara taa",
  exx_none_today: "Enweghi exercise echekara taa. Họọrọ ọzọ nnọọ dị n'okpuru ma ọ bụ site na ụlọọka.",
  exx_nice: "Ọrụ ọma taa",
  exx_nice_d: "Laghachi ụtọdị echi ka ị gaa n'ihu na-agbanyeghị.",
  jyx_journal: "Nchakọta ahụka",
  jyx_mood: "Nnọọ emesịrị",
  jyx_request: "Mgbọọ ahụka ọdịbụ",
  jyx_screening: "Nchọpụta ọrụ obodo",
  jyx_screening_d: "Ihe omume \"Ọ Bụla Ihe Ụdịnaya Gị\"",
  jyx_referred: "A zigara maka ọkwụa naanị (PHC)",
  jyx_referred_d: "E nyere ọnụọ BP ọdị n'oge nchọpụta",
  jyx_empty: "Oge nhọọ gị dị efu",
  jyx_empty_d: "Akụkụ nchakọta, nkọwa na arịọarịa ọdịbụ ga-apụta ebe a ọ bụrụ na ị chọọpụta ha.",
  jyx_legend_records: "Nkpọta",
  jyx_legend_care: "Nlekọta",
  jyx_legend_requests: "Arịọarịa",
  hdx_created: "E kere ụbọchị ahụka",
  hdx_screened: "A chọpụta",
  hdx_referred: "A zigara",
  hdx_followup_due: "Nchọpụta mgbe ebe a na-achọ",
  hdx_followed: "A chọọla ya",
  hdx_empty: "Enweghi ụbọchị ahụka ọzọ",
  hdx_empty_d: "Mee mmọọ ihe omume ka anya nchọpụta na zigara ya.",
  jr_saved: "Echekara nkụta",
  jr_deleted: "Ehichala nkụta ahụ",
  jr_title_page: "Nchakọta ahụka",
  jr_sub_page: "Debe nọọ emesịrị gị, ihe otu ọrọ na ọnụọ ahụka gị kwa ụbọchị.",
  jr_add_entry: "Tinye nkụta",
  jr_empty_title: "Enweghi nkụta nchakọta ọzọ",
  jr_empty_body: "Bụa ịzụ ahụka gị site na ịtinye nkụta mbụ gị taa.",
  jr_edit: "Dezie",
  jr_delete: "Hapụ",
  jr_edit_entry: "Dezie nkụta",
  jr_form_new: "Nkụta ọhụrụ",
  jr_save: "Cheke nkụta",
  jr_date: "Ọnụma",
  jr_mood: "Nnọọ emesịrị",
  jr_symptoms: "Ihe otu ọrọ",
  jr_vitals_weight: "Nnọọ (kg)",
  jr_vitals_heart: "Ịsụ ọbụna (bpm)",
  jr_vitals_sleep: "Ịsụn (oge)",
  jr_vitals_steps: "Ubu ọzọ",
  jr_vitals_bp_sys: "BP nke ukwu",
  jr_vitals_bp_dia: "BP nke nso",
  jr_notes: "Ndetu",
  jr_note_ph: "Olee ọzọ rọ gị?",
  jr_delete_confirm_title: "Hapụ nkụta nchakọta?",
  jr_delete_confirm_body: "A ga-ehichala nkụta a ruo kwa ọtụtụ.",
  jr_confirm_delete: "Eee, hapụ",
  jr_cancel: "Kansela",
  pvx_staff_only: "N'aha naanị ndị ọrụ ọgwụ ụdọ ọdịbụ",
  pv_pending_d: "Anyị na-e anya ụbọchị ọ bụla tupu onye na-eme portal ahụ akpọghị.",
  pvx_no_requests: "Arịọarịa ndị ọrọ ọdịbụ n'akụkọ ego gị ga-apụta ebe a.",
  pvx_register_d: "Melite ma ọ bụ nyụta ebe ọzọ",
  pvx_ph_name: "atụle: Dr. Ngozi Eze",
  pvx_ph_lga: "atụle: Abeokuta South",
  rc2_saved: "Cheke nkọwa",
  rc2_removed: "Ehichala nkọwa",
  rc2_title: "Nkpọta aka ọrụ ọdịbụ",
  rc2_sub: "Nwee ebe nchekwa ihe ịhụrụ, nnyocha na ọkwu ọgwụ ụdọ ọdịbụ dị ọnọdụ.",
  rc2_add: "Tinye nkọwa",
  rc2_filter_all: "Gịnị niile",
  rc2_empty_title: "Enweghi nkọwa ebe a ọzọ",
  rc2_empty_body: "Tinye ọhụrụ, nchọpụta nnyocha ma ọ bụ onyinye egbema ọrị ị gị aka ibere.",
  rc2_delete: "Hapụ nkọwa",
  rc2_open: "Meghee nkọwa ejiri aka",
  rc2_add_title: "Tinye nkọwa",
  rc2_save: "Cheke nkọwa",
  rc2_f_title: "Aha",
  rc2_f_ph_title: "atụle: nchọpụta nnya ọbara",
  rc2_f_provider: "Ndị ọrụ ọgwụ ụdọ / ebe ahụka",
  rc2_f_ph_provider: "atụle: Dr. Smith, Ọkwụa Ihe Ụdịnaya",
  rc2_f_date: "Ọnụma",
  rc2_f_category: "Ụdị",
  rc2_f_summary: "Nchọkọta / nsona",
  rc2_f_summary_ph: "Nchọpụta ndị kọwa ahụ ma ọ bụ ndetu…",
  rc2_f_link: "Njikọ (na-eme ghị)",
  rc2_confirm_title: "Hapụ nkọwa a?",
  rc2_confirm_body: "Enweghi ọzọ mere ya.",
  rc2_confirm_yes: "Eee, hapụ",
  rc2_confirm_no: "Jide ya",
  rm2_saved: "E tinyere nkọwa",
  rm2_removed: "Ehichala nkọwa",
  rm2_on: "Nọọ ọrụ",
  rm2_off: "Kwụrụ",
  rm2_delete: "Hapụ nkọwa",
  rm2_title: "Ndetu",
  rm2_sub: "Ọgwụ ọdịbụ, mmiri, ọzọ na nnọkọ ịhụrụ.",
  rm2_add: "Tinye nkọwa",
  rm2_today: "Ọnụma ọzọ",
  rm2_empty_today: "Enweghi ihe a na-atụ anya taa",
  rm2_empty_today_d: "Nkọwa gị maka ọzọ a ga-apụta ebe a.",
  rm2_all: "Nkọwa niile",
  rm2_empty_all: "Enweghi nkọwa ọzọ",
  rm2_empty_all_d: "Tinye nkọwa gị mbụ ka ịhụụ dose ma ọ bụ ọhụrụ ọ bụla.",
  rm2_sheet_title: "Nkọwa ọhụrụ",
  rm2_save: "Tinye nkọwa",
  rm2_f_title: "Aha",
  rm2_ph_title: "atụle: ọgwụọ nchi ozi",
  rm2_f_time: "Oge",
  rm2_f_type: "Ụdị",
  rm2_f_days: "Meghee na",
  rm2_f_notes: "Ndetu",
  rm2_ph_notes: "Nkọwa ọzọ (na-eme ghị)…",
  rm2_confirm_title: "Hapụ nkọwa a?",
  rm2_confirm_body: "Enweghi ọzọ mere ya.",
  rm2_confirm_yes: "Eee, hapụ",
  rm2_confirm_no: "Jide ya",
  wkr_saved: "Echekara nchọpụta",
  wkr_online: "N'ịntanetị — ejikọta",
  wkr_offline: "Enweghi ịntanetị — mgbanwe na-echere",
  wkr_empty: "Enweghi nchọpụta echekara",
  wkr_empty_d: "Debe nchọpụta mgbe mmọọ oge mmadụ gasịrị ihe omume ahụ bụrụ na nchọpụta ikpeazụ agaghị efunahụ.",
  wkr_f_date: "Ọnụma",
  wkr_f_type: "Ụdị",
  wkr_f_participants: "Ndị na-abụ",
  wkr_f_referred: "A zigara",
  wkr_f_notes: "Ndetu",
  jr_mood_great: "Ọma ọtụtụ",
  jr_mood_good: "Ọma",
  jr_mood_okay: "Ọ dị ọma",
  jr_mood_low: "Nwala ala",
  jr_mood_poor: "Njọ ọma ọ dịghị",
  jr_mood_unknown: "Nnọọ emesịrị",
  jr_symptom_headache: "Ihu ọwụ isi",
  jr_symptom_nausea: "Ọgbụ ọgbụ",
  jr_symptom_fatigue: "Ọkpụmkụ",
  jr_symptom_cough: "Ụkwụsa",
  jr_symptom_fever: "Okwu ọtụtụ",
  jr_symptom_dizziness: "Isi ọ dịghị",
  jr_symptom_sore_throat: "Onye ọgbụ ọdị ọmụ",
  jr_symptom_stomach: "Afụ",
  jr_symptom_back: "Azụ",
  jr_symptom_allergy: "Nchọpụta oke",
  jr_symptom_other: "Ọzọ",
  rc2_cat_visit: "Ọhụrụ",
  rc2_cat_lab: "Nchọpụta ọlaboratory",
  rc2_cat_imaging: "Nkpọta iheonye",
  rc2_cat_prescription: "Ọgụọgụ ọgwụ",
  rc2_cat_vaccination: "Onyinye ọgbụ ọdị",
  a_enter_email: "Biko tinye ozi-e-mail ozugbo.",
  cc2_added: "Ezigara ọtọ ọgụ ọgụ nlekọta",
  cc2_removed: "Aka ewepụta",
  cc2_empty: "Enweghi onye ọ bụla banyere ọzọ",
  cc2_empty_d: "Tinye ndị ị na-nlekọta ka ibe aka nọọ ahụka ha dị nso.",
  pp_saved: "Ezigara pasport",
  pp_none: "E debeghị",
  s_on: "n'Ọnụma",
  s_ph_name: "atụle: Amina Yusuf",
  s_ph_area: "atụle: Ikeja, Lagos",
};
