import type { Dict } from "../i18n";

export const yoDict: Dict = {
    n_home: "Ile", n_explore: "Ṣàwárí", n_find: "Wá Ìtọ́jú", n_services: "Àwọn Iṣẹ́",
    n_health: "Ìlera", n_profile: "Àkọọ́lẹ̀", n_provider: "Olùpèsè", n_admin: "Ìdarí", n_account: "Àkọọ́lẹ̀ mi",
    h_title: "Kí ni a lè ṣe fún ọ lónìí?",
    h_sub: "Kọ́ nípa ìlera rẹ, ṣàyẹ̀wò ara rẹ, wá ìtọ́jú tó yẹ, kí o sì dara pọ̀ mọ́ àwọn olùpèsè ìtọ́jú.",
    h_learn: "Kọ́ nípa ìlera", h_learn_d: "Àwọn àpilẹ̀kọ tó yéni nípa àrùn àti ìdènà.",
    h_check: "Ṣàyẹ̀wò ìlera rẹ", h_check_d: "Ìgbeyẹ̀wò, ilé-ìwòsàn àti àkọọ́lẹ̀ ìlera rẹ.",
    h_find: "Wá ìtọ́jú nítòsí ọ", h_find_d: "Ilé-ìwòsàn, PHC, ilé-awakọ̀, oògùn àti òjògbón ní ìpínlẹ̀ rẹ.",
    h_connect: "Dara pọ̀ mọ́ olùpèsè ìtọ́jú", h_connect_d: "Kàn sí àwọn olùpèsè tààrà láti wálẹ̀ẹ́ tàbí béèrè ìbẹ̀wò.",
    h_search: "Wá àwọn kókó ìlera, àrùn, tàbí iṣẹ́…",
    h_emergency: "Gba ìrànwọ́ báyìí", h_emergency_d: "Àwọn nọ́mbà pàjáwìrì àti àwọn igbésẹ̀ ìrànlọ́wọ́ kìíní.",
    h_browse: "Wo gbogbo àwọn kókó ìlera", h_readmore: "Ka síwájú",
    e_title: "Ṣàwárí ẹ̀kọ́ ìlera", e_sub: "Yan ẹ̀ka kan tàbí ka kókó kan nísàlẹ̀.",
    e_allcat: "Gbogbo ẹ̀ka", e_topics: "Kókó", e_draft: "Àkọsílẹ̀", e_publish: "Gbé jáde", e_report: "Ròyìn",
    f_title: "Wá Ìtọ́jú", f_sub: "Wá ilé-ìwòsàn, ilé-ìwòsàn, PHC, ilé-awakọ̀, ilé-oògùn àti òjògbón — kí o sì kàn sí wọn tààrà.",
    f_search: "Wá nípa orúkọ, iṣẹ́, tàbí LGA…", f_all: "Gbogbo ẹ̀ka", f_verified: "Ti fọwọ́ sí", f_call: "Pe",
    f_whatsapp: "WhatsApp", f_dir: "Ìtọ́sọ́nà", f_request: "Béèrè ìbẹ̀wò", f_reportP: "Ròyìn olùpèsè",
    f_open_24: "Ṣí ní gbogbo wákàtí", f_no_results: "Kò sí olùpèsè tó bá àwáwí rẹ.", f_services: "Iṣẹ́",
    f_hours: "Àkókò", f_desc: "Nípa ilé-ẹ̀kọ́ yìí",
    s_title: "Àwọn Iṣẹ́", s_sub: "Ṣàyẹ̀wò ìlera rẹ kí o sì wálẹ̀ẹ́ àwọn iṣẹ́ ìgbàkọ́ọ̀.",
    s_book: "Wálẹ̀ẹ́ iṣẹ́ tàbí ìbẹ̀wò", s_received: "Àgbéwò gbà",
    em_title: "Gba Ìrànwọ́ Báyìí", em_sub: "Ìtọ́sọ́nà pàjáwìrì àti ibi tí o lè pe àwọn nọ́mbà ìrànlọ́wọ́.",
    hh_title: "Ìlera Mi", hh_sub: "Àgbègbè rẹ — ṣàmúlò, ṣe eré ìdárayá, kọ̀wé, kí o sì dúró sórí ọ̀nà rẹ.",
    hh_exercise: "Eré ìdárayá & iwuwo", hh_exercise_d: "Kọ́ ọ̀nà àti àwọn iwuwo rẹ lójoojúmọ́.",
    hh_journal: "Ìwé àkèsán", hh_journal_d: "Imọ̀lára, àmì àrùn àti ara.",
    hh_records: "Àkọsílẹ̀ ìlera", hh_records_d: "Àwọn ìbẹ̀wò, àbájáde ìwádìí àti àwọn ìwé.",
    hh_reminders: "Àwọn ìránnilétí", hh_reminders_d: "Oògùn, ìdárayá àti àwọn ìrànílétí ìpàdé.",
    a_title: "Àkọọ́lẹ̀", a_sub: "Ṣẹ̀dá àkọọ́lẹ̀ tàbí tẹ̀síwájú gẹ́gẹ́ bí àlejò.",
    a_name: "Orúkọ pípé", a_email: "Ìmẹ̀lẹ̀", a_phone: "Fóònù", a_role: "Èmi jẹ́",
    a_consumer: "Aláìsàn / ẹgbẹ́ àgbègbè", a_provider: "Olùpèsè ìlera", a_admin: "Ẹgbẹ́ CareNBuddi",
    a_signup: "Ṣẹ̀dá àkọọ́lẹ̀", a_signin: "Wọlé", a_signout: "Jáde",
    a_send_code: "Rán kódì ìkọ́kọ́ sí mi", a_verify: "Fìdí rẹ̀ múlẹ̀", a_code: "Kódì 6 nọ́ńbà",
    a_language: "Èdè", a_language_d: "Yí èdè àkọọ́lẹ̀ àti àwọn ìkọ́ ìlera padà.",
    a_demo: "Ọ̀nà ìdánwò", a_demo_admin: "Ṣí ìdánwò ìdarí", a_demo_provider: "Ṣí ìdánwò olùpèsè", a_demo_consumer: "Ṣí ìdánwò aláìsàn",
    a_welcome: "O ti wọlé", c_back: "Pàdà", c_save: "Fipamọ́", c_cancel: "Fagilé",
    a_password: "Ọ̀rọ̀ ìpamọ́",
    a_cloud: "Àkọọ́lẹ̀ ní ọjọ́ ìwé",
    a_cloud_d: "Wọlé láti ṣe àkójọ àwọn ìwé rẹ kí o sì lò CareNBuddi lórí ẹ̀rọ yìí.",
    a_signed_in_as: "A ti wọlé ní",
    a_sync_now: "Ṣàtúnṣe ní báyìí",
    a_syncing: "Ń ṣàtúnṣe…",
    a_synced: "Àwọn ìwé gbogbò ti wà ní ìpamọ́",
    a_sync_idle: "Ṣétà láti ṣàtúnṣe",
a_sync_off: "Àkójọ ọ̀fẹ́ — ìwé rẹ ń gùn nínú ẹ̀rọ yìí",
  a_offline_note: "Ṣiṣẹ́ ní offlain — ìmọ̀ rẹ ń gùn nínú ẹ̀rọ yìí. Wọlé láti ṣàtúnṣe fún gbogbo ẹ̀rọ rẹ.",
  auth_or: "tàbí",
  auth_google: "Google",
  auth_apple: "Apple",
  a_confirm_email: "A ṣẹ̀dá àkọọ́lẹ̀. Ṣàyẹ̀wò ìmẹ̀lẹ̀ rẹ láti fìdí ì, lẹ́yìn náà wọlé.",
    a_bad_login: "Ìmẹ̀lẹ̀ tàbí ọ̀rọ̀ ìpamọ́ kò tọ́.",
    a_missing_fields: "Kí ìmẹ̀lẹ̀ àti ọ̀rọ̀ ìpamọ́ rẹ kí o.",
    c_remove: "Yọ", c_send: "Firanṣẹ́", c_new: "Tuntun", c_status: "Ipò", c_pending: "Òǹdúró",
    c_approved: "Ti fọwọ́ sí", c_rejected: "Ti kọ̀ sílẹ̀", c_resolved: "Ti yanjú", c_none: "Kòsí",
    c_manage: "Ṣàkóso", c_reason: "Ìdí",
    pv_title: "Ẹ̀bùn olùpèsè", pv_sub: "Ṣàkóso àkọọ́lẹ̀ ilé-iṣẹ́ rẹ àti àwọn ìbéèrè.",
    pv_register: "Forukọsilẹ̀ ilé-iṣẹ́ rẹ", pv_requests: "Àwọn ìbéèrè / ìwálẹ̀ẹ́", pv_profile: "Àkọọ́lẹ̀ ilé-iṣẹ́ mi",
    pv_services: "Iṣẹ́ àwọn", pv_save: "Fipamọ́ àkọọ́lẹ̀", pv_pending: "Ìforúkọsílẹ̀ rẹ ń ṣàyẹ̀wò.",
    pv_none: "Kò sí ilé-iṣẹ́ tí a fọwọ́ sí bá àkọọ́lẹ̀ yìí.",
    pv_new_req: "Àwọn ìbéèrè tuntun", pv_confirm: "Sàmì pé a ti kàn sí",
    ad_title: "Ibi ìdarí", ad_sub: "Àkóónú, fífọwọ́sí, àwọn olùmúlò, ìtúpalẹ̀ àti ààbò.",
    ad_overview: "Àkọsílẹ̀", ad_content: "Àkóónú", ad_verification: "Fífọwọ́sí",
    ad_users: "Àwọn olùmúlò", ad_analytics: "Ìtúpalẹ̀", ad_reports: "Àwọn ròyìn",
    ft_nav: "CareNBuddi — Eto Ìtọ́sọ́nà Ìlera Ti IlerE Rẹ.",
    ft_desc: "A máa so ẹ̀kọ́ ìlera pọ̀ mọ́ ìgbésẹ̀ tó tọ́ — ṣàyẹ̀wò àwọn nọ́ńbà rẹ, wá ìtọ́jú tí a fọwọ́ sí, walẹ̀ẹ́ àwọn iṣẹ́, kí o sì tẹ̀lé — fún ẹni kọ̀ọ̀kan, ìdílé àti àwùjọ jákèjádò Nàìjíríà.",
    ft_notdx: "CareNBuddi pese àlàyé ìlera gbogbogbòò àti ìtọ́sọ́nà. Kì í ṣe iwádìí òṣìṣẹ́ ìwòsàn, kò sì rọ́pò òjògbón ìlera.",
    ft_emergency: "Ní pàjáwìrì, pe nọ́ńbà pàjáwìrì àdúgbò rẹ kíákíá — kí o tó lo ìpele yìí.",
    ft_lang: "Wà ní Èdè Gẹ̀ẹ́sì, Yorùbá, Hausa àti Igbo.",
    ft_report: "Ròyìn àlàyé tí kò tọ́ tàbí tó ti pẹ́",
  n_chronic: "Àjọ nípa àrùn àtijọ́", n_chronic_d: "Àwọn ọ̀nà ìmọ̀ fún àrùn àtijọ́ bí ẹ̀jẹ̀ lílára.",
  n_journey: "Ìrìnàjò ìlera", n_journey_d: "Àwọn àkọsílẹ̀ àti ìbẹ̀wò rẹ ní ibi kan.",
  n_carecircle: "Àwọn Tòun ìtọ́jú", n_carecircle_d: "Ìlera ẹbí ní ojú kan.",
  n_healthdays: "Àwọn Ọjọ́ Ìlera", n_healthdays_d: "Àwọn àyẹ̀wò àwùjọ àti tẹ̀lé.",
  n_worker: "Ipo òṣìṣẹ́", n_worker_d: "Àwọn ohun èlò fún àwọn òṣìṣẹ́ ìlera àgbègbè.",
  n_ask_d: "Oluranlọ́wọ́ fún àwọn àrùn, ìtọ́jú àti pẹ̀rẹtẹ̀ náà.",
  cc_title: "Olùbẹ̀wò àrùn àtijọ́", cc_sub: "Èto ọjọ́ọ̀kan àti ìríranlẹ̀ oṣù fún àrùn àtijọ́.",
  cc_today: "Lónìí", cc_month: "Òṣù yìí", cc_latest: "Títóbi", cc_care: "Ìtọ́jú", cc_find: "Wá ilé-ìwòsàn nítòsí →",
  cc_hypertension: "Ìrìnàjò ẹ̀jẹ̀ lílára rẹ", cc_diabetes: "Ìrìnàjò àrùn-ẹ̀jẹ̀-díńtó rẹ",
  cc_sicklecell: "Ìrìnàjò àrùn sẹ̀ẹ̀li rẹ", cc_asthma: "Ìrìnàjò àáárẹ̀ rẹ",
  cc2_title: "Àwọn Tọ́jú", cc2_sub: "Tọ́ ìlera àwọn tí o ń tọ́jú.",
  cc2_remove: "Yọ", cc2_bp: "BP", cc2_med: "Oògùn", cc2_appt: "Ìpàdé", cc2_screen: "Àyẹ̀wò tó ń bọ̀",
  cc2_add: "Fi ọmọ-ẹgbẹ́ kún", cc2_name: "Orúkọ / àpèlé", cc2_rel: "Ìdílé", cc2_save: "Ṣùgbé", cc2_cancel: "Fagilé", cc2_addb: "Fi ọmọ-ẹgbẹ́ kún",
  hd2_title: "Àwọn Ọjọ́ Ìlera Àwùjọ", hd2_sub: "Àyẹ̀wò àti ẹ̀kọ́ ní ibi tí ènìyàn gbà — pẹ̀lú ìtẹ̀lé tó dára.",
  hd2_create: "Ṣẹ̀dá ọjọ́ ìlera", hd2_f_title: "Àkọ́lé", hd2_f_org: "Olùbẹ̀ (ìjọsìn, ilé-ìwé…)",
  hd2_f_date: "Ọjọ́", hd2_f_loc: "Ibi", hd2_f_srv: "Àwọn iṣẹ́", hd2_save: "Ṣẹ̀dá", hd2_cancel: "Fagilé", hd2_createb: "Ṣẹ̀dá ọjọ́ ìlera",
  jt_title: "Ìrìnàjò Ìlera Rẹ", jt_sub: "Ohun gbogbo tó ti ṣẹlẹ̀, ní ibi kan.",
  pp_title: "Ìwé-Ìránṣẹ́ Ìlera", pp_sub: "Àkọọ́lẹ̀ kan. Ìtàn ìlera kan. Gbókìíbi.",
  pp_details: "Àwọn àlàyé rẹ", pp_edit: "Ṣàtúnṣe", pp_save: "Ṣùgbé", pp_cancel: "Fagilé",
  pp_name: "Orúkọ pípé", pp_blood: "Ẹ̀jẹ̀", pp_allergies: "Ẹ̀dùn", pp_meds: "Oògùn tó ń wọ",
  pp_conditions: "Àrùn àtijọ́", pp_history: "Ìtàn ìṣègùn", pp_imm: "Abere", pp_hmo: "Ìlọ́síǹnù / HMO",
  pp_ec: "Olùbọ̀gbọ̀n pàjáwìrì", pp_ecp: "Fóònù pàjáwìrì",
  pp_card: "Káààdì pàjáwìrì", pp_card_d: "Fi hàn sí òṣìṣẹ́ ìlera ní pàjáwìrì.", pp_scan: "Sí sílẹ̀ pẹ̀lú àpparátà òṣìṣẹ́ CareNBuddi",
  w_title: "Ipo Òṣìṣẹ́ Ìlera", w_sub: "Àyẹ̀wò, ìtọ́sọ́nà àti tẹ̀lé láti orí iṣẹ́.",
  w_events: "Ìṣẹ̀lẹ̀", w_participants: "Àwọn tí a yẹ̀wò", w_referred: "Àwọn tí ń yẹ̀wò", w_pending: "Tẹ̀lé tó ku",
  w_log: "Kọ àyẹ̀wò", w_add: "Fi kún", w_recent: "Àwọn àkọsílẹ̀ tó kẹ́hìn", w_sync: "A máa fi pamọ́ ní ẹ̀rí kẹ̀yìn tí o bá gbà nẹ́tíwọ́ọ̀kì.", w_days: "Wo ọjọ́ ìlera →",
  ask_title: "Béèrè Lọ́wọ́ CareNBuddi", ask_ph: "Béèrè nípa àrùn, wíwá ìtọ́jú, ìye owó…", ask_send: "Fi ránṣẹ́",
  f_cost: "Òye owó", f_any_cost: "Gbogbo òye owó", f_low_cost: "₦ Kéré", f_mid_cost: "₦₦ Déédé", f_high_cost: "₦₦₦ Àṣìkù",
  h_tagline: "Àlàyé Tó Dáradára. Ìlera Ìwọ.",
  e_report_reason: "Ìmọ̀ nípa ìpéye àlàyé tàbí ààbò",
  f_location: "Ibi",
  f_category: "Ẹ̀ka",
  f_all_states: "Gbogbo ìpínlẹ̀",
  f_facility_one: "ilé-ìtọ́jú",
  f_facility_many: "àwọn ilé-ìtọ́jú",
  f_book_sent: "Àgbéwò ti ránṣẹ́. Ilé-ìtọ́jú náà yóò kàn sí ọ.",
  f_form_msg: "Àkọsílẹ̀",
  f_form_date: "Ọjọ́ tí o fẹ́",
  f_emergency: "Iṣẹ́ pàjáwìrì wà ní ilé-ìtọ́jú yìí ní gbogbo wákàtí.",
  f_provider_visit: "Ìbẹ̀wò olùpèsè",
  s_we_provide: "Àwọn iṣẹ́ ìlera tí a pèsè",
  s_check_head: "Ṣàyẹ̀wò Ìlera Mi",
  s_open_health: "Ṣí ojú-ewé ìlera mi",
  s_intro: "Béèrè iṣẹ́ àyẹ̀wò, ìtajà àgbègbè, wíláwò tàbí ìbẹ̀wò ọkọ̀ pàjáwìrì fún ara rẹ, ìdílé rẹ, ibi iṣẹ́ tàbí àwùjọ rẹ. Kò sí owó tí a béèrè láti fi béèrè — ẹgbẹ́ kan yóò jẹrí àwọn àlàyé ní fònù.",
  s_form_head: "Béèrè iṣẹ́ tàbí ìbẹ̀wò",
  s_service: "Iṣẹ́",
  s_date: "Ọjọ́ tí o fẹ́",
  s_area: "Agbègbè / ẹgbẹ́ / ibi iṣẹ́",
  s_submit: "Béèrè iṣẹ́",
  s_free_note: "Kò sí owó tí a béèrè láti fi béèrè. Ẹgbẹ́ kan yóò jẹrí ohun tí o yẹ fún, ìye owó, àti àwọn àlàyé ní fònù.",
  s_book_another: "Wálẹ̀ẹ́ ìbẹ̀wò míì",
  s_on_date: " ní ọjọ́ ",
  s_success: "O ṣeun {name}! Ẹgbẹ́ CareNBuddi kan yóò kàn sí {phone} láti jẹrí ìbẹ̀wò {service} rẹ{date}. A máa jẹrí ìwálẹ̀ẹ́ kọ̀ọ̀kan ní fònù àti sms.",
  sc_bp: "Ẹ̀jẹ̀ lílára",
  sc_bp_d: "Àyẹ̀wò ẹ̀jẹ̀ kíákíá àti ìtẹ̀lé tó rọrùn.",
  sc_glu: "Ìwọ̀n-súgà inú ẹ̀jẹ̀",
  sc_glu_d: "Àyẹ̀wò glukóòsì àti ìmọ̀ràn ìgbésíayé.",
  sc_well: "Àyẹ̀wò wíníssí",
  sc_well_d: "Àyẹ̀wò ìpìlẹ̀ ara àti ìlera gbogbogbòò.",
  srv_education: "Ẹ̀kọ́ ìlera",
  srv_education_d: "Ìkẹ́kọ̀ọ́ tó rọrùn nípa ìdènà àti ìdúróṣinṣin ìlera.",
  srv_outreach: "Ìtajà àgbègbè",
  srv_outreach_d: "Ìṣẹ̀lẹ̀ àyẹ̀wò àti ìmúlẹ̀ ní àgbègbè rẹ.",
  srv_corporate: "Wíláwò ibi iṣẹ́",
  srv_corporate_d: "Ọjọ́ ìlera ibi iṣẹ́ fún àwọn ẹgbẹ́ àti agbari.",
  srv_mobile: "Ìbẹ̀wò ọkọ̀ pàjáwìrì",
  srv_mobile_d: "Àyẹ̀wò, ìtajà àti iṣẹ́ wíláwò ní ibi tí o wà.",
  srv_referral: "Iṣẹ́ títọ́ àlọ̀",
  srv_referral_d: "Ìtẹ̀lé tó dára sí olùpèsè tó yẹ nígbà tí ó bá yẹ.",
  srv_campaigns: "Ìtẹ̀wé ìlera",
  srv_campaigns_d: "Àwọn ọjọ́ àyẹ̀wò àgbègbè bíi “Mọ Àwọn Nọ́mbà Rẹ”.",
  em_call: "Pe nọ́mbà pàjáwìrì lẹ́sẹ̀kẹsẹ̀",
  em_call_d: "Fún ìdígárarí ara, àìsàn ọkàn, àìlè mí, ẹ̀jẹ̀ lílọ, ìjóná, àpẹẹrẹ àrùn-ọpọlọ, tàbí ìṣòro kankan — má ṣe dúró, má sì gbẹ́kẹ̀lé àpparátà náà.",
  em_while: "Nígbà tí o ń dúró fún ìrànlọ́wọ́ ọlọ́jà",
  em_s1: "Jẹ́ kí ara rẹ àti ẹni náà wà ní ààbò — má ṣe gbe wọn nígbà tí wọn bá wà ní ewu.",
  em_s2: "Bí wọn bá ti dè láàrin oorun ṣùgbọ́n tí wọn ń mí, fi wọn sí ipò ìgbàpadà.",
  em_s3: "Fún ìjóná, fún omi tutu láti fau sí i fún o kéré jù 20 ìṣẹ́jú — má lò yìńtá, bota, tàbí eyín.",
  em_s4: "Fún ẹ̀jẹ̀ lílọ, tẹ̀ wọn níwọ̀jú pẹ̀lú aṣọ mímọ́.",
  em_s5: "Fún àpẹẹrẹ àrùn-ọpọlọ (ojú rẹ̀ ń rọ̀, ọwọ́ rẹ̀ ń rẹ, ọ̀rọ̀ rẹ̀ ń gbọ́), de ọdọ àwọn pàjáwìrì kíákíá.",
  em_find_care: "Wá ìtọ́jú tí ń mú kí pàjáwìrì wà",
  em_find_d: "Fún ìtọ́jú tí kì í pa ẹ̀mí, wá ilé-ìtọ́jú tí ń pèsè iṣẹ́ pàjáwìrì nítòsí rẹ.",
  em_find_hospital: "Wá ilé-ìwòsàn",
  em_find_clinic: "Wá ilé-ìwòsàn",
  em_footer: "Nínú pàjáwìrì ìṣègùn, pe àwọn iṣẹ́ pàjáwìrì ní kókó. CareNBuddi jẹ́ fún ẹ̀kọ́ àti títọ́ ala.",
  hh_know: "Mọ àwọn nọ́mbà rẹ",
  hh_open: "Ṣí",
  hh_know_d: "Ṣẹ̀dá Ọjọ́ Ìlera Àwùjọ CareNBuddi tàbí wálẹ̀ẹ́ ìbẹ̀wò ọkọ̀ pàjáwìrì láti àyẹ̀wò ẹ̀jẹ̀ lílára rẹ àti glukóòsì pẹ̀lú ìlòlò òjògbón ìlera.",
  n_passport: "Ìwé Pásìpọ́ọ̀tì Ìlera",
  n_ask: "Béèrè",
  a_code_sent: "“Demo” í-mẹ̀lẹ̀ ti ránṣẹ́ — ṣàyẹ̀wò kódì ní ìsàlẹ̀.",
  a_email_required: "Tẹ àdiirẹ́ẹ̀sì í-mẹ̀lẹ̀ rẹ ní kókó.",
  a_code_mismatch: "Kódì náà kò bára mu. Ṣàyẹ̀wò kí o tún gbìyànjú.",
  a_demo_mode: "irú “demo” náà ń fi kódì hàn dípò ránṣẹ́ í-mẹ̀lẹ̀.",
  a_demo_note: "Àwọn pápá olùpèsè àti ìdarí jẹ́ tí a ń gé-ọ̀nà sí nípa páyiti.",
  a_email_ph: "iwo@apeere.com",
  a_member_default: "Ọmọ-ẹgbẹ́ CareNBuddi",
  pv_confirm_done: "Jẹrí",
  pv_guard: "Agbègbè yìí jẹ́ fún àwọn olùpèsè ìlera tí a fọwọ́ sí. Wọlé pẹ̀lú àkọọ́lẹ̀ olùpèsè tàbí ìdarí láti tẹ̀síwájú.",
  pv_services_label: "Àwọn iṣẹ́ (pípa àyànmọ́nà pẹ̀lú kọ́má)",
  pv_about: "Nípa ilé-iṣẹ́ yìí",
  pv_no_message: "Kò sí àkọsílẹ̀",
  prg_lead: "Àwọn olùpèsè forúkọsílẹ̀ lẹ́ẹ̀kan pèlu; ẹgbẹ́ CareNBuddi jẹrí ilé-iṣẹ́ kọ̀ọ̀kan kí wọn tó hàn nínú Wá Ìtọ́jú gẹ́gẹ́ bí olùpèsè tí a fọwọ́ sí.",
  prg_facility: "Orúkọ ilé-iṣẹ́",
  prg_category: "Ẹ̀ka",
  prg_state: "Ìpínlẹ̀",
  prg_lga: "LGA / agbègbè",
  prg_address: "Àdírẹ́ẹ̀sì",
  prg_submit: "Fi ránṣẹ́ fún ìfọwọ́sí",
  prg_note: "Ìfọwọ́sí dáwùjọ lábæk ẹgbẹ́ — àwọn olùpèsè tí a fọwọ́ sí nìkan ni a fi àpẹẹrẹ ✓ hàn ní Wá Ìtọ́jú.",
  prg_success_1: "A ti fi {facility} ránṣẹ́ fún àyẹ̀wò.",
  prg_success_2: "Iwọ yóò lè ṣàkóso àwọn ìbéèrè rẹ àti àkọọ́lẹ̀ ní kọwọ́tọ̀ olùpèsè nígbà tí a bá fọwọ́ sí i.",
  ad_signin_req: "Agbègbè yìí jẹ́ fún ẹgbẹ́ CareNBuddi nìkan. Lo àkọọ́lẹ̀ “demo” ìdarí láti ṣe àyẹ̀wò ìṣàkóso àkóónú, ìfọwọ́sí, àwọn olùmúlò, ìtúpalẹ̀ àti àwọn ròyìn.",
  ad_providers: "Àwọn olùpèsè",
  ad_verified_p: "Àwọn olùpèsè tí a fọwọ́ sí",
  ad_topics: "Àwọn kókó",
  ad_verify_pending: "Ìfọwọ́sí tí ń dúró",
  ad_bookings: "Àwọn wálẹ̀ẹ́",
  ad_reports_open: "Àwọn ròyìn tí ń ṣí",
  ad_c_add: "Fi kókó kún (àpẹ̀rọ)",
  ad_c_slug: "slug",
  ad_c_title: "Àkọ́lé",
  ad_c_summary: "Àkótùn",
  ad_c_category: "Ẹ̀ka",
  ad_c_add_draft: "Fi àpẹ̀rọ kún",
  ad_c_publish: "Gbé jáde",
  ad_c_unpublish: "Yọ́ kúrò nínú ìgbéjáde",
  ad_c_delete: "Paá rẹ́ rẹ́",
  ad_c_required: "Slug àti àkọ́lé ni a béèrè.",
  ad_c_draft_note: "Àpẹ̀rọ — fi àkótùn kún kí o tó gbé jáde.",
  ad_c_empty_summary: "Ń bọ̀ láìpẹ́.",
  ad_c_exists: "Kókó kan pẹ̀lú slug yìí wà tẹ́lẹ̀.",
  ad_c_created: "A ti ṣẹ̀dá àpẹ̀rọ — gbé jáde láti atokọ ìsàlẹ̀.",
  ad_v_none: "Kò sí ìbéèrè ìforúkọsílẹ̀.",
  ad_v_verify: "Fọwọ́ sí & gbé jáde",
  ad_v_reject: "Kọ̀",
  ad_v_approved_desc: "CareNBuddi ti fọwọ́ sí lẹ́yìn àyẹ̀wò ìwé.",
  ad_u_name: "Orúkọ",
  ad_u_email: "Í-mẹ̀lẹ̀",
  ad_u_role: "Ipò",
  ad_u_joined: "Dára pọ̀",
  ad_a_cat: "Àwọn olùpèsè nípa ẹ̀ka",
  ad_a_state: "Àwọn olùpèsè nípa ìpínlẹ̀",
  ad_a_bookings: "Àwọn ìbéèrè wálẹ̀ẹ́ — ọjọ́ 14 sẹ́hìn",
  ad_a_requests: "Àwọn ìbéèrè",
  ad_a_pipeline: "Ìtọ̀forúkọsílẹ̀:",
  ad_a_submitted: "fi ránṣẹ́",
  ad_a_approved: "fọwọ́ sí",
  ad_a_pending0: "dúró",
  ad_r_none: "Kò sí ròyìn.",
  ad_r_resolve: "Yanjú",
  pr_requests: "Àwọn ìbéèrè mi",
  pr_no_requests: "Kò sí ìbéèrè wálẹ̀ẹ́ kankan sibẹ̀.",
  pr_get_started: "láti bẹ̀rẹ̀.",
  pr_provider: "Ìbẹ̀wò olùpèsè",
  pr_appt: "Àwọn ìpàdé",
  pr_appt_d: "Àwọn ìbẹ̀wò tó ń bọ̀ àti àwọn ìbéèrè yóò hàn níbí.",
  pr_rem: "Àwọn ìránnilétí",
  pr_rem_d: "A ti ṣeto àwọn ìránnilétí oògùn àti àyẹ̀wò.",
  pr_saved: "Àwọn olùpèsè tó pamọ́",
  pr_saved_d: "Samisìlé àwọn ilé-iṣẹ́ àti òjògbón tí o gbẹ́kẹ̀lé.",
  pr_records: "Àkọsílẹ̀ ìlera",
  pr_records_d: "A fi àwọn àkọsílẹ̀ hàn níbi tí ó bá tọ́ ní òfin nìkan.",
  pr_soon: "Ń bọ̀ láìpẹ́",
  j_title: "Ìwé àkọọ́lẹ̀ ìlera",
  j_sub: "Kọ imọ̀lára rẹ, àwọn àmì àrùn àti ara rẹ lójoojúmọ́.",
  j_new: "Àkọsílẹ̀ tuntun",
  j_date: "Ọjọ́",
  j_mood: "Imọ̀lára",
  j_symptoms: "Àwọn àmì àrùn",
  j_weight: "Iwuwo (kg)",
  j_heart: "Ìfọ́yẹ̀ ọkàn (bpm)",
  j_sleep: "Orun (hrs)",
  j_steps: "Ìgbésẹ̀",
  j_bp_sys: "Ìfọ́yẹ̀ ẹ̀jẹ̀ tó lókè",
  j_bp_dia: "Ìfọ́yẹ̀ ẹ̀jẹ̀ tó kéré",
  j_notes: "Àkíyèsí",
  j_note_ph: "Báwo ni ọjọ́ rẹ ṣe lọ?",
  j_save: "Pamọ́ àkọsílẹ̀",
  j_empty: "Kò sí ìkọsílẹ̀ kankan. Fi àkọ́kọ́ rẹ kún.",
  j_collapse: "Fún in",
  j_details: "Àwọn àlàyé",
  j_delete: "Paá rẹ́",
  r_title: "Àwọn ìránnilétí",
  r_sub: "Oògùn, omi, ìṣe àti ìpàdé.",
  r_new: "Ìránni  tuntun",
  r_title_field: "Àkọ́lé",
  r_title_ph: "b.a. Oògùn ìrọlẹ́",
  r_time: "Àkókò",
  r_type: "Irú",
  r_repeat: "Tún ṣe ní",
  r_notes: "Àkíyèsí",
  r_notes_ph: "Àlàyé àfikún…",
  r_add: "Fi ìránnilétí kún",
  r_today: "Lónìí",
  r_none_today: "Kò sí ohun tí a ṣètò fún òní.",
  r_all: "Gbogbo ìránnilétí",
  r_none: "Kò sí ìránnilétí. Fi àkọ́kọ́ rẹ kún.",
  r_on: "Wà ní",
  r_off: "Kò sí",
  r_disable: "Dínà",
  r_enable: "Jẹ́ kí ó wà",
  r_delete: "Paá rẹ́",
  rc_title: "Àwọn àkọsílẹ̀ ìṣègùn",
  rc_sub: "Pamọ́ ìtọ́ka àkọsílẹ̀ ìbẹ̀wò, ìwádìí àti ògùn.",
  rc_add: "Fi àkọsílẹ̀ kún",
  rc_title_field: "Àkọ́lé",
  rc_title_ph: "b.a. Àbájáde ìwádìí ẹ̀jẹ̀",
  rc_provider: "Olùpèsè / ilé-iṣẹ́",
  rc_provider_ph: "b.a. Dókítà Smith, Ilé-ìwòsàn Ìlú",
  rc_date: "Ọjọ́",
  rc_category: "Ẹ̀ka",
  rc_summary: "Àkótùn / àbájáde",
  rc_summary_ph: "Àwọn àwádìí tàbí àkíyèsí pàtàkì…",
  rc_link: "Ìtọ́ka (àfikún)",
  rc_save: "Pamọ́ àkọsílẹ̀",
  rc_all: "Gbogbo",
  rc_empty: "Kò sí àkọsílẹ̀ níbí sibẹ̀.",
  rc_delete: "Paá rẹ́",
  rc_open: "Ṣí àkọsílẹ̀ tí a so",
  ex_back: "Pàdà sí Ìlera Mi",
  ex_title: "Ìrìnàjò Eré Ìdárayá & Iwuwo",
  ex_sub: "Ṣètò ète rẹ, kọ iṣẹ́ ojoojúmọ́ rẹ, kí o sì wo ìtẹ̀síwájú rẹ. Àwọn dátà rẹ dúró lórí ẹ̀rọ yìí.",
  ex_streak: "{n} ọjọ́ ìwọ̀nsì",
  ex_goal_1: "Ètè rẹ",
  ex_loss_goal: "Ètè ìdínà iwuwo",
  ex_gain_goal: "Ètè ìpọ̀ iwuwo",
  ex_goalfmt: " — láti {start} kg sí {goal} kg (gíga {h} cm).",
  ex_height: "Gíga (cm)",
  ex_start_w: "Ìwọ̀n bẹ̀rẹ̀ (kg)",
  ex_goal_w: "Ìwọ̀n ète (kg)",
  ex_save_goal: "Pamọ́ ète",
  ex_today_w_ph: "Kọ iwuwo òní (kg)",
  ex_record_w: "Kọ iwuwo",
  ex_warn: "Jọ̀ọ́ tẹ gíga, iwuwo bẹ̀rẹ̀ àti iwuwo ète ní cm / kg.",
  ex_cur_w: "Iwuwo lọ́wọ́lọ́wọ́",
  ex_lost: "Títí èsọnú",
  ex_gained: "Títí ìpọ̀",
  ex_to_goal: "sí ète",
  ex_progress: "Ìtẹ̀síwájú àjò",
  ex_goal_x: "Ètè {g} kg",
  ex_week_active: "Ṣiṣe ní ọ̀sẹ̀ yìí",
  ex_logged_today: "{n} tí a kọ lónìí",
  ex_weight_journey_2: "Ìrìnàjò iwuwo",
  ex_checkins: "{n} ìgbámúṣe",
  ex_goal_label: "Ètè",
  ex_date: "Ọjọ́",
  ex_weight: "Iwuwo",
  ex_change: "Ìyípadà",
  ex_start: "bẹ̀rẹ̀",
  ex_train_3: "Ṣe eré lójoojúmọ́",
  ex_done: "Ṣe tán lónìí",
  ex_not_done: "Kò tí ì ṣe lónìí",
  ex_exercise: "Eré ìdárayá",
  ex_minutes: "Ìṣẹ́jú",
  ex_note_opt: "Àkíyèsí (àfikún)",
  ex_note_ph: "b.a. mo nímọ̀lára dáradára, ìdárayá ìròlẹ́",
  ex_log: "Kọ ìdárayá",
  ex_remove: "Yọ",
  ex_no_today: "Kò sí ìdárayá tí a kọ lónìí. Yan ìdárayá ní òkè tàbí látinú ibi-ẹ̀kọ́ ìsàlẹ̀.",
  ex_reminder_4: "Ìránnilétí ìdárayá ojoojúmọ́",
  ex_rem_on: "Ń ṣiṣẹ́ — ìránnilétí ti ṣètò fún {time}.",
  ex_rem_off: "A ti pa ìránnilétí.",
  ex_rem_time: "Àkókò ìránnilétí",
  ex_rem_note: "Ìránnilétí àdúgbè máa ń ràn ọ́ lọ́wọ́ láti ṣe é lójoojúmọ́. A ti ṣètò fún ránṣẹ́ ìránni  ní MVP.",
  ex_library_5: "Ibì-ẹ̀kọ́ ìdárayá",
  ex_library_d: "Àwọn fóótò àti fídíò àwọn ìdárayá ọ̀tọ̀ọ̀tọ̀. Yan ọ̀kan kí o sì kọ ọ́ gẹ́gẹ́ bí ìdárayá òní.",
  ex_hide: "Fọ́ń",
  ex_howto: "Báwo ni a ṣe ń ṣe é",
  ex_log_today: "Kọ òní",
  ex_media_1: "Látí fi àwọn médíà ara rẹ ṣe àfikún: fi àwọn fóótò sínú",
  ex_media_2: "àti àwọn fídíò sínú",
  ex_media_3: "Wọn yóò hàn lẹ́sẹ̀kẹsẹ̀.",
  hd_when: "Ìgbà tí o yẹ láti wá ìrànlọ́wọ́ ọlọ́jà",
  hd_what: "Kí ni",
  hd_symptoms: "Àwọn àmì àti àmìfihàn",
  hd_risk: "Àwọn ẹ̀dùn",
  hd_prevention: "Ìdènà",
  hd_faqs: "Àwọn ìbéèrè tí a máa ń béèrè",
  hd_read_more: "Ka síwájú",
  hd_reviewed: "Wo nipasẹ",
  hd_report: "Ròyìn",
  hd_source: "Orísun:",
  hd_find_help: "Wá Ìrànlọ́wọ́ Nítòsí Mi",
  sv_emergency: "Pàjáwìrì",
  sv_hospitals: "Àwọn ilé-ìwòsàn",
  sv_phc: "Àwọn ilé-ìtọ́jú àkọ́kọ́",
  sv_labs: "Àwọn ilé-ṣéyẹ̀wò",
  sv_pharmacies: "Àwọn ilé-oògùn",
  sv_professionals: "Àwọn òjògbón",
  count_results: "{n} olùpèsè",
  lang: "Èdè Yorùbá",

  // Mobile app redesign: appointments, find care, health, profile, auth, onboarding.
  home_guest: "Ọ̀fẹ́",
  home_overview: "Àkọsílẹ̀ ìlera",
  home_next_appt: "Ìpàdé tó ń bọ̀",
  home_no_appt: "Kò sí ìwálẹ̀ẹ́ kankan sibẹ̀",
  home_view: "Wo",
  home_reminders: "Àwọn ìránnilétí",
  home_meds: "Oògùn",
  home_bp: "Ẹ̀jẹ̀ lílára",
  home_meds_due_1: "Ìránnilétí oògùn kan wà lórí",
  home_meds_due_n: "Àwọn ìránnilétí oògùn wà lórí",
  home_no_meds: "Kò sí ìránnilétí oògùn kankan",
  home_details: "Àwọn àlàyé",
  home_quick: "Àwọn ìgbésẹ̀ kánkán",
  home_upcoming: "Ìpàdé tó ń bọ̀",
  home_all: "Gbogbo",
  home_no_appt_title: "Kò sí ìpàdé tí a wálẹ̀ẹ́",
  home_no_appt_d: "Wá olùpèsè kí o sì wálẹ̀ẹ́ ní ìgbésẹ̀ díẹ̀.",
  home_find_care: "Wá ìtọ́jú",
  home_nearby: "Àwọn iṣẹ́ ìlera ní agbègbè rẹ",
  home_see_all: "Wo gbogbo wọn",
  home_tips: "Àwọn ìmọ̀ràn ìlera",
  home_emergency_d: "Má dúró fún àpẹẹrẹ yìí. Pe nọ́mbà pàjáwìrì kíákíá, lẹ́yìn náà lo CareNBuddi.",
  home_call_112: "Pe 112",
  home_passport_d: "Káààdì pàjáwìrì rẹ àti àkótùn ìlera rẹ",
  hx_title: "Ìdárayá àti ìlera",
  home_wellness_d: "Ìgbésẹ̀, iwuwo àti órùn",
  f_cost_low: "₦ Ìye owó kéré",
  f_cost_high: "₦₦₦ Tí ó ga",
  f_cost_mid: "₦₦ Tó wọ́pọ̀",
  appt_rescheduled: "A ti yí ìpàdé padà",
  appt_cancelled_toast: "A ti fagilé ìpàdé",
  appt_title: "Àwọn ìpàdé",
  appt_sub: "Tẹ̀lé àwọn ìbẹ̀wò rẹ kí o sì béèrè àkókò mìíràn ní ìgbésẹ̀ díẹ̀.",
  appt_refresh: "Tú àwọn ìpàdé ṣe",
  appt_next: "Ìpàdé tó ń bọ̀",
  appt_view_provider: "Wo olùpèsè",
  appt_reschedule: "Yí padà",
  appt_reschedule_d: "Yan ọjọ́ àti àkókò mìíràn",
  appt_cancel_visit: "Fagilé ìbẹ̀wò yìí",
  appt_cancel_visit_d: "A máa fi ìròyìn fún olùpèsè",
  appt_none_title: "Kò sí ìpàdé tí a wálẹ̀ẹ́",
  appt_none_d: "Wá olùpèsè tí a fọwọ́ sí nítòsí rẹ kí o sì béèrè ìbẹ̀wò ní ìgbésẹ̀ díẹ̀.",
  appt_find_care: "Wá ìtọ́jú",
  appt_tab_upcoming: "Tó ń bọ̀",
  appt_tab_completed: "Ti parí",
  appt_tab_cancelled: "Ti fagilé",
  appt_need_sooner: "Ṣe o fẹ́ ìtọ́jú kíákíá?",
  appt_services: "Béèrè iṣẹ́ ìlera",
  appt_services_d: "Àyẹ̀wò, ìlera gbogbo ara àti ìbẹ̀wò pẹ̀lú ọkọ̀ ilé-ìwòsàn",
  appt_emergency_d: "Àwọn nọ́mbà pàjáwìrì àti àwọn igbésẹ̀ ìrànlọ́wọ́ kìíní",
  appt_confirm_time: "Sàmì àkókò tuntun",
  appt_current: "Lọ́wọ́lọ́wọ́",
  appt_pick_date: "Yan ọjọ́",
  appt_pick_time: "Yan àkókò",
  appt_cancel_title: "Ṣe o fẹ́ fagilé ìpàdé yìí?",
  appt_cancel_body: "A máa fagilé ìpàdé yìí. O lè tún wálẹ̀ẹ́ mọ́ lẹ́yìn náà.",
  appt_cancel_confirm: "Bẹ́ẹ̀ni, fagilé",
  appt_keep: "Fi sílẹ̀",
  fc_sub: "Ilé-ìwòsàn, PHC, ilé-ṣàyẹ̀wò, ilé-oògùn àti àwọn òjògbón — pẹ̀lú àkókò tó ń bọ̀ kìíní.",
  fc_refresh: "Tú àwọn àbájáde ṣe",
  fc_clear_search: "Pa ètò wíwá rẹ́ rẹ́",
  fc_filters: "Àwọn àṣàyàn",
  fc_error_title: "Kò sí àbájáde tó yàtọ̀",
  fc_error_d: "Kò lé gba àtòkọ àwọn ilé-ìtọ́jú rẹ. Gbìyànjú lẹ́ẹ̀kan mìíràn.",
  fc_retry: "Gbìyànjú tún",
  fc_empty_title: "Kò sí olùpèsè tí a rí",
  fc_empty_d: "Gbìyànjú orúkọ mìíràn, tàbí pa àwọn àṣàyàn rẹ́ kí o rí gbogbo wọn.",
  fc_clear_filters: "Pa àwọn àṣàyàn rẹ́",
  fc_choose_state: "Yan ìpínlẹ̀",
  fc_reset: "Tún bẹ̀rẹ̀",
  fc_show_n: "Fihàn {n} àbájáde",
  fc_name_req: "Tẹ orúkọ pípé rẹ",
  fc_phone_req: "Tẹ nọ́mbà fóònù rẹ",
  fc_missing_title: "Kò sí ilé-ìtọ́jú yìí",
  fc_missing_d: "Ilé-ìtọ́jú yìí kò sí nínú àtòkọ mọ́. Wá àwọn ilé-ìtọ́jú tó wà nítòsí rẹ.",
  fc_request_sent: "A ti fi ìbéèrè ìbẹ̀wò ránṣẹ́",
  fc_report_title: "Ròyìn ilé-ìtọ́jú yìí",
  fc_report_reason: "Kí ni àṣìṣe tó wà nínú àtòkọ yìí?",
  fc_book_appointment: "Wálẹ̀ẹ́ ìpàdé",
  fc_whatsapp_d: "Béèrè nínú WhatsApp",
  fc_request_d: "Fi ìbéèrè ránṣẹ́, ilé-ìtọ́jú náà yóò kàn sí ọ láti ṣètò ìbẹ̀wò.",
  fc_no_date: "Kò sí ọjọ́ tí a fẹ́",
  hd_steady: "Ó wà pẹ̀lú ìdúróṣinṣin",
  hd_reminder_on: "A ti tan ìránnilétí",
  hd_reminder_off: "A ti pa ìránnilétí",
  hd_eyebrow: "Àkọsílẹ̀ ìlera rẹ ní wíwọ́ kan",
  hd_title: "Ìlera rẹ",
  hd_guest_title: "Wọlé kí o máa fi àkọsílẹ̀ ìlera rẹ pamọ́",
  hd_guest_body: "Tí o bá wọlé, àwọn ìwé àkèsán rẹ, àkọsílẹ̀ rẹ àti ìránnilétí rẹ yóò máa tẹ̀lé ọ lórí ẹ̀rọ yìí.",
  hd_guest_cta: "Wọlé tàbí ṣẹ̀dá àkọọ́lẹ̀",
  hd_vitals: "Àwọn àmì ìlera",
  hd_vitals_sub: "Àwọn àgbéwọ̀n tó kẹ́hìn",
  hd_log: "Kọ",
  hd_wellness: "Ìlera ara",
  hd_wellness_sub: "Ọjọ́ 7 tó kẹ́hìn",
  hd_open: "Ṣí",
  hd_activity: "Àwọn ìgbésẹ̀ ọ̀sẹ̀ yìí",
  hd_min: "ìṣẹ́jú",
  hd_weight_goal: "Ètè iwuwo",
  hd_no_weighin: "Kò sí ìgbéwọ̀n iwuwo kankan sibẹ̀",
  hd_unit_kg: "kg",
  hd_steps: "Ìgbésẹ̀",
  hd_daily_avg: "Ìníwọ̀n ojoojúmọ́",
  hd_steps_sub: "Tó kẹ́hìn",
  hd_meds: "Oògùn",
  hd_all: "Gbogbo",
  hd_next_dose: "Àìkó mìíràn tó ń bọ̀",
  hd_paused: "Ti dúró",
  hd_toggle_med: "Yí ìránnilétí oògùn padà",
  hd_active: "ń ṣiṣẹ́",
  hd_manage: "Ṣàkóso",
  hd_no_meds: "Kò sí ìránnilétí oògùn kankan",
  hd_no_meds_d: "Fi ọ̀kan kún kí o má ṣe gbàgbé oògùn rẹ",
  hd_add: "Fi kún",
  hd_records: "Àbájáde ìwádìí àti àkọsílẹ̀",
  hd_view_all: "Wo gbogbo wọn",
  hd_no_records: "Kò sí àkọsílẹ̀ kankan sibẹ̀",
  hd_add_record: "Fi àkọsílẹ̀ kún",
  hd_passport: "Ìwé Pásìpọ́ọ̀tì Ìlera",
  hd_passport_d: "Káààdì pàjáwìrì rẹ àti àkótùn ìlera rẹ",
  hd_vaccines: "Àwọn abere ajesára",
  hd_no_vaccines: "Kò sí abere ajesára tí a kọ̀wé",
  hd_no_vaccines_d: "Fi abere kún kí o máa fi ìtàn abere rẹ pamọ́ ní ibi kan.",
  hd_journey: "Ìrìnàjò ìlera",
  hd_journey_sub: "Àwọn àgbéwọ̀n tó kẹ́hìn",
  hd_no_symptoms: "Kò sí àmì àrùn tí a kọ̀wé",
  hd_no_journal: "Kò sí àgbéwọ̀n kankan sibẹ̀",
  hd_chronic: "Àwọn àrùn àtijọ́",
  hd_chronic_d: "Ìlera ẹ̀jẹ̀ lílára, àrùn-ẹ̀jẹ̀-díńtó àti àáárẹ̀",
  hd_support: "Ẹgbẹ́ tó ń tọ́jú rẹ",
  prof_saved: "A ti fipamọ́ àkọọ́lẹ̀ rẹ",
  prof_emergency_saved: "A ti fipamọ́ olùbọ̀gbọ́ pàjáwìrì",
  prof_sub: "Àwọn àlàyé rẹ, àṣàyàn rẹ àti ààbò ní ibi kan.",
  prof_signed_out_title: "O kò tí wọlé",
  prof_signed_out_d: "Wọlé kí o máa fi àwọn ìwálẹ̀ẹ́ àti àkọsílẹ̀ rẹ pamọ́, tàbí tẹ̀síwájú gẹ́gẹ́ bí ọ̀fẹ́.",
  gate_continue_guest: "Tẹ̀síwájú gẹ́gẹ́ bí ọ̀fẹ́",
  prof_photo_failed: "A kò lè lo fídíò náà. Jẹ́yìí ọ̀kan mìíràn.",
  prof_photo_no_room: "Àyè àtúnṣe ẹ̀yìn ti tẹ́lẹ̀ níbi tí a fi fi ìwájú.",
  prof_photo_remove: "Yí fídíò kúrú",
  prof_photo_removed: "A yí fídíò kúrú",
  prof_photo_saved: "A ṣàtúnṣe fídíò",
  prof_photo_too_large: "Fídíò náà tọ́ jù. Yan ọ̀kan tí kúrú sí i.",
  prof_change_photo: "Yí fídíò padà",
  prof_no_phone: "Kò sí nọ́mbà fóònù tí a fi kún",
  prof_edit: "Ṣàtúnṣe àkọọ́lẹ̀",
  prof_account_sync: "Àkọọ́lẹ̀ àti ìsopọ̀",
  prof_emergency: "Olùbọ̀gbọ́ pàjáwìrì",
  prof_no_emergency: "Kò sí olùbọ̀gbọ́ pàjáwìrì kankan sibẹ̀",
  prof_no_emergency_d: "Fi ẹni kan kún tí àwọn olùrànlọ́wọ́ lè pe fún ọ ní pàjáwìrì",
  prof_call: "Pe",
  prof_view_all: "Wo gbogbo wọn",
  prof_bookings_1: "Ìbéèrè ìwálẹ̀ẹ́ kan",
  prof_bookings_n: "Àwọn ìbéèrè ìwálẹ̀ẹ́",
  prof_bookings_d: "Tẹ̀lé ipò gbogbo àwọn ìbẹ̀wò tí o ti béèrè.",
  auth_phone_label: "Fóònù (àfikún)",
  auth_phone_hint: "Àwọn olùpèsè máa lo ọ́ láti fìdí ìbẹ̀wò múlẹ̀",
  prof_phone_ph: "+234 ...",
  prof_email_fixed: "Kò lè yí ìmẹ̀lẹ̀ padà níbí",
  prof_emergency_ph: "bíi: Táyọ̀ Ògúnlẹ́yẹ (ará ìdílé)",
  prof_emergency_note: "Nọ́mbà yìí ni a máa fihàn lórí Káààdì Pàjáwìrì Ìlera rẹ.",
  auth_err_email_required: "Tẹ àdírẹ́ẹ̀sì ìmẹ̀lẹ̀ rẹ.",
  auth_err_email_invalid: "Àdírẹ́ẹ̀sì ìmẹ̀lẹ̀ yìí kò dára.",
  auth_reset_offline: "Ìtúntò ọ̀rọ̀ ìpamọ́ nílò àkọọ́lẹ̀ CareNBuddi nínú òwúrọ̀. Ní àpẹẹrẹ ọ̀fẹ́, a kò fọwọ́bọ ọ̀rọ̀ ìpamọ́.",
  auth_reset_unconfigured: "Kò sí ìsopọ̀ ìfiránṣẹ́ ìmẹ̀lẹ̀ sibẹ̀. Lo “Àkọọ́lẹ̀ àti ìsopọ̀” láti fi tán.",
  auth_reset_sent: "A ti rán ìtọ́ka ìtúntò ránṣẹ́",
  auth_reset_failed: "Kò lé rán ìmẹ̀lẹ̀ yìí. Gbìyànjú lẹ́ẹ̀kan mìíràn.",
  auth_reset_title: "Tún ọ̀rọ̀ ìpamọ́ rẹ ṣe",
  auth_reset_sub: "Tẹ ìmẹ̀lẹ̀ tí o fi ṣẹ̀dá àkọọ́lẹ̀ rẹ, a ó rán ìtọ́ka láti yan ọ̀rọ̀ ìpamọ́ tuntun ránṣẹ́ sí ọ.",
  auth_reset_sent_d: "Tí àdírẹ́ẹ̀sì yìí bá ní àkọọ́lẹ̀, ìtọ́ka ìtúntò yóò wà nínú àpò ìmẹ̀lẹ̀ rẹ.",
  auth_resend_in: "Ń rán…",
  auth_reset_cta: "Rán ìtọ́ka ìtúntò",
  auth_reset_cta_resend: "Tún rán ìtọ́ka ìtúntò ṣe",
  auth_back_signin: "Pàdà sí ibi wọlé",
  auth_back: "Pàdà sí CareNBuddi",
  auth_home: "Ile-iṣẹ́ CareNBuddi",
  brand_name: "CareNBuddi",
  auth_err_password_required: "Tẹ ọ̀rọ̀ ìpamọ́ rẹ.",
  auth_err_password_short: "Ọ̀rọ̀ ìpamọ́ gbọdọ̀ jẹ́ ọ̀rọ̀ 8 sí i.",
  auth_signin_no_account: "Kò sí àkọọ́lẹ̀ ọ̀fẹ́ tí ó lo ìmẹ̀lẹ̀ yìí. Ṣẹ̀dá àkọọ́lẹ̀ kí o tó wọlé.",
  auth_signed_in: "O ti wọlé",
  auth_signin_title: "O ti dé láààyè",
  auth_signin_sub: "Wọlé láti rí àwọn ìwálẹ̀ẹ́ rẹ, àkọsílẹ̀ rẹ àti Ìwé Pásìpọ́ọ̀tì Ìlera rẹ lórí ẹ̀rọ yìí.",
  auth_password_ph: "••••••••",
  auth_password_hint: "Kò kéré sí ọ̀rọ̀ 8",
  auth_forgot: "Gbàgbé ọ̀rọ̀ ìpamọ́?",
  auth_no_account: "Ṣe o tún fẹ́ ṣẹ̀dá àkọọ́lẹ̀?",
  auth_demo_link: "Ó ń ṣàyẹ̀wò nìkan?",
  auth_err_name_required: "Tẹ orúkọ pípé rẹ.",
  auth_err_phone_invalid: "Tẹ nọ́mbà fóònù tó tọ́, bíi +234 800 000 0000.",
  auth_err_confirm_mismatch: "Àwọn ọ̀rọ̀ ìpamọ́ méjèèjì kò dọ́gba.",
  auth_check_email: "Ṣàyẹ̀wò àpò ìmẹ̀lẹ̀ rẹ láti fìdí àkọọ́lẹ̀ rẹ múlẹ̀",
  auth_account_created: "A ti ṣẹ̀dá àkọọ́lẹ̀",
  auth_signup_failed: "Kò lé ṣẹ̀dá àkọọ́lẹ̀ yìí.",
  auth_signup_title: "Ṣẹ̀dá àkọọ́lẹ̀ rẹ",
  auth_signup_sub: "Àkọọ́lẹ̀ kan nìkan máa fi àwọn ìwálẹ̀ẹ́ àti àkọsílẹ̀ ìlera rẹ pamọ́ ní ibi kan. Kì í ṣe dandan — o lè tẹ̀síwájú gẹ́gẹ́ bí ọ̀fẹ́.",
  auth_role_patient: "Aláìsàn",
  auth_confirm_label: "Tẹ ọ̀rọ̀ ìpamọ́ tún",
  auth_creating: "Ń ṣẹ̀dá…",
  auth_have_account: "Ṣe o ní àkọọ́lẹ̀ tẹ́lẹ̀?",
  auth_verify_no_email: "Kò sí àdírẹ́ẹ̀sì ìmẹ̀lẹ̀ tí a lè fìdí múlẹ̀.",
  auth_confirmed: "A ti fìdí ìmẹ̀lẹ̀ rẹ múlẹ̀",
  auth_verify_short: "Tẹ kódì nọ́ńbà 6 tí o gba nínú ìmẹ̀lẹ̀ rẹ.",
  auth_verify_failed: "Kódì yìí kò tọ́.",
  auth_resent_demo: "Ní àpẹẹrẹ ọ̀fẹ́, a kò rán kódì sí ìmẹ̀lẹ̀ rẹ.",
  auth_resent: "A ti rán kódì tuntun. Ṣàyẹ̀wò àpò ìmẹ̀lẹ̀ rẹ.",
  auth_resend_failed: "Kò lé rán kódì tuntun.",
  auth_verify_title: "Fìdí ìmẹ̀lẹ̀ rẹ múlẹ̀",
  auth_verify_sub: "A ti rán ìtọ́ka fìdí àti kódì nọ́ńbà 6 sí àpò ìmẹ̀lẹ̀ rẹ. Ṣí ìtọ́ka náà, tàbí tẹ kódì ní ìsàlẹ̀.",
  auth_verify_sub_off: "Ní àpẹẹrẹ ọ̀fẹ́, a kò rán ìmẹ̀lẹ̀ kankan. Tẹ̀síwájú nígbà tí o bá fẹ́.",
  auth_email_label: "Àdírẹ́ẹ̀sì ìmẹ̀lẹ̀",
  auth_code_label: "Kódì fìdí múlẹ̀",
  auth_resend: "Rán kódì tún",
  auth_verify_hint: "Ṣe o ti fìdí rẹ̀ múlẹ̀ tẹ́lẹ̀? Wọlé pẹ̀lú ìmẹ̀lẹ̀ àti ọ̀rọ̀ ìpamọ́ rẹ.",
  auth_verify_continue: "Tẹ̀síwájú sí CareNBuddi",
  gate_signin_title: "Wọlé kí o tẹ̀síwájú",
  gate_signin_body: "Abala yìí ní àwọn àkọsílẹ̀ ìlera tí ó jẹ́ ètò. Wọlé láti rí àwọn àkọsílẹ̀ rẹ.",
  gate_signin_cta: "Wọlé",
  gate_staff_title: "Àwọn òṣìṣẹ́ nìkan",
  gate_staff_body: "Abala yìí jẹ́ fún àwọn olùpèsè àti òṣìṣẹ́ CareNBuddi nìkan.",
  gate_back_profile: "Pàdà sí Àkọọ́lẹ̀",
  appt_cancelled_note: "A ti fagilé ìpàdé yìí.",
  appt_book_again: "Wálẹ̀ẹ́ tún",
  appt_cancel: "Fagilé",
  booking_done: "A ti wálẹ̀ẹ́ ìpàdé",
  fc_book_title: "Wálẹ̀ẹ́ ìpàdé",
  fc_confirm_booking: "Sàmì ìwálẹ̀ẹ́",
  fc_visit_type: "Irú ìbẹ̀wò",
  fc_pick_date: "Yan ọjọ́",
  fc_pick_time: "Yan àkókò",
  fc_notes: "Àkíyèsí (àfikún)",
  fc_notes_ph: "Ohunkóhun tí o fẹ́ kí olùpèsè mọ́ ṣáájú ìbẹ̀wò…",
  fc_book_note: "O lè yí àkókò padà tàbí fagilé nínú àtòkọ Àwọn Ìpàdé rẹ.",
  onb_skip: "Fọ́",
  onb_step_word: "Ìgbésẹ̀",
  onb_step_1: "1 nínú 3",
  onb_step_2: "2 nínú 3",
  onb_step_3: "3 nínú 3",
  onb_back: "Pàdà",
  onb_start: "Bẹ̀rẹ̀",
  onb_next: "Tẹ̀síwájú",
  prof_signed_out: "O ti jáde",
  prof_health_prefs: "Àṣàyàn ìlera",
  prof_units: "Àwọn ìwọn",
  prof_units_d: "Báwo ni a ṣe máa fihàn iwuwo, gíga àti ìgbóná ara?",
  prof_units_metric: "Métìrì (kg)",
  prof_units_imperial: "Ímbíríà (lb)",
  prof_hmo_empty: "Kò sí sibẹ̀ — fi kún nínú Ìwé Pásìpọ́ọ̀tì Ìlera rẹ",
  prof_notifications: "Àwọn ìránnilétí",
  prof_notif_appt: "Àwọn ìránnilétí ìpàdé",
  prof_notif_appt_d: "A máa ràn ọ́ lọ́wọ́ ṣáájú ìpàdé rẹ",
  prof_notif_meds: "Àwọn ìránnilétí oògùn",
  prof_notif_meds_d: "A máa fi ìránnilétí hàn fún àwọn tí o ti tan",
  prof_notif_tips: "Àwọn ìmọ̀ràn ìlera",
  prof_notif_tips_d: "Àwọn ìmọ̀ràn nípa ìdènà àti àyẹ̀wò lójoojúmọ́",
  prof_privacy: "Ààbò àti ìdáàbòbò",
  prof_account_sync_d: "Ṣe àkójọ àwọn àkọsílẹ̀ rẹ kí o sì ṣàkóso àkọọ́lẹ̀ rẹ ní òwúrọ̀",
  prof_privacy_notice: "Ìròyìn ààbò",
  prof_privacy_notice_d: "Kí ni a máa fi pamọ́ lórí ẹ̀rọ yìí, kí ni a máa ṣe àtúnṣe sí òwúrọ̀?",
  prof_change_password: "Yí ọ̀rọ̀ ìpamọ́ padà",
  prof_change_password_d: "A máa rán ìtọ́ka ìtúntò tó ní ààbò sí ìmẹ̀lẹ̀ rẹ",
  prof_help: "Ìrànlọ́wọ́ àti atilẹyin",
  prof_contact_support: "Kàn sí ẹgbẹ́ atilẹyin",
  prof_support_email: "support@healthlink.ng",
  prof_find_d: "Wá àwọn olùpèsè àti ilé-ìwòsàn nítòsí rẹ",
  prof_signout_d: "Àwọn àkọsílẹ̀ rẹ yóò wà lórí ẹ̀rọ yìí",
  prof_privacy_local_title: "A fi pamọ́ lórí ẹ̀rọ yìí",
  prof_privacy_local_d: "Láìsí àkọọ́lẹ̀, gbogbo ohun tí o kọ — àwọn ìwálẹ̀ẹ́, ìwé àkèsán, àkọsílẹ̀, Ìwé Pásìpọ́ọ̀tì Ìlera, àṣàyàn rẹ àti fídíò profaịlì rẹ — a máa fi pamọ́ lórí fóònù rẹ nìkan. Kò yóò lọ sí òwúrọ̀.",
  prof_privacy_cloud_title: "Ìsopọ̀ sí òwúrọ̀ nìkan tí o bá fẹ́",
  prof_privacy_cloud_d: "Tí o bá so àkọọ́lẹ̀ CareNBuddi pọ̀, a máa ṣe àkójọ àwọn àkọsílẹ̀ rẹ pẹ̀lú ìdáàbòbò kí o lè lo àpẹẹrẹ yìí lórí ẹ̀rọ mìíràn. Lo “Àkọọ́lẹ̀ àti ìsopọ̀” láti so tàbí jáde.",
  prof_privacy_share_title: "Kí ni àwọn olùpèsè máa rí?",
  prof_privacy_share_d: "Olùpèsè kan máa rí orúkọ àti nọ́mbà fóònù tí o fún wọn nígbà tí o bá béèrè ìbẹ̀wò, àti àwọn àlàyé tí o yan láti fihàn nínú Ìwé Pásìpọ́ọ̀tì Ìlera rẹ.",
  prof_signout_title: "Ṣe o fẹ́ jáde kúrò nínú CareNBuddi?",
  prof_signout_body: "Àwọn àkọsílẹ̀ tí o fi pamọ́ yóò wà lórí ẹ̀rọ yìí. O lè tún wọlé lẹ́yìn náà.",
  fc_slots_call: "Pe láti mọ àwọn àkókò tó wà",
  fc_next_slot: "Àkókò tó ń bọ̀ kìíní",
  fc_book: "Wálẹ̀ẹ́",
  fc_details: "Àwọn àlàyé",
  appt_empty_upcoming: "Kò sí ìpàdé tó ń bọ̀ kankan",
  appt_empty_upcoming_d: "Wálẹ̀ẹ́ ìbẹ̀wò pẹ̀lú olùpèsè tí a fọwọ́ sí ní ìgbésẹ̀ díẹ̀.",
  appt_empty_completed: "Kò sí ìbẹ̀wò tí o ti parí sibẹ̀",
  appt_empty_completed_d: "Àwọn ìpàdé yóò lọ síbí nígbà tí ọjọ́ ìbẹ̀wò bá kọjá.",
  appt_empty_cancelled: "Kò sí ìpàdé tí a fagilé",
  appt_empty_cancelled_d: "Àwọn ìbẹ̀wò tí o fagilé yóò hàn níbí pẹ̀lú ìtàn rẹ.",
  hx_sub: "Ṣe ìdárayá kí o ní ìlera dáadáa",
  n_appts: "Àwọn ìpàdé",
  n_care: "Wá ìtọ́jú",
  n_my_health: "Ìlera mi",
  n_staff: "Àwọn ohun èlò òṣìṣẹ́",
  n_more: "Àwọn àfikún",
  n_notifications: "Àwọn ìránnilétí",
  n_main_nav: "Ojú-ọ̀nà àkọ́kọ́",
  ad_v_approved_toast: "Ilé ìwòsàn ti fọwọ́sí",
  ad_v_none_d: "Àwọn ìbéèrè forúkọsílẹ̀ ilé ìwòsàn yóò hàn níbí láti ṣàyẹ̀wò.",
  ad_r_empty: "Kò sí ìṣòlájú",
  ad_r_empty_d: "Ìṣòlájú àwọn ènìyàn yóò hàn níbí láti ṣàyẹ̀wò.",
  askx_greeting: "Pẹ̀lẹ o! Mo ni Ask CareNBuddi. Mo lè ràn ọ́ lọ́wọ́ láti lóye ọ̀nàgbà ìdáwọ́lé àti láti lo àwọn ohun tí ó ń ṣe nínú àpp — èmi kì í bá mọ́ nípa ọ̀nàgbà. Kíni ni o fẹ́ mọ̀?",
  askx_disclaimer: "Ìtumọ̀ ìwé níkan ni — kì í ṣe àrọ́pò ìṣèpàdà ọ̀pẹ̀gùn mọ́.",
  askx_emergency_hint: "Ìṣòkùn? Wọ́n 112 láti inú Gba Ìrọ̀rùn.",
  emx_national: "Ìṣòkùn orílẹ̀: 112",
  chx_title: "Ìràn ọ̀rọ̀ ìtọ́jú ìlú",
  chx_sub: "Ìtò ìwájú lójoojúmọ́ àti ìmọ̀ ní ìṣàǹwó nípa àwọn àmì ẹ̀gẹ́.",
  chx_today: "Lónìí",
  chx_month: "Osù ní báyìí",
  chx_bp_logged: "Àwọn ìwọn BP tí a kọ sílẹ̀",
  chx_entries_logged: "ìtọ́kasí ìkọlọ́kalọ́ tí a kọ sílẹ̀",
  chx_latest: "Ọ̀gbà́n",
  chx_care: "Ìtọ́jú",
  chx_find: "Wá ibi ìwòsàn tí ó sun mọ́",
  chx_reminder_set: "A ṣètò àkíyèsí fún èyí náà",
  chx_remind: "Rántí mi",
  exx_warn: "Jọ̀wọ́ bọ ìbééèkè, ìwúwún ìṣẹ̀rẹ àti ìwúwún àmáyè gbogbo ní cm / kg.",
  exx_goal_saved: "Àmáyè ti wà nípamọ́",
  exx_weight_saved: "Ìwúwún tí a kọ sílẹ̀",
  exx_workout_logged: "Àwọn ìṣeré tí a kọ sílẹ̀",
  h_dashboard: "Àwọn Ìwòsàn mi",
  ex_not_yet: "Àkúnṣẹ́ kò tíì ṣe",
  ex_current: "Ìwúwún lọ́wọ́lọ́wọ́",
  ex_week: "Ti ṣe láàárín ọ̀sẹ̀ yìí",
  ex_today: "lónìí",
  ex_bmi: "BMI",
  ex_goal: "Àmáyè",
  ex_set_goal: "Ṣètò àmáyè rẹ",
  ex_journey: "Ìrìn ìwúwún",
  exx_no_weighins: "A kò tíì kọ ìwúwún kankan.",
  exx_ph_weight: "Ìwúwún ọjọ́ lónìí (kg)",
  ex_record: "Kọ",
  ex_reminder: "Àkíyèsí ìṣeré níjoojúmọ́",
  ex_active: "Ṣiṣẹ́",
  ex_at: "ti yan fún",
  ex_off: "Àkíyèsí ti títì.",
  ex_time: "Àkíyèsí àtúnṣe",
  ex_reminder_note: "Àkíyèsí láàrin ẹ̀rẹ́ dìírà núpẹ̀ pẹ̀lú ṣíṣe ìlọ̀sí kúnjú? Ìfẹ̀ àkíyèsí wà ní ìlà ní fẹ̀ní MVP oní tẹ̀lé.",
  ex_library: "Ìlọ́wé ìṣeré",
  ex_how: "Bí a ṣe ṣe",
  ex_save: "Fi àmáyè pamọ́",
  ex_from: "láti",
  ex_to: "sí",
  exx_f_height: "Írefùlé (cm)",
  exx_f_start: "Ìwúwún ìbẹ̀rẹ̀ (kg)",
  exx_f_goal: "Ìwúwún àmáyè (kg)",
  ex_add: "Kọ ìṣeré",
  exx_f_exercise: "Ìṣeré",
  exx_f_minutes: "Ìṣẹ́jú",
  exx_f_note: "Àkíyèsí (aṣọ́wọ́)",
  exx_ph_note: "àpẹẹrẹ: ìṣẹ́ òwúrọ̀",
  ex_today_logged: "Tí a kọ sílẹ̀ lónìí",
  exx_none_today: "A kò tíì kọ ìṣeré lónìí. Yan ìṣeré lókè yìí tàbí láti inú ìlọ́wé náà.",
  exx_nice: "Ó dára lónìí",
  exx_nice_d: "Padà sí ilọ lọ́wọ́ láti tẹ̀sí ìlàsí rẹ.",
  jyx_journal: "Ìwé ìkọlọ́kalọ́ ìwòsàn",
  jyx_mood: "Àìyá",
  jyx_request: "Ìbéèrè ìwòsàn",
  jyx_screening: "Ìdíwájú àwọn ọkùnrin",
  jyx_screening_d: "Ìsẹ́yèsí \"Mọ̀ Nọ́mbà Rẹ\"",
  jyx_referred: "A tọ́kasí sí ilú ìwòsàn àkọ́kọ́",
  jyx_referred_d: "Ìwọn BP tí a ṣàkíyèsí nígbà ìdíwájú",
  jyx_empty: "Àkàkọ́ ìlà ìsà rẹ ni",
  jyx_empty_d: "Ìtọ́kasí ìkọlọ́kalọ́, ìwé ìkọlọ́kalọ́ àti ìbéèrè ìwòsàn yóò hàn níbí bí o bá fi wọn kún.",
  jyx_legend_records: "Ìwé ìkọlọ́kalọ́",
  jyx_legend_care: "Ìtọ́jú",
  jyx_legend_requests: "Ìbéèrè",
  hdx_created: "Àwọn ọjọ́ ìwòsàn ti yíyàdì",
  hdx_screened: "Tí a ṣàyẹ̀wò",
  hdx_referred: "Tí a tọ́kasí",
  hdx_followup_due: "Tí ó kò sí ìtọpa tẹ̀lé",
  hdx_followed: "Tí a tẹ̀lé",
  hdx_empty: "Kò sí ọjọ́ ìwòsàn síbẹ̀",
  hdx_empty_d: "Ṣẹ̀dá ìsẹ́yèsí ìtanṣẹ́ láti tẹ̀lé ìdíwájú àti ìtọ́kasí.",
  jr_saved: "Ìwé tí a fi pamọ́",
  jr_deleted: "A ti pa ìwé náà",
  jr_title_page: "Ìwé ìkọlọ́kalọ́ ìwòsàn",
  jr_sub_page: "Kọ àìyá, àmì àdì àti ìwọn ìwòsàn rẹ níjoojúmọ́.",
  jr_add_entry: "Fi ìwé kún",
  jr_empty_title: "Kò sí ìtọ́kasí ìkọlọ́kalọ́ síbẹ̀",
  jr_empty_body: "Bẹ̀rẹ̀ sí àtúnṣe ìwòsàn rẹ nípa fífí ìwé àkọ́kọ́ níjoojúmọ́.",
  jr_edit: "Ṣàtúnṣe",
  jr_delete: "Pa",
  jr_edit_entry: "Ṣàtúnṣe ìwé",
  jr_form_new: "Ìwé tuntun",
  jr_save: "Fi ìwé pamọ́",
  jr_date: "Ọjọ́",
  jr_mood: "Àìyá",
  jr_symptoms: "Àmì àdì",
  jr_vitals_weight: "Ìwúwún (kg)",
  jr_vitals_heart: "Ìlù ọkàn (bpm)",
  jr_vitals_sleep: "Ìwúwún sùgbọ́n (wákàtí)",
  jr_vitals_steps: "Ìgbésẹ̀",
  jr_vitals_bp_sys: "BP àìgba",
  jr_vitals_bp_dia: "BP ìsàlẹ̀",
  jr_notes: "Àkíyèsí",
  jr_note_ph: "Bí ọjọ́ rẹ ṣe rẹ?",
  jr_delete_confirm_title: "Pa ìwé ìkọlọ́kalọ́?",
  jr_delete_confirm_body: "A yóò yí ìwé náà kúrò láìdípò.",
  jr_confirm_delete: "Bẹ́ẹ̀, pa",
  jr_cancel: "Fagilé",
  pvx_staff_only: "Àdìkọ́ àwọn olùmúlò nìkan",
  pv_pending_d: "Ìwọ́sàn wa ní àyẹ̀wò gbogbo fọ́rúkọsílẹ̀ kí ìhúrú náà tó ní ṣẹ́wájú.",
  pvx_no_requests: "Àwọn ìbéèrè ọkùnrin fún ilé ìwòsàn rẹ yóò hàn níbí.",
  pvx_register_d: "Ṣàfikún tàbí fi ílu mìíràn kún",
  pvx_ph_name: "àpẹẹrẹ: Dr. Ngozi Eze",
  pvx_ph_lga: "àpẹẹrẹ: Abeokuta South",
  rc2_saved: "Ìwé ìkọlọ́kalọ́ tí a fi pamọ́",
  rc2_removed: "A ti pa ìwé ìkọlọ́kalọ́ náà",
  rc2_title: "Ìwé ìkọlọ́kalọ́ ìwòsàn",
  rc2_sub: "Fi ìtọ́wọ́sí nípa ìjíròrò àwọn ìrírò, ìdáwójú àti àtúnṣe ọkàn pẹ̀lú ọ̀nà ìsopọ̀.",
  rc2_add: "Fi ìwé kún",
  rc2_filter_all: "Gbogbo",
  rc2_empty_title: "Kò sí ìwé ìkọlọ́kalọ́ sí ibí",
  rc2_empty_body: "Fi ìjíròrò, ìdáwójú tàbí àbẹ́ṣẹ̀ kún láti tẹ́lé pẹ̀lú rẹ.",
  rc2_delete: "Pa ìwé ìkọlọ́kalọ́",
  rc2_open: "Ṣí ìwé ìkọlọ́kalọ́ tí a so",
  rc2_add_title: "Fi ìwé ìkọlọ́kalọ́ kún",
  rc2_save: "Fi ìwé ìkọlọ́kalọ́ pamọ́",
  rc2_f_title: "Àkọ́kọ́",
  rc2_f_ph_title: "àpẹẹrẹ: àbọ̀kún ìdáwójú èjìgbbí",
  rc2_f_provider: "Olùmúlò / ilé ìwòsàn",
  rc2_f_ph_provider: "àpẹẹrẹ: Dr. Smith, Ilé Ìwòsàn Ìlú",
  rc2_f_date: "Ọjọ́",
  rc2_f_category: "Àwọn ẹ̀ka",
  rc2_f_summary: "Àkúkò / àbọ̀kún",
  rc2_f_summary_ph: "Àwọn ìdíwájú àtúnṣe tàbí àkíyèsí…",
  rc2_f_link: "Ọ̀nà ìsopọ̀ (aṣọ́wọ́)",
  rc2_confirm_title: "Pa ìwé ìkọlọ́kalọ́ yìí?",
  rc2_confirm_body: "A kò lè ṣe èyí padà.",
  rc2_confirm_yes: "Bẹ́ẹ̀, pa",
  rc2_confirm_no: "Fi só",
  rm2_saved: "Àkíyèsí tí a fi kún",
  rm2_removed: "A ti pa àkíyèsí náà",
  rm2_on: "Ṣiṣẹ́",
  rm2_off: "Títì",
  rm2_delete: "Pa àkíyèsí",
  rm2_title: "Àwọn àkíyèsí",
  rm2_sub: "Oògùn, omi, ìṣẹ́ àti ìpàdé pẹ̀lú ọjọ́ ìbéèrè.",
  rm2_add: "Fi àkíyèsí kún",
  rm2_today: "Lónìí",
  rm2_empty_today: "Kò sí ètò lónìí",
  rm2_empty_today_d: "Àwọn àkíyèsí ọjọ́ lónìí rẹ yóò hàn níbí.",
  rm2_all: "Gbogbo àkíyèsí",
  rm2_empty_all: "Kò sí àkíyèsí síbẹ̀",
  rm2_empty_all_d: "Fi àkíyèsí àkọ́kọ́ kún láti má ṣe gbé omì tàbí ìjíròrò padà.",
  rm2_sheet_title: "Àkíyèsí tuntun",
  rm2_save: "Fi àkíyèsí kún",
  rm2_f_title: "Àkọ́kọ́",
  rm2_ph_title: "àpẹẹrẹ: oògùn alẹ́",
  rm2_f_time: "Àtúnṣe",
  rm2_f_type: "Ẹ̀yà",
  rm2_f_days: "Tún un ṣe ní",
  rm2_f_notes: "Àkíyèsí",
  rm2_ph_notes: "Àkíyèsí àṣọ́wọ́…",
  rm2_confirm_title: "Pa àkíyèsí yìí?",
  rm2_confirm_body: "A kò lè ṣe èyí padà.",
  rm2_confirm_yes: "Bẹ́ẹ̀, pa",
  rm2_confirm_no: "Fi só",
  wkr_saved: "Ìdíwájú tí a kọ sílẹ̀",
  wkr_online: "On-line — wà ní ìbọ̀pọ̀",
  wkr_offline: "Àìsí ìntánẹ́ẹ̀tì — àwọn àyípadà ní ìlà òkè",
  wkr_empty: "Kò sí ìdíwájú tí a kọ sílẹ̀",
  wkr_empty_d: "Kọ ìdíwájú lẹ́yìn ìsẹ́yèsí ìtanṣẹ́ nítorí kí àwọn ìtọpa tẹ̀lé má bá ṣòfo.",
  wkr_f_date: "Ọjọ́",
  wkr_f_type: "Ẹ̀yà",
  wkr_f_participants: "Àwọn olùbasilẹ̀",
  wkr_f_referred: "Tí a tọ́kasí",
  wkr_f_notes: "Àkíyèsí",
  jr_mood_great: "Ó dára gan-an",
  jr_mood_good: "Ó dára",
  jr_mood_okay: "Ó wà lórí",
  jr_mood_low: "Ó kùn",
  jr_mood_poor: "Ó ń ṣòro",
  jr_mood_unknown: "Àìyá",
  jr_symptom_headache: "Ìrora orí",
  jr_symptom_nausea: "Ìyá ni",
  jr_symptom_fatigue: "Àìyá ara",
  jr_symptom_cough: "Ègbẹ́ẹ̀",
  jr_symptom_fever: "Àrọ́gbá",
  jr_symptom_dizziness: "Àì mọ̀dọ́",
  jr_symptom_sore_throat: "Ìrora ọfun-un",
  jr_symptom_stomach: "Àtún-ìyá",
  jr_symptom_back: "Ùgbẹ́",
  jr_symptom_allergy: "Àmì ará",
  jr_symptom_other: "Mííràn",
  rc2_cat_visit: "Ìjíròrò",
  rc2_cat_lab: "Ìdáwójú ìdánwò",
  rc2_cat_imaging: "Ìyàwòrán",
  rc2_cat_prescription: "Àtúnṣe oògùn",
  rc2_cat_vaccination: "Àbẹ́ṣẹ̀",
  a_enter_email: "Kí àkọ́kọ́ ìmeèlì sí ibi.",
  cc2_added: "Ìkan àyá ìtọ́jú ti yíyàdì",
  cc2_removed: "A yíyọ",
  cc2_empty: "A kò tíì fi ẹnìyàn kún",
  cc2_empty_d: "Fi àwọn ènìyàn tí o ṣe àtúnṣe kún láti tẹ́lé àwọn àkónkò́ ìwòsàn pàtàkì wọn.",
  pp_saved: "ÌpasSPORTI ti yíyàdì",
  pp_none: "A kò ṣètò",
  s_on: "ní ọjọ́",
  s_ph_name: "àpẹẹrẹ: Amina Yusuf",
  s_ph_area: "àpẹẹrẹ: Ikeja, Lagos",
};
