import type { Dict } from "../i18n";

export const yoDict: Dict = {
    n_home: "Ile", n_explore: "Ṣàwárí", n_find: "Wá Ìtọ́jú", n_services: "Àwọn Iṣẹ́",
    n_health: "Ìlera", n_profile: "Àkọọ́lẹ̀", n_provider: "Olùpèsè", n_admin: "Ìdarí", n_account: "Àkọọ́lẹ̀ mi",
    h_title: "Kí ni a lè ṣe fún ọ lónìí?",
    h_sub: "Kọ́ nípa ìlera rẹ, ṣàyẹ̀wò ara rẹ, wá ìtọ́jú tó yẹ, kí o sì dara pọ̀ mọ́ àwọn olùpèsè ìtọ́jú.",
    h_learn: "Kọ́ nípa ìlera", h_learn_d: "Àwọn àpilẹ̀kọ tó yéni nípa àrùn àti ìdènà.",
    h_check: "Ṣàyẹ̀wò ìlera rẹ", h_check_d: "Ìgbeyẹ̀wò, ilé-ìwòsàn àti àkọọ́lẹ̀ ìlera rẹ.",
    h_find: "Wá ìtọ́jú nítòsí ọ", h_find_d: "Ilé-ìwòsàn, PHC, ilé-awakọ̀, oògùn àti òjògbón ní ìpínlẹ̀ rẹ.",
    h_connect: "Dara pọ̀ mọ́ olùpèsè ìtọ́jú", h_connect_d: "Kàn sí àwọn olùpèsè tààrà láti wálẹ̀ẹ́ tàbí béèrè ìbẹ̀wò.",
    h_search: "Wá àwọn kókó ìlera, àrùn, tàbí iṣẹ́…",
    h_emergency: "Gba ìrànwọ́ báyìí", h_emergency_d: "Àwọn nọ́mbà pàjáwìrì àti àwọn igbésẹ̀ ìrànlọ́wọ́ kìíní.",
    h_browse: "Wo gbogbo àwọn kókó ìlera", h_readmore: "Ka síwájú",
    e_title: "Ṣàwárí ẹ̀kọ́ ìlera", e_sub: "Yan ẹ̀ka kan tàbí ka kókó kan nísàlẹ̀.",
    e_allcat: "Gbogbo ẹ̀ka", e_topics: "Kókó", e_draft: "Àkọsílẹ̀", e_publish: "Gbé jáde", e_report: "Ròyìn",
    f_title: "Wá Ìtọ́jú", f_sub: "Wá ilé-ìwòsàn, ilé-ìwòsàn, PHC, ilé-awakọ̀, ilé-oògùn àti òjògbón — kí o sì kàn sí wọn tààrà.",
    f_search: "Wá nípa orúkọ, iṣẹ́, tàbí LGA…", f_all: "Gbogbo ẹ̀ka", f_verified: "Ti fọwọ́ sí", f_call: "Pe",
    f_whatsapp: "WhatsApp", f_dir: "Ìtọ́sọ́nà", f_request: "Béèrè ìbẹ̀wò", f_reportP: "Ròyìn olùpèsè",
    f_open_24: "Ṣí ní gbogbo wákàtí", f_no_results: "Kò sí olùpèsè tó bá àwáwí rẹ.", f_services: "Iṣẹ́",
    f_hours: "Àkókò", f_desc: "Nípa ilé-ẹ̀kọ́ yìí",
    s_title: "Àwọn Iṣẹ́", s_sub: "Ṣàyẹ̀wò ìlera rẹ kí o sì wálẹ̀ẹ́ àwọn iṣẹ́ ìgbàkọ́ọ̀.",
    s_book: "Wálẹ̀ẹ́ iṣẹ́ tàbí ìbẹ̀wò", s_received: "Àgbéwò gbà",
    em_title: "Gba Ìrànwọ́ Báyìí", em_sub: "Ìtọ́sọ́nà pàjáwìrì àti ibi tí o lè pe àwọn nọ́mbà ìrànlọ́wọ́.",
    hh_title: "Ìlera Mi", hh_sub: "Àgbègbè rẹ — ṣàmúlò, ṣe eré ìdárayá, kọ̀wé, kí o sì dúró sórí ọ̀nà rẹ.",
    hh_exercise: "Eré ìdárayá & iwuwo", hh_exercise_d: "Kọ́ ọ̀nà àti àwọn iwuwo rẹ lójoojúmọ́.",
    hh_journal: "Ìwé àkèsán", hh_journal_d: "Imọ̀lára, àmì àrùn àti ara.",
    hh_records: "Àkọsílẹ̀ ìlera", hh_records_d: "Àwọn ìbẹ̀wò, àbájáde ìwádìí àti àwọn ìwé.",
    hh_reminders: "Àwọn ìránnilétí", hh_reminders_d: "Oògùn, ìdárayá àti àwọn ìrànílétí ìpàdé.",
    a_title: "Àkọọ́lẹ̀", a_sub: "Ṣẹ̀dá àkọọ́lẹ̀ tàbí tẹ̀síwájú gẹ́gẹ́ bí àlejò.",
    a_name: "Orúkọ pípé", a_email: "Ìmẹ̀lẹ̀", a_phone: "Fóònù", a_role: "Èmi jẹ́",
    a_consumer: "Aláìsàn / ẹgbẹ́ àgbègbè", a_provider: "Olùpèsè ìlera", a_admin: "Ẹgbẹ́ HealthLink",
    a_signup: "Ṣẹ̀dá àkọọ́lẹ̀", a_signin: "Wọlé", a_signout: "Jáde",
    a_send_code: "Rán kódì ìkọ́kọ́ sí mi", a_verify: "Fìdí rẹ̀ múlẹ̀", a_code: "Kódì 6 nọ́ńbà",
    a_language: "Èdè", a_language_d: "Yí èdè àkọọ́lẹ̀ àti àwọn ìkọ́ ìlera padà.",
    a_demo: "Ọ̀nà ìdánwò", a_demo_admin: "Ṣí ìdánwò ìdarí", a_demo_provider: "Ṣí ìdánwò olùpèsè", a_demo_consumer: "Ṣí ìdánwò aláìsàn",
    a_welcome: "O ti wọlé", c_back: "Pàdà", c_save: "Fipamọ́", c_cancel: "Fagilé",
    c_remove: "Yọ", c_send: "Firanṣẹ́", c_new: "Tuntun", c_status: "Ipò", c_pending: "Òǹdúró",
    c_approved: "Ti fọwọ́ sí", c_rejected: "Ti kọ̀ sílẹ̀", c_resolved: "Ti yanjú", c_none: "Kòsí",
    c_manage: "Ṣàkóso", c_reason: "Ìdí",
    pv_title: "Ẹ̀bùn olùpèsè", pv_sub: "Ṣàkóso àkọọ́lẹ̀ ilé-iṣẹ́ rẹ àti àwọn ìbéèrè.",
    pv_register: "Forukọsilẹ̀ ilé-iṣẹ́ rẹ", pv_requests: "Àwọn ìbéèrè / ìwálẹ̀ẹ́", pv_profile: "Àkọọ́lẹ̀ ilé-iṣẹ́ mi",
    pv_services: "Iṣẹ́ àwọn", pv_save: "Fipamọ́ àkọọ́lẹ̀", pv_pending: "Ìforúkọsílẹ̀ rẹ ń ṣàyẹ̀wò.",
    pv_none: "Kò sí ilé-iṣẹ́ tí a fọwọ́ sí bá àkọọ́lẹ̀ yìí.",
    pv_new_req: "Àwọn ìbéèrè tuntun", pv_confirm: "Sàmì pé a ti kàn sí",
    ad_title: "Ibi ìdarí", ad_sub: "Àkóónú, fífọwọ́sí, àwọn olùmúlò, ìtúpalẹ̀ àti ààbò.",
    ad_overview: "Àkọsílẹ̀", ad_content: "Àkóónú", ad_verification: "Fífọwọ́sí",
    ad_users: "Àwọn olùmúlò", ad_analytics: "Ìtúpalẹ̀", ad_reports: "Àwọn ròyìn",
    ft_nav: "HealthLink — Eto Ìtọ́sọ́nà Ìlera Ti IlerE Rẹ.",
    ft_desc: "A máa so ẹ̀kọ́ ìlera pọ̀ mọ́ ìgbésẹ̀ tó tọ́ — ṣàyẹ̀wò àwọn nọ́ńbà rẹ, wá ìtọ́jú tí a fọwọ́ sí, walẹ̀ẹ́ àwọn iṣẹ́, kí o sì tẹ̀lé — fún ẹni kọ̀ọ̀kan, ìdílé àti àwùjọ jákèjádò Nàìjíríà.",
    ft_notdx: "HealthLink pese àlàyé ìlera gbogbogbòò àti ìtọ́sọ́nà. Kì í ṣe iwádìí òṣìṣẹ́ ìwòsàn, kò sì rọ́pò òjògbón ìlera.",
    ft_emergency: "Ní pàjáwìrì, pe nọ́ńbà pàjáwìrì àdúgbò rẹ kíákíá — kí o tó lo ìpele yìí.",
    ft_lang: "Wà ní Èdè Gẹ̀ẹ́sì, Yorùbá, Hausa àti Igbo.",
    ft_report: "Ròyìn àlàyé tí kò tọ́ tàbí tó ti pẹ́",
  n_chronic: "Àjọ nípa àrùn àtijọ́", n_chronic_d: "Àwọn ọ̀nà ìmọ̀ fún àrùn àtijọ́ bí ẹ̀jẹ̀ lílára.",
  n_journey: "Ìrìnàjò ìlera", n_journey_d: "Àwọn àkọsílẹ̀ àti ìbẹ̀wò rẹ ní ibi kan.",
  n_carecircle: "Àwọn Tòun ìtọ́jú", n_carecircle_d: "Ìlera ẹbí ní ojú kan.",
  n_healthdays: "Àwọn Ọjọ́ Ìlera", n_healthdays_d: "Àwọn àyẹ̀wò àwùjọ àti tẹ̀lé.",
  n_worker: "Ipo òṣìṣẹ́", n_worker_d: "Àwọn ohun èlò fún àwọn òṣìṣẹ́ ìlera àgbègbè.",
  n_ask_d: "Oluranlọ́wọ́ fún àwọn àrùn, ìtọ́jú àti pẹ̀rẹtẹ̀ náà.",
  cc_title: "Olùbẹ̀wò àrùn àtijọ́", cc_sub: "Èto ọjọ́ọ̀kan àti ìríranlẹ̀ oṣù fún àrùn àtijọ́.",
  cc_today: "Lónìí", cc_month: "Òṣù yìí", cc_latest: "Títóbi", cc_care: "Ìtọ́jú", cc_find: "Wá ilé-ìwòsàn nítòsí →",
  cc_hypertension: "Ìrìnàjò ẹ̀jẹ̀ lílára rẹ", cc_diabetes: "Ìrìnàjò àrùn-ẹ̀jẹ̀-díńtó rẹ",
  cc_sicklecell: "Ìrìnàjò àrùn sẹ̀ẹ̀li rẹ", cc_asthma: "Ìrìnàjò àáárẹ̀ rẹ",
  cc2_title: "Àwọn Tọ́jú", cc2_sub: "Tọ́ ìlera àwọn tí o ń tọ́jú.",
  cc2_remove: "Yọ", cc2_bp: "BP", cc2_med: "Oògùn", cc2_appt: "Ìpàdé", cc2_screen: "Àyẹ̀wò tó ń bọ̀",
  cc2_add: "Fi ọmọ-ẹgbẹ́ kún", cc2_name: "Orúkọ / àpèlé", cc2_rel: "Ìdílé", cc2_save: "Ṣùgbé", cc2_cancel: "Fagilé", cc2_addb: "Fi ọmọ-ẹgbẹ́ kún",
  hd2_title: "Àwọn Ọjọ́ Ìlera Àwùjọ", hd2_sub: "Àyẹ̀wò àti ẹ̀kọ́ ní ibi tí ènìyàn gbà — pẹ̀lú ìtẹ̀lé tó dára.",
  hd2_create: "Ṣẹ̀dá ọjọ́ ìlera", hd2_f_title: "Àkọ́lé", hd2_f_org: "Olùbẹ̀ (ìjọsìn, ilé-ìwé…)",
  hd2_f_date: "Ọjọ́", hd2_f_loc: "Ibi", hd2_f_srv: "Àwọn iṣẹ́", hd2_save: "Ṣẹ̀dá", hd2_cancel: "Fagilé", hd2_createb: "Ṣẹ̀dá ọjọ́ ìlera",
  jt_title: "Ìrìnàjò Ìlera Rẹ", jt_sub: "Ohun gbogbo tó ti ṣẹlẹ̀, ní ibi kan.",
  pp_title: "Ìwé-Ìránṣẹ́ Ìlera", pp_sub: "Àkọọ́lẹ̀ kan. Ìtàn ìlera kan. Gbókìíbi.",
  pp_details: "Àwọn àlàyé rẹ", pp_edit: "Ṣàtúnṣe", pp_save: "Ṣùgbé", pp_cancel: "Fagilé",
  pp_name: "Orúkọ pípé", pp_blood: "Ẹ̀jẹ̀", pp_allergies: "Ẹ̀dùn", pp_meds: "Oògùn tó ń wọ",
  pp_conditions: "Àrùn àtijọ́", pp_history: "Ìtàn ìṣègùn", pp_imm: "Abere", pp_hmo: "Ìlọ́síǹnù / HMO",
  pp_ec: "Olùbọ̀gbọ̀n pàjáwìrì", pp_ecp: "Fóònù pàjáwìrì",
  pp_card: "Káààdì pàjáwìrì", pp_card_d: "Fi hàn sí òṣìṣẹ́ ìlera ní pàjáwìrì.", pp_scan: "Sí sílẹ̀ pẹ̀lú àpparátà òṣìṣẹ́ HealthLink",
  w_title: "Ipo Òṣìṣẹ́ Ìlera", w_sub: "Àyẹ̀wò, ìtọ́sọ́nà àti tẹ̀lé láti orí iṣẹ́.",
  w_events: "Ìṣẹ̀lẹ̀", w_participants: "Àwọn tí a yẹ̀wò", w_referred: "Àwọn tí ń yẹ̀wò", w_pending: "Tẹ̀lé tó ku",
  w_log: "Kọ àyẹ̀wò", w_add: "Fi kún", w_recent: "Àwọn àkọsílẹ̀ tó kẹ́hìn", w_sync: "A máa fi pamọ́ ní ẹ̀rí kẹ̀yìn tí o bá gbà nẹ́tíwọ́ọ̀kì.", w_days: "Wo ọjọ́ ìlera →",
  ask_title: "Béèrè Lọ́wọ́ HealthLink", ask_ph: "Béèrè nípa àrùn, wíwá ìtọ́jú, ìye owó…", ask_send: "Fi ránṣẹ́",
  f_cost: "Òye owó", f_any_cost: "Gbogbo òye owó", f_low_cost: "₦ Kéré", f_mid_cost: "₦₦ Déédé", f_high_cost: "₦₦₦ Àṣìkù",
  h_tagline: "Àlàyé Tó Dáradára. Ìlera Ìwọ.",
  e_report_reason: "Ìmọ̀ nípa ìpéye àlàyé tàbí ààbò",
  f_location: "Ibi",
  f_category: "Ẹ̀ka",
  f_all_states: "Gbogbo ìpínlẹ̀",
  f_facility_one: "ilé-ìtọ́jú",
  f_facility_many: "àwọn ilé-ìtọ́jú",
  f_book_sent: "Àgbéwò ti ránṣẹ́. Ilé-ìtọ́jú náà yóò kàn sí ọ.",
  f_form_msg: "Àkọsílẹ̀",
  f_form_date: "Ọjọ́ tí o fẹ́",
  f_emergency: "Iṣẹ́ pàjáwìrì wà ní ilé-ìtọ́jú yìí ní gbogbo wákàtí.",
  f_provider_visit: "Ìbẹ̀wò olùpèsè",
  s_we_provide: "Àwọn iṣẹ́ ìlera tí a pèsè",
  s_check_head: "Ṣàyẹ̀wò Ìlera Mi",
  s_open_health: "Ṣí ojú-ewé ìlera mi",
  s_intro: "Béèrè iṣẹ́ àyẹ̀wò, ìtajà àgbègbè, wíláwò tàbí ìbẹ̀wò ọkọ̀ pàjáwìrì fún ara rẹ, ìdílé rẹ, ibi iṣẹ́ tàbí àwùjọ rẹ. Kò sí owó tí a béèrè láti fi béèrè — ẹgbẹ́ kan yóò jẹrí àwọn àlàyé ní fònù.",
  s_form_head: "Béèrè iṣẹ́ tàbí ìbẹ̀wò",
  s_service: "Iṣẹ́",
  s_date: "Ọjọ́ tí o fẹ́",
  s_area: "Agbègbè / ẹgbẹ́ / ibi iṣẹ́",
  s_submit: "Béèrè iṣẹ́",
  s_free_note: "Kò sí owó tí a béèrè láti fi béèrè. Ẹgbẹ́ kan yóò jẹrí ohun tí o yẹ fún, ìye owó, àti àwọn àlàyé ní fònù.",
  s_book_another: "Wálẹ̀ẹ́ ìbẹ̀wò míì",
  s_on_date: " ní ọjọ́ ",
  s_success: "O ṣeun {name}! Ẹgbẹ́ HealthLink kan yóò kàn sí {phone} láti jẹrí ìbẹ̀wò {service} rẹ{date}. A máa jẹrí ìwálẹ̀ẹ́ kọ̀ọ̀kan ní fònù àti sms.",
  sc_bp: "Ẹ̀jẹ̀ lílára",
  sc_bp_d: "Àyẹ̀wò ẹ̀jẹ̀ kíákíá àti ìtẹ̀lé tó rọrùn.",
  sc_glu: "Ìwọ̀n-súgà inú ẹ̀jẹ̀",
  sc_glu_d: "Àyẹ̀wò glukóòsì àti ìmọ̀ràn ìgbésíayé.",
  sc_well: "Àyẹ̀wò wíníssí",
  sc_well_d: "Àyẹ̀wò ìpìlẹ̀ ara àti ìlera gbogbogbòò.",
  srv_education: "Ẹ̀kọ́ ìlera",
  srv_education_d: "Ìkẹ́kọ̀ọ́ tó rọrùn nípa ìdènà àti ìdúróṣinṣin ìlera.",
  srv_outreach: "Ìtajà àgbègbè",
  srv_outreach_d: "Ìṣẹ̀lẹ̀ àyẹ̀wò àti ìmúlẹ̀ ní àgbègbè rẹ.",
  srv_corporate: "Wíláwò ibi iṣẹ́",
  srv_corporate_d: "Ọjọ́ ìlera ibi iṣẹ́ fún àwọn ẹgbẹ́ àti agbari.",
  srv_mobile: "Ìbẹ̀wò ọkọ̀ pàjáwìrì",
  srv_mobile_d: "Àyẹ̀wò, ìtajà àti iṣẹ́ wíláwò ní ibi tí o wà.",
  srv_referral: "Iṣẹ́ títọ́ àlọ̀",
  srv_referral_d: "Ìtẹ̀lé tó dára sí olùpèsè tó yẹ nígbà tí ó bá yẹ.",
  srv_campaigns: "Ìtẹ̀wé ìlera",
  srv_campaigns_d: "Àwọn ọjọ́ àyẹ̀wò àgbègbè bíi “Mọ Àwọn Nọ́mbà Rẹ”.",
  em_call: "Pe nọ́mbà pàjáwìrì lẹ́sẹ̀kẹsẹ̀",
  em_call_d: "Fún ìdígárarí ara, àìsàn ọkàn, àìlè mí, ẹ̀jẹ̀ lílọ, ìjóná, àpẹẹrẹ àrùn-ọpọlọ, tàbí ìṣòro kankan — má ṣe dúró, má sì gbẹ́kẹ̀lé àpparátà náà.",
  em_while: "Nígbà tí o ń dúró fún ìrànlọ́wọ́ ọlọ́jà",
  em_s1: "Jẹ́ kí ara rẹ àti ẹni náà wà ní ààbò — má ṣe gbe wọn nígbà tí wọn bá wà ní ewu.",
  em_s2: "Bí wọn bá ti dè láàrin oorun ṣùgbọ́n tí wọn ń mí, fi wọn sí ipò ìgbàpadà.",
  em_s3: "Fún ìjóná, fún omi tutu láti fau sí i fún o kéré jù 20 ìṣẹ́jú — má lò yìńtá, bota, tàbí eyín.",
  em_s4: "Fún ẹ̀jẹ̀ lílọ, tẹ̀ wọn níwọ̀jú pẹ̀lú aṣọ mímọ́.",
  em_s5: "Fún àpẹẹrẹ àrùn-ọpọlọ (ojú rẹ̀ ń rọ̀, ọwọ́ rẹ̀ ń rẹ, ọ̀rọ̀ rẹ̀ ń gbọ́), de ọdọ àwọn pàjáwìrì kíákíá.",
  em_find_care: "Wá ìtọ́jú tí ń mú kí pàjáwìrì wà",
  em_find_d: "Fún ìtọ́jú tí kì í pa ẹ̀mí, wá ilé-ìtọ́jú tí ń pèsè iṣẹ́ pàjáwìrì nítòsí rẹ.",
  em_find_hospital: "Wá ilé-ìwòsàn",
  em_find_clinic: "Wá ilé-ìwòsàn",
  em_footer: "Nínú pàjáwìrì ìṣègùn, pe àwọn iṣẹ́ pàjáwìrì ní kókó. HealthLink jẹ́ fún ẹ̀kọ́ àti títọ́ ala.",
  hh_know: "Mọ àwọn nọ́mbà rẹ",
  hh_open: "Ṣí",
  hh_know_d: "Ṣẹ̀dá Ọjọ́ Ìlera Àwùjọ HealthLink tàbí wálẹ̀ẹ́ ìbẹ̀wò ọkọ̀ pàjáwìrì láti àyẹ̀wò ẹ̀jẹ̀ lílára rẹ àti glukóòsì pẹ̀lú ìlòlò òjògbón ìlera.",
  n_passport: "Ìwé Pásìpọ́ọ̀tì Ìlera",
  n_ask: "Béèrè",
  a_code_sent: "“Demo” í-mẹ̀lẹ̀ ti ránṣẹ́ — ṣàyẹ̀wò kódì ní ìsàlẹ̀.",
  a_email_required: "Tẹ àdiirẹ́ẹ̀sì í-mẹ̀lẹ̀ rẹ ní kókó.",
  a_code_mismatch: "Kódì náà kò bára mu. Ṣàyẹ̀wò kí o tún gbìyànjú.",
  a_demo_mode: "irú “demo” náà ń fi kódì hàn dípò ránṣẹ́ í-mẹ̀lẹ̀.",
  a_demo_note: "Àwọn pápá olùpèsè àti ìdarí jẹ́ tí a ń gé-ọ̀nà sí nípa páyiti.",
  a_email_ph: "iwo@apeere.com",
  a_member_default: "Ọmọ-ẹgbẹ́ HealthLink",
  pv_confirm_done: "Jẹrí",
  pv_guard: "Agbègbè yìí jẹ́ fún àwọn olùpèsè ìlera tí a fọwọ́ sí. Wọlé pẹ̀lú àkọọ́lẹ̀ olùpèsè tàbí ìdarí láti tẹ̀síwájú.",
  pv_services_label: "Àwọn iṣẹ́ (pípa àyànmọ́nà pẹ̀lú kọ́má)",
  pv_about: "Nípa ilé-iṣẹ́ yìí",
  pv_no_message: "Kò sí àkọsílẹ̀",
  prg_lead: "Àwọn olùpèsè forúkọsílẹ̀ lẹ́ẹ̀kan pèlu; ẹgbẹ́ HealthLink jẹrí ilé-iṣẹ́ kọ̀ọ̀kan kí wọn tó hàn nínú Wá Ìtọ́jú gẹ́gẹ́ bí olùpèsè tí a fọwọ́ sí.",
  prg_facility: "Orúkọ ilé-iṣẹ́",
  prg_category: "Ẹ̀ka",
  prg_state: "Ìpínlẹ̀",
  prg_lga: "LGA / agbègbè",
  prg_address: "Àdírẹ́ẹ̀sì",
  prg_submit: "Fi ránṣẹ́ fún ìfọwọ́sí",
  prg_note: "Ìfọwọ́sí dáwùjọ lábæk ẹgbẹ́ — àwọn olùpèsè tí a fọwọ́ sí nìkan ni a fi àpẹẹrẹ ✓ hàn ní Wá Ìtọ́jú.",
  prg_success_1: "A ti fi {facility} ránṣẹ́ fún àyẹ̀wò.",
  prg_success_2: "Iwọ yóò lè ṣàkóso àwọn ìbéèrè rẹ àti àkọọ́lẹ̀ ní kọwọ́tọ̀ olùpèsè nígbà tí a bá fọwọ́ sí i.",
  ad_signin_req: "Agbègbè yìí jẹ́ fún ẹgbẹ́ HealthLink nìkan. Lo àkọọ́lẹ̀ “demo” ìdarí láti ṣe àyẹ̀wò ìṣàkóso àkóónú, ìfọwọ́sí, àwọn olùmúlò, ìtúpalẹ̀ àti àwọn ròyìn.",
  ad_providers: "Àwọn olùpèsè",
  ad_verified_p: "Àwọn olùpèsè tí a fọwọ́ sí",
  ad_topics: "Àwọn kókó",
  ad_verify_pending: "Ìfọwọ́sí tí ń dúró",
  ad_bookings: "Àwọn wálẹ̀ẹ́",
  ad_reports_open: "Àwọn ròyìn tí ń ṣí",
  ad_c_add: "Fi kókó kún (àpẹ̀rọ)",
  ad_c_slug: "slug",
  ad_c_title: "Àkọ́lé",
  ad_c_summary: "Àkótùn",
  ad_c_category: "Ẹ̀ka",
  ad_c_add_draft: "Fi àpẹ̀rọ kún",
  ad_c_publish: "Gbé jáde",
  ad_c_unpublish: "Yọ́ kúrò nínú ìgbéjáde",
  ad_c_delete: "Paá rẹ́ rẹ́",
  ad_c_required: "Slug àti àkọ́lé ni a béèrè.",
  ad_c_draft_note: "Àpẹ̀rọ — fi àkótùn kún kí o tó gbé jáde.",
  ad_c_empty_summary: "Ń bọ̀ láìpẹ́.",
  ad_c_exists: "Kókó kan pẹ̀lú slug yìí wà tẹ́lẹ̀.",
  ad_c_created: "A ti ṣẹ̀dá àpẹ̀rọ — gbé jáde láti atokọ ìsàlẹ̀.",
  ad_v_none: "Kò sí ìbéèrè ìforúkọsílẹ̀.",
  ad_v_verify: "Fọwọ́ sí & gbé jáde",
  ad_v_reject: "Kọ̀",
  ad_v_approved_desc: "HealthLink ti fọwọ́ sí lẹ́yìn àyẹ̀wò ìwé.",
  ad_u_name: "Orúkọ",
  ad_u_email: "Í-mẹ̀lẹ̀",
  ad_u_role: "Ipò",
  ad_u_joined: "Dára pọ̀",
  ad_a_cat: "Àwọn olùpèsè nípa ẹ̀ka",
  ad_a_state: "Àwọn olùpèsè nípa ìpínlẹ̀",
  ad_a_bookings: "Àwọn ìbéèrè wálẹ̀ẹ́ — ọjọ́ 14 sẹ́hìn",
  ad_a_requests: "Àwọn ìbéèrè",
  ad_a_pipeline: "Ìtọ̀forúkọsílẹ̀:",
  ad_a_submitted: "fi ránṣẹ́",
  ad_a_approved: "fọwọ́ sí",
  ad_a_pending0: "dúró",
  ad_r_none: "Kò sí ròyìn.",
  ad_r_resolve: "Yanjú",
  pr_requests: "Àwọn ìbéèrè mi",
  pr_no_requests: "Kò sí ìbéèrè wálẹ̀ẹ́ kankan sibẹ̀.",
  pr_get_started: "láti bẹ̀rẹ̀.",
  pr_provider: "Ìbẹ̀wò olùpèsè",
  pr_appt: "Àwọn ìpàdé",
  pr_appt_d: "Àwọn ìbẹ̀wò tó ń bọ̀ àti àwọn ìbéèrè yóò hàn níbí.",
  pr_rem: "Àwọn ìránnilétí",
  pr_rem_d: "A ti ṣeto àwọn ìránnilétí oògùn àti àyẹ̀wò.",
  pr_saved: "Àwọn olùpèsè tó pamọ́",
  pr_saved_d: "Samisìlé àwọn ilé-iṣẹ́ àti òjògbón tí o gbẹ́kẹ̀lé.",
  pr_records: "Àkọsílẹ̀ ìlera",
  pr_records_d: "A fi àwọn àkọsílẹ̀ hàn níbi tí ó bá tọ́ ní òfin nìkan.",
  pr_soon: "Ń bọ̀ láìpẹ́",
  j_title: "Ìwé àkọọ́lẹ̀ ìlera",
  j_sub: "Kọ imọ̀lára rẹ, àwọn àmì àrùn àti ara rẹ lójoojúmọ́.",
  j_new: "Àkọsílẹ̀ tuntun",
  j_date: "Ọjọ́",
  j_mood: "Imọ̀lára",
  j_symptoms: "Àwọn àmì àrùn",
  j_weight: "Iwuwo (kg)",
  j_heart: "Ìfọ́yẹ̀ ọkàn (bpm)",
  j_sleep: "Orun (hrs)",
  j_steps: "Ìgbésẹ̀",
  j_bp_sys: "Ìfọ́yẹ̀ ẹ̀jẹ̀ tó lókè",
  j_bp_dia: "Ìfọ́yẹ̀ ẹ̀jẹ̀ tó kéré",
  j_notes: "Àkíyèsí",
  j_note_ph: "Báwo ni ọjọ́ rẹ ṣe lọ?",
  j_save: "Pamọ́ àkọsílẹ̀",
  j_empty: "Kò sí ìkọsílẹ̀ kankan. Fi àkọ́kọ́ rẹ kún.",
  j_collapse: "Fún in",
  j_details: "Àwọn àlàyé",
  j_delete: "Paá rẹ́",
  r_title: "Àwọn ìránnilétí",
  r_sub: "Oògùn, omi, ìṣe àti ìpàdé.",
  r_new: "Ìránni  tuntun",
  r_title_field: "Àkọ́lé",
  r_title_ph: "b.a. Oògùn ìrọlẹ́",
  r_time: "Àkókò",
  r_type: "Irú",
  r_repeat: "Tún ṣe ní",
  r_notes: "Àkíyèsí",
  r_notes_ph: "Àlàyé àfikún…",
  r_add: "Fi ìránnilétí kún",
  r_today: "Lónìí",
  r_none_today: "Kò sí ohun tí a ṣètò fún òní.",
  r_all: "Gbogbo ìránnilétí",
  r_none: "Kò sí ìránnilétí. Fi àkọ́kọ́ rẹ kún.",
  r_on: "Wà ní",
  r_off: "Kò sí",
  r_disable: "Dínà",
  r_enable: "Jẹ́ kí ó wà",
  r_delete: "Paá rẹ́",
  rc_title: "Àwọn àkọsílẹ̀ ìṣègùn",
  rc_sub: "Pamọ́ ìtọ́ka àkọsílẹ̀ ìbẹ̀wò, ìwádìí àti ògùn.",
  rc_add: "Fi àkọsílẹ̀ kún",
  rc_title_field: "Àkọ́lé",
  rc_title_ph: "b.a. Àbájáde ìwádìí ẹ̀jẹ̀",
  rc_provider: "Olùpèsè / ilé-iṣẹ́",
  rc_provider_ph: "b.a. Dókítà Smith, Ilé-ìwòsàn Ìlú",
  rc_date: "Ọjọ́",
  rc_category: "Ẹ̀ka",
  rc_summary: "Àkótùn / àbájáde",
  rc_summary_ph: "Àwọn àwádìí tàbí àkíyèsí pàtàkì…",
  rc_link: "Ìtọ́ka (àfikún)",
  rc_save: "Pamọ́ àkọsílẹ̀",
  rc_all: "Gbogbo",
  rc_empty: "Kò sí àkọsílẹ̀ níbí sibẹ̀.",
  rc_delete: "Paá rẹ́",
  rc_open: "Ṣí àkọsílẹ̀ tí a so",
  ex_back: "Pàdà sí Ìlera Mi",
  ex_title: "Ìrìnàjò Eré Ìdárayá & Iwuwo",
  ex_sub: "Ṣètò ète rẹ, kọ iṣẹ́ ojoojúmọ́ rẹ, kí o sì wo ìtẹ̀síwájú rẹ. Àwọn dátà rẹ dúró lórí ẹ̀rọ yìí.",
  ex_streak: "{n} ọjọ́ ìwọ̀nsì",
  ex_goal_1: "Ètè rẹ",
  ex_loss_goal: "Ètè ìdínà iwuwo",
  ex_gain_goal: "Ètè ìpọ̀ iwuwo",
  ex_goalfmt: " — láti {start} kg sí {goal} kg (gíga {h} cm).",
  ex_height: "Gíga (cm)",
  ex_start_w: "Ìwọ̀n bẹ̀rẹ̀ (kg)",
  ex_goal_w: "Ìwọ̀n ète (kg)",
  ex_save_goal: "Pamọ́ ète",
  ex_today_w_ph: "Kọ iwuwo òní (kg)",
  ex_record_w: "Kọ iwuwo",
  ex_warn: "Jọ̀ọ́ tẹ gíga, iwuwo bẹ̀rẹ̀ àti iwuwo ète ní cm / kg.",
  ex_cur_w: "Iwuwo lọ́wọ́lọ́wọ́",
  ex_lost: "Títí èsọnú",
  ex_gained: "Títí ìpọ̀",
  ex_to_goal: "sí ète",
  ex_progress: "Ìtẹ̀síwájú àjò",
  ex_goal_x: "Ètè {g} kg",
  ex_week_active: "Ṣiṣe ní ọ̀sẹ̀ yìí",
  ex_logged_today: "{n} tí a kọ lónìí",
  ex_weight_journey_2: "Ìrìnàjò iwuwo",
  ex_checkins: "{n} ìgbámúṣe",
  ex_goal_label: "Ètè",
  ex_date: "Ọjọ́",
  ex_weight: "Iwuwo",
  ex_change: "Ìyípadà",
  ex_start: "bẹ̀rẹ̀",
  ex_train_3: "Ṣe eré lójoojúmọ́",
  ex_done: "Ṣe tán lónìí",
  ex_not_done: "Kò tí ì ṣe lónìí",
  ex_exercise: "Eré ìdárayá",
  ex_minutes: "Ìṣẹ́jú",
  ex_note_opt: "Àkíyèsí (àfikún)",
  ex_note_ph: "b.a. mo nímọ̀lára dáradára, ìdárayá ìròlẹ́",
  ex_log: "Kọ ìdárayá",
  ex_remove: "Yọ",
  ex_no_today: "Kò sí ìdárayá tí a kọ lónìí. Yan ìdárayá ní òkè tàbí látinú ibi-ẹ̀kọ́ ìsàlẹ̀.",
  ex_reminder_4: "Ìránnilétí ìdárayá ojoojúmọ́",
  ex_rem_on: "Ń ṣiṣẹ́ — ìránnilétí ti ṣètò fún {time}.",
  ex_rem_off: "A ti pa ìránnilétí.",
  ex_rem_time: "Àkókò ìránnilétí",
  ex_rem_note: "Ìránnilétí àdúgbè máa ń ràn ọ́ lọ́wọ́ láti ṣe é lójoojúmọ́. A ti ṣètò fún ránṣẹ́ ìránni  ní MVP.",
  ex_library_5: "Ibì-ẹ̀kọ́ ìdárayá",
  ex_library_d: "Àwọn fóótò àti fídíò àwọn ìdárayá ọ̀tọ̀ọ̀tọ̀. Yan ọ̀kan kí o sì kọ ọ́ gẹ́gẹ́ bí ìdárayá òní.",
  ex_hide: "Fọ́ń",
  ex_howto: "Báwo ni a ṣe ń ṣe é",
  ex_log_today: "Kọ òní",
  ex_media_1: "Látí fi àwọn médíà ara rẹ ṣe àfikún: fi àwọn fóótò sínú",
  ex_media_2: "àti àwọn fídíò sínú",
  ex_media_3: "Wọn yóò hàn lẹ́sẹ̀kẹsẹ̀.",
  hd_when: "Ìgbà tí o yẹ láti wá ìrànlọ́wọ́ ọlọ́jà",
  hd_what: "Kí ni",
  hd_symptoms: "Àwọn àmì àti àmìfihàn",
  hd_risk: "Àwọn ẹ̀dùn",
  hd_prevention: "Ìdènà",
  hd_faqs: "Àwọn ìbéèrè tí a máa ń béèrè",
  hd_read_more: "Ka síwájú",
  hd_reviewed: "Wo nipasẹ",
  hd_report: "Ròyìn",
  hd_source: "Orísun:",
  hd_find_help: "Wá Ìrànlọ́wọ́ Nítòsí Mi",
  sv_emergency: "Pàjáwìrì",
  sv_hospitals: "Àwọn ilé-ìwòsàn",
  sv_phc: "Àwọn ilé-ìtọ́jú àkọ́kọ́",
  sv_labs: "Àwọn ilé-ṣéyẹ̀wò",
  sv_pharmacies: "Àwọn ilé-oògùn",
  sv_professionals: "Àwọn òjògbón",
  count_results: "{n} olùpèsè",
  lang: "Èdè Yorùbá",
};
