import type { Dict } from "../i18n";

export const yoDict: Dict = {
    n_home: "Ile", n_explore: "Ṣàwárí", n_find: "Wá Ìtọ́jú", n_services: "Àwọn Iṣẹ́",
    n_health: "Ìlera", n_profile: "Àkọọ́lẹ̀", n_provider: "Olùpèsè", n_admin: "Ìdarí", n_account: "Àkọọ́lẹ̀ mi",
    h_title: "Kí ni a lè ṣe fún ọ lónìí?",
    h_sub: "Kọ́ nípa ìlera rẹ, ṣàyẹ̀wò ara rẹ, wá ìtọ́jú tó yẹ, kí o sì dara pọ̀ mọ́ àwọn olùpèsè ìtọ́jú.",
    h_learn: "Kọ́ nípa ìlera", h_learn_d: "Àwọn àpilẹ̀kọ tó yéni nípa àrùn àti ìdènà.",
    h_check: "Ṣàyẹ̀wò ìlera rẹ", h_check_d: "Ìgbeyẹ̀wò, ilé-ìwòsàn àti àkọọ́lẹ̀ ìlera rẹ.",
    h_find: "Wá ìtọ́jú nítòsí ọ", h_find_d: "Ilé-ìwòsàn, PHC, ilé-awakọ̀, oògùn àti òjògbón ní ìpínlẹ̀ rẹ.",
    h_connect: "Dara pọ̀ mọ́ olùpèsè ìtọ́jú", h_connect_d: "Kàn sí àwọn olùpèsè tààrà láti wálẹ̀ẹ́ tàbí béèrè ìbẹ̀wò.",
    h_search: "Wá àwọn kókó ìlera, àrùn, tàbí iṣẹ́…",
    h_emergency: "Gba ìrànwọ́ báyìí", h_emergency_d: "Àwọn nọ́mbà pàjáwìrì àti àwọn igbésẹ̀ ìrànlọ́wọ́ kìíní.",
    h_browse: "Wo gbogbo àwọn kókó ìlera", h_readmore: "Ka síwájú",
    e_title: "Ṣàwárí ẹ̀kọ́ ìlera", e_sub: "Yan ẹ̀ka kan tàbí ka kókó kan nísàlẹ̀.",
    e_allcat: "Gbogbo ẹ̀ka", e_topics: "Kókó", e_draft: "Àkọsílẹ̀", e_publish: "Gbé jáde", e_report: "Ròyìn",
    f_title: "Wá Ìtọ́jú", f_sub: "Wá ilé-ìwòsàn, ilé-ìwòsàn, PHC, ilé-awakọ̀, ilé-oògùn àti òjògbón — kí o sì kàn sí wọn tààrà.",
    f_search: "Wá nípa orúkọ, iṣẹ́, tàbí LGA…", f_all: "Gbogbo ẹ̀ka", f_verified: "Ti fọwọ́ sí", f_call: "Pe",
    f_whatsapp: "WhatsApp", f_dir: "Ìtọ́sọ́nà", f_request: "Béèrè ìbẹ̀wò", f_reportP: "Ròyìn olùpèsè",
    f_open_24: "Ṣí ní gbogbo wákàtí", f_no_results: "Kò sí olùpèsè tó bá àwáwí rẹ.", f_services: "Iṣẹ́",
    f_hours: "Àkókò", f_desc: "Nípa ilé-ẹ̀kọ́ yìí",
    s_title: "Àwọn Iṣẹ́", s_sub: "Ṣàyẹ̀wò ìlera rẹ kí o sì wálẹ̀ẹ́ àwọn iṣẹ́ ìgbàkọ́ọ̀.",
    s_book: "Wálẹ̀ẹ́ iṣẹ́ tàbí ìbẹ̀wò", s_received: "Àgbéwò gbà",
    em_title: "Gba Ìrànwọ́ Báyìí", em_sub: "Ìtọ́sọ́nà pàjáwìrì àti ibi tí o lè pe àwọn nọ́mbà ìrànlọ́wọ́.",
    hh_title: "Ìlera Mi", hh_sub: "Àgbègbè rẹ — ṣàmúlò, ṣe eré ìdárayá, kọ̀wé, kí o sì dúró sórí ọ̀nà rẹ.",
    hh_exercise: "Eré ìdárayá & iwuwo", hh_exercise_d: "Kọ́ ọ̀nà àti àwọn iwuwo rẹ lójoojúmọ́.",
    hh_journal: "Ìwé àkèsán", hh_journal_d: "Imọ̀lára, àmì àrùn àti ara.",
    hh_records: "Àkọsílẹ̀ ìlera", hh_records_d: "Àwọn ìbẹ̀wò, àbájáde ìwádìí àti àwọn ìwé.",
    hh_reminders: "Àwọn ìránnilétí", hh_reminders_d: "Oògùn, ìdárayá àti àwọn ìrànílétí ìpàdé.",
    a_title: "Àkọọ́lẹ̀", a_sub: "Ṣẹ̀dá àkọọ́lẹ̀ tàbí tẹ̀síwájú gẹ́gẹ́ bí àlejò.",
    a_name: "Orúkọ pípé", a_email: "Ìmẹ̀lẹ̀", a_phone: "Fóònù", a_role: "Èmi jẹ́",
    a_consumer: "Aláìsàn / ẹgbẹ́ àgbègbè", a_provider: "Olùpèsè ìlera", a_admin: "Ẹgbẹ́ HealthLink",
    a_signup: "Ṣẹ̀dá àkọọ́lẹ̀", a_signin: "Wọlé", a_signout: "Jáde",
    a_send_code: "Rán kódì ìkọ́kọ́ sí mi", a_verify: "Fìdí rẹ̀ múlẹ̀", a_code: "Kódì 6 nọ́ńbà",
    a_language: "Èdè", a_language_d: "Yí èdè àkọọ́lẹ̀ àti àwọn ìkọ́ ìlera padà.",
    a_demo: "Ọ̀nà ìdánwò", a_demo_admin: "Ṣí ìdánwò ìdarí", a_demo_provider: "Ṣí ìdánwò olùpèsè", a_demo_consumer: "Ṣí ìdánwò aláìsàn",
    a_welcome: "O ti wọlé", c_back: "Pàdà", c_save: "Fipamọ́", c_cancel: "Fagilé",
    c_remove: "Yọ", c_send: "Firanṣẹ́", c_new: "Tuntun", c_status: "Ipò", c_pending: "Òǹdúró",
    c_approved: "Ti fọwọ́ sí", c_rejected: "Ti kọ̀ sílẹ̀", c_resolved: "Ti yanjú", c_none: "Kòsí",
    c_manage: "Ṣàkóso", c_reason: "Ìdí",
    pv_title: "Ẹ̀bùn olùpèsè", pv_sub: "Ṣàkóso àkọọ́lẹ̀ ilé-iṣẹ́ rẹ àti àwọn ìbéèrè.",
    pv_register: "Forukọsilẹ̀ ilé-iṣẹ́ rẹ", pv_requests: "Àwọn ìbéèrè / ìwálẹ̀ẹ́", pv_profile: "Àkọọ́lẹ̀ ilé-iṣẹ́ mi",
    pv_services: "Iṣẹ́ àwọn", pv_save: "Fipamọ́ àkọọ́lẹ̀", pv_pending: "Ìforúkọsílẹ̀ rẹ ń ṣàyẹ̀wò.",
    pv_none: "Kò sí ilé-iṣẹ́ tí a fọwọ́ sí bá àkọọ́lẹ̀ yìí.",
    pv_new_req: "Àwọn ìbéèrè tuntun", pv_confirm: "Sàmì pé a ti kàn sí",
    ad_title: "Ibi ìdarí", ad_sub: "Àkóónú, fífọwọ́sí, àwọn olùmúlò, ìtúpalẹ̀ àti ààbò.",
    ad_overview: "Àkọsílẹ̀", ad_content: "Àkóónú", ad_verification: "Fífọwọ́sí",
    ad_users: "Àwọn olùmúlò", ad_analytics: "Ìtúpalẹ̀", ad_reports: "Àwọn ròyìn",
    ft_nav: "HealthLink — Eto Ìtọ́sọ́nà Ìlera Ti IlerE Rẹ.",
    ft_desc: "A máa so ẹ̀kọ́ ìlera pọ̀ mọ́ ìgbésẹ̀ tó tọ́ — ṣàyẹ̀wò àwọn nọ́ńbà rẹ, wá ìtọ́jú tí a fọwọ́ sí, walẹ̀ẹ́ àwọn iṣẹ́, kí o sì tẹ̀lé — fún ẹni kọ̀ọ̀kan, ìdílé àti àwùjọ jákèjádò Nàìjíríà.",
    ft_notdx: "HealthLink pese àlàyé ìlera gbogbogbòò àti ìtọ́sọ́nà. Kì í ṣe iwádìí òṣìṣẹ́ ìwòsàn, kò sì rọ́pò òjògbón ìlera.",
    ft_emergency: "Ní pàjáwìrì, pe nọ́ńbà pàjáwìrì àdúgbò rẹ kíákíá — kí o tó lo ìpele yìí.",
    ft_lang: "Wà ní Èdè Gẹ̀ẹ́sì, Yorùbá, Hausa àti Igbo.",
    ft_report: "Ròyìn àlàyé tí kò tọ́ tàbí tó ti pẹ́",
  n_chronic: "Àjọ nípa àrùn àtijọ́", n_chronic_d: "Àwọn ọ̀nà ìmọ̀ fún àrùn àtijọ́ bí ẹ̀jẹ̀ lílára.",
  n_journey: "Ìrìnàjò ìlera", n_journey_d: "Àwọn àkọsílẹ̀ àti ìbẹ̀wò rẹ ní ibi kan.",
  n_carecircle: "Àwọn Tòun ìtọ́jú", n_carecircle_d: "Ìlera ẹbí ní ojú kan.",
  n_healthdays: "Àwọn Ọjọ́ Ìlera", n_healthdays_d: "Àwọn àyẹ̀wò àwùjọ àti tẹ̀lé.",
  n_worker: "Ipo òṣìṣẹ́", n_worker_d: "Àwọn ohun èlò fún àwọn òṣìṣẹ́ ìlera àgbègbè.",
  n_ask_d: "Oluranlọ́wọ́ fún àwọn àrùn, ìtọ́jú àti pẹ̀rẹtẹ̀ náà.",
  cc_title: "Olùbẹ̀wò àrùn àtijọ́", cc_sub: "Èto ọjọ́ọ̀kan àti ìríranlẹ̀ oṣù fún àrùn àtijọ́.",
  cc_today: "Lónìí", cc_month: "Òṣù yìí", cc_latest: "Títóbi", cc_care: "Ìtọ́jú", cc_find: "Wá ilé-ìwòsàn nítòsí →",
  cc_hypertension: "Ìrìnàjò ẹ̀jẹ̀ lílára rẹ", cc_diabetes: "Ìrìnàjò àrùn-ẹ̀jẹ̀-díńtó rẹ",
  cc_sicklecell: "Ìrìnàjò àrùn sẹ̀ẹ̀li rẹ", cc_asthma: "Ìrìnàjò àáárẹ̀ rẹ",
  cc2_title: "Àwọn Tọ́jú", cc2_sub: "Tọ́ ìlera àwọn tí o ń tọ́jú.",
  cc2_remove: "Yọ", cc2_bp: "BP", cc2_med: "Oògùn", cc2_appt: "Ìpàdé", cc2_screen: "Àyẹ̀wò tó ń bọ̀",
  cc2_add: "Fi ọmọ-ẹgbẹ́ kún", cc2_name: "Orúkọ / àpèlé", cc2_rel: "Ìdílé", cc2_save: "Ṣùgbé", cc2_cancel: "Fagilé", cc2_addb: "Fi ọmọ-ẹgbẹ́ kún",
  hd2_title: "Àwọn Ọjọ́ Ìlera Àwùjọ", hd2_sub: "Àyẹ̀wò àti ẹ̀kọ́ ní ibi tí ènìyàn gbà — pẹ̀lú ìtẹ̀lé tó dára.",
  hd2_create: "Ṣẹ̀dá ọjọ́ ìlera", hd2_f_title: "Àkọ́lé", hd2_f_org: "Olùbẹ̀ (ìjọsìn, ilé-ìwé…)",
  hd2_f_date: "Ọjọ́", hd2_f_loc: "Ibi", hd2_f_srv: "Àwọn iṣẹ́", hd2_save: "Ṣẹ̀dá", hd2_cancel: "Fagilé", hd2_createb: "Ṣẹ̀dá ọjọ́ ìlera",
  jt_title: "Ìrìnàjò Ìlera Rẹ", jt_sub: "Ohun gbogbo tó ti ṣẹlẹ̀, ní ibi kan.",
  pp_title: "Ìwé-Ìránṣẹ́ Ìlera", pp_sub: "Àkọọ́lẹ̀ kan. Ìtàn ìlera kan. Gbókìíbi.",
  pp_details: "Àwọn àlàyé rẹ", pp_edit: "Ṣàtúnṣe", pp_save: "Ṣùgbé", pp_cancel: "Fagilé",
  pp_name: "Orúkọ pípé", pp_blood: "Ẹ̀jẹ̀", pp_allergies: "Ẹ̀dùn", pp_meds: "Oògùn tó ń wọ",
  pp_conditions: "Àrùn àtijọ́", pp_history: "Ìtàn ìṣègùn", pp_imm: "Abere", pp_hmo: "Ìlọ́síǹnù / HMO",
  pp_ec: "Olùbọ̀gbọ̀n pàjáwìrì", pp_ecp: "Fóònù pàjáwìrì",
  pp_card: "Káààdì pàjáwìrì", pp_card_d: "Fi hàn sí òṣìṣẹ́ ìlera ní pàjáwìrì.", pp_scan: "Sí sílẹ̀ pẹ̀lú àpparátà òṣìṣẹ́ HealthLink",
  w_title: "Ipo Òṣìṣẹ́ Ìlera", w_sub: "Àyẹ̀wò, ìtọ́sọ́nà àti tẹ̀lé láti orí iṣẹ́.",
  w_events: "Ìṣẹ̀lẹ̀", w_participants: "Àwọn tí a yẹ̀wò", w_referred: "Àwọn tí ń yẹ̀wò", w_pending: "Tẹ̀lé tó ku",
  w_log: "Kọ àyẹ̀wò", w_add: "Fi kún", w_recent: "Àwọn àkọsílẹ̀ tó kẹ́hìn", w_sync: "A máa fi pamọ́ ní ẹ̀rí kẹ̀yìn tí o bá gbà nẹ́tíwọ́ọ̀kì.", w_days: "Wo ọjọ́ ìlera →",
  ask_title: "Béèrè Lọ́wọ́ HealthLink", ask_ph: "Béèrè nípa àrùn, wíwá ìtọ́jú, ìye owó…", ask_send: "Fi ránṣẹ́",
  f_cost: "Òye owó", f_any_cost: "Gbogbo òye owó", f_low_cost: "₦ Kéré", f_mid_cost: "₦₦ Déédé", f_high_cost: "₦₦₦ Àṣìkù",
};
